{
  "hash": "889b1d31b82ad11211519b63023b5168",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"A Causal Graph Is Not One Graph: Bayesian Discovery with CPDAG Posteriors\"\nauthor: \"Carlos Trujillo\"\ndate: \"2026-08-30\"\ndescription: \"What if our Bayesian model is wrong? A visual walk from uncertainty about models to DAGs, CPDAG probabilities, and causal effects.\"\nimage: \"/images/bayesian_cpdag_graph_discovery.png\"\nimage-alt: \"Several causal graph equivalence classes receiving different amounts of posterior probability.\"\ncategories: [causal inference, bayesian, graphical models, causal discovery, python]\njupyter: cetagostini_web_new\nexecute:\n  conda: cetagostini_web_new\nresources:\n  - graph_math.py\n  - graph_sampling.py\n  - graph_checks.py\nformat:\n  html:\n    code-fold: false\n    code-tools: true\n    code-overflow: wrap\n---\n\n# Introduction\n\nAs a Bayesian, I often stop to ask what uncertainty I'm actually reporting. A posterior can look careful and precise. But what have I allowed myself to be uncertain about?\n\nI find the distinction between **epistemic** and **aleatoric** uncertainty useful here. The first is about what we do not know. The second is about randomness in the process we are modeling. A parameter posterior describes the first; predictions for a new outcome can combine both. Even if we knew every parameter, the next outcome could still vary.\n\nInside epistemic uncertainty, though, there is another question: **what if I chose the wrong model?**\n\nSuppose I fit a model in which $b$ causes $y$. I can get a posterior for that effect. But unless I put alternative causal structures into the analysis, that posterior does not ask whether $y$ causes $b$ instead. Or whether some other variable explains their association.\n\nEverything is conditional on the assumptions I wrote down. A wrong model can still give me a narrow posterior. What it does not give me automatically is uncertainty about the mistakes it cannot represent.\n\n![Uncertainty about an outcome is not the same as uncertainty about parameters or a graph. All of these calculations still sit inside a chosen family of models.](images/uncertainty-map.svg){#fig-uncertainty-map fig-alt=\"A map separates outcome randomness from unknown parameters and graph structure, and shows shared modeling assumptions outside those candidate choices.\"}\n\nSo could we make the model itself uncertain? Could we build a **model of models**?\n\nThat is the part I want to explore here. We'll use Bayesian causal discovery to put probabilities on candidate graphs, see why several graphs sometimes deserve one shared summary, and carry those possibilities into a causal effect. We will also deliberately try a case our assumptions cannot handle. I want us to leave with a useful answer, not the impression that adding another posterior makes the assumptions disappear.\n\n# Quick summary\n\nThis article walks you through:\n\n- **A model of models:** what we need to specify before a graph can receive a probability.\n- **DAGs and CPDAGs:** why several different drawings can tell the same observational story.\n- **A smaller search:** directional-prior matrices and hard masks, followed by MCMC for unresolved directions and exact updates for terminal parents.\n- **An intervention:** how uncertainty about arrows becomes uncertainty about an effect.\n- **The limits:** a nonlinear counterexample, the role of priors, and what probabilistic programming tools can do here.\n\nThe long code blocks are folded. The mathematical and sampling details are available in expandable notes, so we can follow the main story without reading the graph-search machinery first.\n\n# Theoretical lens\n\n## How could we build a model of models?\n\nWe do not need a new version of Bayes' rule. We need to let the model index be unknown, alongside its parameters.\n\nCall the candidate model $M$ and its parameters $\\theta_M$. Then our joint posterior is\n\n$$\np(M,\\theta_M\\mid D)\n\\propto p(D\\mid M,\\theta_M)\\,p(\\theta_M\\mid M)\\,\\pi(M).\n$$\n\nWe have three things to write down: how a candidate generates data, what its parameters could be, and how much prior probability it receives. The data update the relative weights. Instead of choosing one model and forgetting the others, we can keep that distribution.\n\nThis is one joint Bayesian model, not a separate PyMC fit for every candidate. A sampled graph is a possible value of the structural unknown, just as a sampled coefficient is a possible value of a regression parameter. Separate fits later in the article change the prior assumptions for a sensitivity analysis.\n\nThere is a catch, of course. We have to choose the candidates. If every candidate leaves out the same important cause, the posterior has nowhere to put that possibility. “A model of models” is still a model.\n\n## How does causality make that manageable?\n\nCausal graphs give us a compact way to describe one part of a model: **which variables enter which mechanisms**. An arrow $x\\rightarrow y$ says that $x$ is a direct input to the mechanism for $y$. It does not tell us the shape or size of that effect.\n\n![The graph specifies an input to a mechanism; the equation specifies how that input acts. A straight line and a curved relationship can share the same DAG.](images/model-to-dag.svg){#fig-model-to-dag fig-alt=\"The arrow x to y is paired with an equation and with straight and curved mechanisms, separating who affects whom from how the effect works.\"}\n\nA **directed acyclic graph**, or DAG, has arrows and no directed cycle: following arrows cannot bring us back to where we started. That lets us build a system one mechanism at a time. For now, we will not model feedback loops or hidden common causes.\n\nA graph alone is not a complete statistical model. We must also choose the mechanisms and their noise. To keep this first walk manageable, we use linear equations with independent Gaussian errors:\n\n$$\nX_i=\\alpha_i+\\sum_{j\\in\\mathrm{Pa}_i(G)}\\beta_{ij}X_j+\\varepsilon_i,\n\\qquad \\varepsilon_i\\sim\\mathcal N(0,\\sigma_i^2).\n$$\n\nThe parents $\\mathrm{Pa}_i(G)$ are simply the nodes with arrows into $i$. Choosing a DAG chooses which coefficients appear. The intercepts, coefficients, and noise scales remain unknown.\n\nSo we are not searching through every model anyone could write. We are comparing **linear-Gaussian causal models on a fixed set of measured variables**. We assume independent, complete observations and no hidden common causes. We also use the causal Markov and faithfulness assumptions to connect graph structure with conditional independence: the graph implies some independences, and faithfulness rules out extra ones caused by exact cancellations.\n\nYes, we still have to assume something. The benefit is that we can now say clearly what is uncertain and what we have held fixed. Later, we will see what happens when the relationship is not linear.\n\n# Getting started\n\nWe will use seven variables. There are 1,138,779,265 labeled DAGs on seven nodes, so this is no longer an example where we normalize a list of every graph. Instead, PyMC samples a shared, unknown DAG for the whole dataset. The linear-Gaussian parameters can still be integrated out exactly.\n\nThis notebook uses the `cetagostini_web_new` kernel, PyMC 6, `pymc.dims`, and PyTensor's named tensors. The graph and scoring utilities are available as [graph_math.py](graph_math.py), [graph_sampling.py](graph_sampling.py), and [graph_checks.py](graph_checks.py). They keep the code below focused on the model, rather than on bit masks and transition bookkeeping.\n\n::: {#f8268451 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Imports and reproducible streams\"}\nimport time\nfrom collections import Counter\nfrom importlib.metadata import version\nfrom math import comb, prod\n\nimport arviz_base as azb\nimport arviz_stats as azs\nimport matplotlib.pyplot as plt\nimport networkx as nx\nimport numpy as np\nimport pandas as pd\nimport pymc as pm\nimport pymc.dims as pmd\nimport pytensor.tensor as pt\nimport pytensor.xtensor as ptx\nfrom IPython.display import Markdown, display\nfrom matplotlib.patches import FancyArrowPatch\nfrom scipy.special import softmax\nfrom scipy.stats import gaussian_kde\n\nfrom cetagostini.style import COLORS, PALETTE, article_table, setup_notebook\nfrom graph_math import (\n    BGeScore, cpdag, draw_parameters, mec_key, pair_probabilities, pairs_for,\n    states_to_parents, simulate_scm, total_effects,\n)\nfrom graph_sampling import (\n    TemperedGraphStep, initial_states, terminal_parent_distributions,\n)\nfrom graph_checks import check_small_graphs\n\nsetup_notebook(figsize=(8, 5), warnings_filter=\"\")\n# The local sans-serif fallback supplies bold, but not semibold.\nplt.rcParams[\"axes.titleweight\"] = \"bold\"\nSEED = 20260909\nrng_data = np.random.default_rng(SEED)\nrng_effect = np.random.default_rng(SEED + 1)\nrng_predictive = np.random.default_rng(SEED + 2)\nprint(f\"Data seed: {SEED}; PyMC {pm.__version__}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData seed: 20260909; PyMC 6.3.2\n```\n:::\n:::\n\n\n# Let's make a world we can check\n\nThere are four independent root causes: $a,b,c,d$. Both $a$ and $b$ affect $e$; $d$ affects $f$. Finally, $a,b,c,e,f$ each directly affect $y$:\n\n$$\n\\begin{aligned}\na&=\\varepsilon_a, &b&=\\varepsilon_b, &c&=\\varepsilon_c, &d&=\\varepsilon_d,\\\\\ne&=0.9a+0.8b+\\varepsilon_e,\\\\\nf&=0.9d+\\varepsilon_f,\\\\\ny&=0.55a+0.5b+0.6c+0.7e+0.8f+\\varepsilon_y.\n\\end{aligned}\n$$\n\nThe seven errors are mutually independent $\\mathcal N(0,1)$. These are structural equations: an intervention replaces one equation and leaves the other mechanisms unchanged. Under the generating model, increasing $d$ by one unit changes the mean of $y$ by $0.9\\times0.8=0.72$ through $f$.\n\n::: {#3071714a .cell execution_count=2}\n``` {.python .cell-code}\nlabels = (\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"y\")\nn_nodes, n_obs = len(labels), 300\npairs = pairs_for(n_nodes)\na, b, c, d = rng_data.normal(size=(4, n_obs))\ne = 0.9 * a + 0.8 * b + rng_data.normal(size=n_obs)\nf = 0.9 * d + rng_data.normal(size=n_obs)\ny = 0.55 * a + 0.5 * b + 0.6 * c + 0.7 * e + 0.8 * f + rng_data.normal(size=n_obs)\ndata = np.column_stack([a, b, c, d, e, f, y])\n\ntruth = np.array([0, 0, 0, 0, (1 << 0) | (1 << 1), 1 << 3,\n                  sum(1 << i for i in (0, 1, 2, 4, 5))])\nobservational_twin = truth.copy()\nobservational_twin[3], observational_twin[5] = 1 << 5, 0\ntruth_key = mec_key(truth)\nassert mec_key(observational_twin) == truth_key\nassert sum(int(mask).bit_count() for mask in truth) == 8\nprint(f\"{n_obs} observations; {n_nodes} nodes; 8 generating arrows\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n300 observations; 7 nodes; 8 generating arrows\n```\n:::\n:::\n\n\nWe know the generating order because we wrote the equations. The discovery model does **not** receive that order, the generating adjacency matrix, or a maximum-parent restriction. We will give it only one piece of directional knowledge: $y$ has no outgoing arrows. Its parents and the directions among the other six variables remain unknown.\n\nBefore fitting anything, compare these two DAGs. Reversing $d\\rightarrow f$ gives a different intervention story, but the same observational equivalence class.\n\nA CPDAG summarizes that class: its arrows are shared by both DAGs, while an undirected edge marks the direction that can still reverse.\n\n::: {#cell-fig-true-dag-cpdag .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Draw DAGs and completed equivalence classes\"}\ndef draw_graph(ax, adjacency, title):\n    positions = {0: (-1.7, 1.9), 1: (-0.5, 2.4), 2: (0.6, 1.9),\n                 3: (1.9, 2.4), 4: (-1.0, 0.8), 5: (1.4, 0.8), 6: (0.0, -0.5)}\n    graph = nx.empty_graph(n_nodes)\n    nx.draw_networkx_nodes(graph, positions, node_size=650,\n                          node_color=COLORS[\"surface_alt\"], edgecolors=COLORS[\"primary\"], ax=ax)\n    nx.draw_networkx_labels(graph, positions, labels=dict(enumerate(labels)),\n                           font_color=COLORS[\"ink\"], font_weight=\"bold\", ax=ax)\n    for i, j in pairs:\n        if not (adjacency[i, j] or adjacency[j, i]):\n            continue\n        undirected = adjacency[i, j] and adjacency[j, i]\n        start, end = (i, j) if adjacency[i, j] else (j, i)\n        ax.add_patch(FancyArrowPatch(\n            positions[start], positions[end], arrowstyle=\"-\" if undirected else \"-|>\",\n            mutation_scale=14, linewidth=1.6, shrinkA=16, shrinkB=16,\n            linestyle=\"--\" if undirected else \"-\",\n            color=COLORS[\"brown\"] if undirected else COLORS[\"green_strong\"],\n        ))\n    ax.set(title=title, xlim=(-2.1, 2.3), ylim=(-0.9, 2.8), aspect=\"equal\")\n    ax.axis(\"off\")\n\n\ndef adjacency_of(parents):\n    return np.array([[bool(int(parents[j]) & (1 << i)) for j in range(n_nodes)]\n                     for i in range(n_nodes)])\n\n\nfig, axes = plt.subplots(1, 3, figsize=(12, 4.4))\nfor ax, matrix, title in zip(axes, [adjacency_of(truth), adjacency_of(observational_twin), cpdag(truth)],\n                            [\"Generating DAG\", \"Equivalent DAG\", \"Shared CPDAG\"]):\n    draw_graph(ax, matrix, title)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The generating DAG and its observational twin differ only in d–f. Their CPDAG has seven compelled arrows and one undirected edge. Reversing an arrow requires reparameterizing the mechanisms, not reusing the generating coefficients.](bayesian_cpdag_graph_discovery_files/figure-html/fig-true-dag-cpdag-output-1.png){#fig-true-dag-cpdag width=1877 height=624 fig-alt='Three seven-node diagrams. Both a and b point into e; a, b, c, e and f point into y. The d-f edge points toward f, toward d, or remains undirected in the three panels.'}\n:::\n:::\n\n\nIn this linear-Gaussian family, those DAGs can represent exactly the same observational distribution with different coefficients and noise scales. Recovering the right observational relationships need not recover every causal direction.\n\n\n# Why do we need a CPDAG?\n\n## What does “completed partially directed” mean?\n\nLet's unpack the name. A **CPDAG** is a **completed partially directed acyclic graph**. It represents a whole *Markov-equivalence class*: the DAGs with the same conditional-independence implications.\n\n- **Partially directed** means that some connections may have arrows while others remain undirected.\n- **Completed** means that every arrow shared by all DAGs in the class has been oriented. It does **not** mean that every pair of nodes is connected.\n- An **undirected edge** is a connection whose direction differs across members of the class. It is not two opposite causal arrows, and it is not an absent edge.\n\nA DAG gives us one fully directed candidate. PDAG simply says that a graph is partly directed; it does not certify that its arrows are exactly the ones shared by an observational equivalence class. A CPDAG gives us that completed class summary. Despite the word “partially,” it can be fully directed when its class contains only one DAG.\n\nA simpler three-variable picture helps:\n\n![The chain and fork DAGs share one CPDAG. The collider belongs to a different class, even though all four DAGs have the same connections.](images/dag-to-cpdag.svg){#fig-dag-to-cpdag fig-alt=\"Three DAGs without a collider share the undirected chain a-b-y. The collider a to b from y forms a separate class with both arrows fixed.\"}\n\nIn the chain and fork, $a$ and $y$ are separated by conditioning on $b$. In the collider $a\\rightarrow b\\leftarrow y$, $a$ and $y$ are separated before conditioning on $b$; conditioning on that shared effect can make them dependent. The arrows into the middle node change the independence story.\n\nThe [Verma–Pearl characterization](https://ftp.cs.ucla.edu/pub/stat_ser/R150.pdf) gives us a practical rule: two DAGs are Markov equivalent exactly when they share the same **skeleton** and **unshielded colliders**. The skeleton is the set of connections with arrowheads removed. An unshielded collider is a pair of arrows into a shared child whose parents are not connected.\n\n\nHere, $a\\rightarrow e\\leftarrow b$ fixes the arrows into $e$. The unshielded colliders at $y$ fix all five arrows into $y$. The $d$–$f$ connection can still reverse. The resulting class contains exactly the two DAGs in @fig-true-dag-cpdag.\n\nWe group sampled DAGs by their skeleton and colliders, then compute each class's CPDAG from a representative DAG using compelled-edge orientation. We do **not** intersect only the DAGs visited by MCMC: missing a member would otherwise make a reversible edge look compelled.\n\n# How do we give a DAG a probability?\n\nFor a DAG $G$, Bayes' rule gives\n\n$$\np(G\\mid D)\\propto p(D\\mid G)\\,\\pi(G),\\qquad\np(D\\mid G)=\\int p(D\\mid\\theta_G,G)\\,p(\\theta_G\\mid G)\\,d\\theta_G.\n$$\n\nThe integral averages the likelihood over the **parameter prior**, not over fitted posterior draws. We do not fit each graph, take its best likelihood, and call that a posterior probability. Here a compatible normal-Wishart construction gives the **Bayesian Gaussian equivalent**, or **BGe**, score. It integrates out the intercepts, regression coefficients, and noise variances exactly.\n\nEquivalent DAGs have equal BGe evidence. This **score equivalence** depends on the likelihood and the coherent parameter priors; it is not a property of arbitrary priors attached separately to each regression.\n\n## Two distinct prior choices\n\nFirst, assign a categorical state to each unordered pair: absent, forward, or backward. Before adding directional restrictions, the baseline probabilities are $(1/3,1/3,1/3)$. Conditioning their product on acyclicity gives equal probability to every legal DAG. It does not give equal probability to every CPDAG: a class with more members starts with more mass.\n\nWe will condition this prior on a hard mask, then vary the remaining directional preferences. Eligible score-equivalent DAGs retain equal evidence; unequal graph priors can still give them unequal posterior weights.\n\nSecond, choose a common parameter prior in the variables' measurement units. We set the prior mean $\\nu=0$, mean precision $\\alpha_\\mu=1$, and Wishart degrees of freedom $\\alpha_W=p+4$. With anticipated scales $s_i$, our prior scale matrix is\n\n$$\nT=(\\alpha_W-p-1)\\operatorname{diag}(s_1^2,\\ldots,s_p^2).\n$$\n\nUnder the complete Gaussian reference model this makes $\\mathbb E[\\Sigma]=\\operatorname{diag}(s_i^2)$. It does not fix any graph's coefficients or residual variances. The restricted DAG models inherit compatible local priors from this construction. We choose the scales before fitting; they are not sample standard deviations disguised as prior knowledge.\n\n::: {#66be8fb0 .cell execution_count=4}\n``` {.python .cell-code}\nprior_sd = np.array([1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 2.0])\nscore = BGeScore(data, prior_sd=prior_sd, alpha_mu=1.0, alpha_w=n_nodes + 4)\nprint(f\"Local parent sets: {n_nodes * 2 ** (n_nodes - 1)}; complete DAG enumeration: none\")\nprint(f\"Equivalent-DAG log-evidence difference: \"\n      f\"{score.graph_score(truth) - score.graph_score(observational_twin):.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLocal parent sets: 448; complete DAG enumeration: none\nEquivalent-DAG log-evidence difference: 0.00e+00\n```\n:::\n:::\n\n\nThe score cache contains 448 valid **local parent sets**, not 448 candidate DAGs. We compute those local terms once and reuse them. The mask below reduces which combinations are admissible without changing the underlying parameter prior.\n\n::: {.callout-note collapse=\"true\"}\n## The collapsed likelihood and its parameter prior\n\nFor $S$ of size $\\ell$, let $a_S=\\alpha_W-p+\\ell$. With $N$ observations,\n\n$$\nR=T+\\sum_{r=1}^N(x_r-\\bar x)(x_r-\\bar x)^\\top\n  +\\frac{N\\alpha_\\mu}{N+\\alpha_\\mu}(\\bar x-\\nu)(\\bar x-\\nu)^\\top.\n$$\n\nThe subset marginal likelihood is\n\n$$\n\\begin{aligned}\n\\log M(S)={}&\\frac{\\ell}{2}\\log\\frac{\\alpha_\\mu}{N+\\alpha_\\mu}\n+\\log\\frac{\\Gamma_\\ell((N+a_S)/2)}{\\Gamma_\\ell(a_S/2)}\n-\\frac{N\\ell}{2}\\log\\pi\\\\\n&+\\frac{a_S}{2}\\log|T_S|-\\frac{N+a_S}{2}\\log|R_S|.\n\\end{aligned}\n$$\n\nWe sum $\\log M(P_i\\cup\\{i\\})-\\log M(P_i)$ over nodes. The cached table subtracts each node's empty-parent score, a graph-independent constant that does not change posterior weights. Determinants are taken on the indicated submatrices, not on submatrices of an inverse. See [Geiger and Heckerman (1994)](https://www.microsoft.com/en-us/research/publication/learning-gaussian-networks/) and the correction by [Kuipers, Moffa, and Heckerman (2014)](https://doi.org/10.1214/14-AOS1217).\n:::\n\n# Restrict impossible arrows, not unknown ones\n\nHow would we enter the belief that $a\\rightarrow y$ is more plausible than $y\\rightarrow a$? Use a matrix $P$ with **sources in rows and targets in columns**. For an unordered pair $(i,j)$, its three local probabilities are\n\n$$\nq_{ij}=\\big[1-P_{ij}-P_{ji},\\;P_{ij},\\;P_{ji}\\big].\n$$\n\nThe entries $P_{ij}$ and $P_{ji}$ must sum to at most one; a row need not sum to one because a node may have several children. These are local probabilities **before conditioning on acyclicity and the hard mask**, not guaranteed marginal probabilities in the resulting DAG prior.\n\nFor example, $P_{ay}=0.7$ and $P_{ya}=0.1$ give probabilities $(0.2,0.7,0.1)$. Forbidding $y\\rightarrow a$ conditions that row to $(2/9,7/9,0)$. It preserves the relative odds of absence and $a\\rightarrow y$; it does not force the surviving arrow.\n\n::: {#5e6c89de .cell execution_count=5}\n``` {.python .cell-code}\ndirection_prior = pd.DataFrame(\n    (1 - np.eye(n_nodes)) / 3, index=labels, columns=labels,\n)\nallowed = pd.DataFrame(\n    ~np.eye(n_nodes, dtype=bool), index=labels, columns=labels,\n)\nallowed.loc[\"y\", :] = False\n\nbaseline_probs = pair_probabilities(\n    direction_prior.to_numpy(), allowed.to_numpy(),\n)\n```\n:::\n\n\nThe Boolean mask is **background knowledge**, not an inference from the correlations. It would be appropriate if $y$ is an outcome that cannot cause the other recorded variables. In this synthetic example it is true, but we still have not supplied its five parents. Exact zeros remove forbidden states; small positive probabilities would only discourage them.\n\n::: {#e336643f .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Display the two reader-facing matrices\"}\ndisplay(article_table(\n    direction_prior.reset_index(names=\"\"),\n    \"Directional prior before hard restrictions: row → column\",\n    formats={node: \"{:.2f}\" for node in labels},\n))\ndisplay(article_table(\n    allowed.astype(int).reset_index(names=\"\"),\n    \"Allowed directions: row → column; 1 permits an arrow, 0 forbids it\",\n))\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_05dcc th {\n  text-align: left;\n}\n#T_05dcc td {\n  text-align: left;\n}\n#T_05dcc_row0_col0, #T_05dcc_row0_col1, #T_05dcc_row0_col2, #T_05dcc_row0_col3, #T_05dcc_row0_col4, #T_05dcc_row0_col5, #T_05dcc_row0_col6, #T_05dcc_row0_col7, #T_05dcc_row1_col0, #T_05dcc_row1_col1, #T_05dcc_row1_col2, #T_05dcc_row1_col3, #T_05dcc_row1_col4, #T_05dcc_row1_col5, #T_05dcc_row1_col6, #T_05dcc_row1_col7, #T_05dcc_row2_col0, #T_05dcc_row2_col1, #T_05dcc_row2_col2, #T_05dcc_row2_col3, #T_05dcc_row2_col4, #T_05dcc_row2_col5, #T_05dcc_row2_col6, #T_05dcc_row2_col7, #T_05dcc_row3_col0, #T_05dcc_row3_col1, #T_05dcc_row3_col2, #T_05dcc_row3_col3, #T_05dcc_row3_col4, #T_05dcc_row3_col5, #T_05dcc_row3_col6, #T_05dcc_row3_col7, #T_05dcc_row4_col0, #T_05dcc_row4_col1, #T_05dcc_row4_col2, #T_05dcc_row4_col3, #T_05dcc_row4_col4, #T_05dcc_row4_col5, #T_05dcc_row4_col6, #T_05dcc_row4_col7, #T_05dcc_row5_col0, #T_05dcc_row5_col1, #T_05dcc_row5_col2, #T_05dcc_row5_col3, #T_05dcc_row5_col4, #T_05dcc_row5_col5, #T_05dcc_row5_col6, #T_05dcc_row5_col7, #T_05dcc_row6_col0, #T_05dcc_row6_col1, #T_05dcc_row6_col2, #T_05dcc_row6_col3, #T_05dcc_row6_col4, #T_05dcc_row6_col5, #T_05dcc_row6_col6, #T_05dcc_row6_col7 {\n  text-align: left;\n}\n</style>\n<table id=\"T_05dcc\">\n  <caption>Directional prior before hard restrictions: row → column</caption>\n  <thead>\n    <tr>\n      <th id=\"T_05dcc_level0_col0\" class=\"col_heading level0 col0\" ></th>\n      <th id=\"T_05dcc_level0_col1\" class=\"col_heading level0 col1\" >a</th>\n      <th id=\"T_05dcc_level0_col2\" class=\"col_heading level0 col2\" >b</th>\n      <th id=\"T_05dcc_level0_col3\" class=\"col_heading level0 col3\" >c</th>\n      <th id=\"T_05dcc_level0_col4\" class=\"col_heading level0 col4\" >d</th>\n      <th id=\"T_05dcc_level0_col5\" class=\"col_heading level0 col5\" >e</th>\n      <th id=\"T_05dcc_level0_col6\" class=\"col_heading level0 col6\" >f</th>\n      <th id=\"T_05dcc_level0_col7\" class=\"col_heading level0 col7\" >y</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_05dcc_row0_col0\" class=\"data row0 col0\" >a</td>\n      <td id=\"T_05dcc_row0_col1\" class=\"data row0 col1\" >0.00</td>\n      <td id=\"T_05dcc_row0_col2\" class=\"data row0 col2\" >0.33</td>\n      <td id=\"T_05dcc_row0_col3\" class=\"data row0 col3\" >0.33</td>\n      <td id=\"T_05dcc_row0_col4\" class=\"data row0 col4\" >0.33</td>\n      <td id=\"T_05dcc_row0_col5\" class=\"data row0 col5\" >0.33</td>\n      <td id=\"T_05dcc_row0_col6\" class=\"data row0 col6\" >0.33</td>\n      <td id=\"T_05dcc_row0_col7\" class=\"data row0 col7\" >0.33</td>\n    </tr>\n    <tr>\n      <td id=\"T_05dcc_row1_col0\" class=\"data row1 col0\" >b</td>\n      <td id=\"T_05dcc_row1_col1\" class=\"data row1 col1\" >0.33</td>\n      <td id=\"T_05dcc_row1_col2\" class=\"data row1 col2\" >0.00</td>\n      <td id=\"T_05dcc_row1_col3\" class=\"data row1 col3\" >0.33</td>\n      <td id=\"T_05dcc_row1_col4\" class=\"data row1 col4\" >0.33</td>\n      <td id=\"T_05dcc_row1_col5\" class=\"data row1 col5\" >0.33</td>\n      <td id=\"T_05dcc_row1_col6\" class=\"data row1 col6\" >0.33</td>\n      <td id=\"T_05dcc_row1_col7\" class=\"data row1 col7\" >0.33</td>\n    </tr>\n    <tr>\n      <td id=\"T_05dcc_row2_col0\" class=\"data row2 col0\" >c</td>\n      <td id=\"T_05dcc_row2_col1\" class=\"data row2 col1\" >0.33</td>\n      <td id=\"T_05dcc_row2_col2\" class=\"data row2 col2\" >0.33</td>\n      <td id=\"T_05dcc_row2_col3\" class=\"data row2 col3\" >0.00</td>\n      <td id=\"T_05dcc_row2_col4\" class=\"data row2 col4\" >0.33</td>\n      <td id=\"T_05dcc_row2_col5\" class=\"data row2 col5\" >0.33</td>\n      <td id=\"T_05dcc_row2_col6\" class=\"data row2 col6\" >0.33</td>\n      <td id=\"T_05dcc_row2_col7\" class=\"data row2 col7\" >0.33</td>\n    </tr>\n    <tr>\n      <td id=\"T_05dcc_row3_col0\" class=\"data row3 col0\" >d</td>\n      <td id=\"T_05dcc_row3_col1\" class=\"data row3 col1\" >0.33</td>\n      <td id=\"T_05dcc_row3_col2\" class=\"data row3 col2\" >0.33</td>\n      <td id=\"T_05dcc_row3_col3\" class=\"data row3 col3\" >0.33</td>\n      <td id=\"T_05dcc_row3_col4\" class=\"data row3 col4\" >0.00</td>\n      <td id=\"T_05dcc_row3_col5\" class=\"data row3 col5\" >0.33</td>\n      <td id=\"T_05dcc_row3_col6\" class=\"data row3 col6\" >0.33</td>\n      <td id=\"T_05dcc_row3_col7\" class=\"data row3 col7\" >0.33</td>\n    </tr>\n    <tr>\n      <td id=\"T_05dcc_row4_col0\" class=\"data row4 col0\" >e</td>\n      <td id=\"T_05dcc_row4_col1\" class=\"data row4 col1\" >0.33</td>\n      <td id=\"T_05dcc_row4_col2\" class=\"data row4 col2\" >0.33</td>\n      <td id=\"T_05dcc_row4_col3\" class=\"data row4 col3\" >0.33</td>\n      <td id=\"T_05dcc_row4_col4\" class=\"data row4 col4\" >0.33</td>\n      <td id=\"T_05dcc_row4_col5\" class=\"data row4 col5\" >0.00</td>\n      <td id=\"T_05dcc_row4_col6\" class=\"data row4 col6\" >0.33</td>\n      <td id=\"T_05dcc_row4_col7\" class=\"data row4 col7\" >0.33</td>\n    </tr>\n    <tr>\n      <td id=\"T_05dcc_row5_col0\" class=\"data row5 col0\" >f</td>\n      <td id=\"T_05dcc_row5_col1\" class=\"data row5 col1\" >0.33</td>\n      <td id=\"T_05dcc_row5_col2\" class=\"data row5 col2\" >0.33</td>\n      <td id=\"T_05dcc_row5_col3\" class=\"data row5 col3\" >0.33</td>\n      <td id=\"T_05dcc_row5_col4\" class=\"data row5 col4\" >0.33</td>\n      <td id=\"T_05dcc_row5_col5\" class=\"data row5 col5\" >0.33</td>\n      <td id=\"T_05dcc_row5_col6\" class=\"data row5 col6\" >0.00</td>\n      <td id=\"T_05dcc_row5_col7\" class=\"data row5 col7\" >0.33</td>\n    </tr>\n    <tr>\n      <td id=\"T_05dcc_row6_col0\" class=\"data row6 col0\" >y</td>\n      <td id=\"T_05dcc_row6_col1\" class=\"data row6 col1\" >0.33</td>\n      <td id=\"T_05dcc_row6_col2\" class=\"data row6 col2\" >0.33</td>\n      <td id=\"T_05dcc_row6_col3\" class=\"data row6 col3\" >0.33</td>\n      <td id=\"T_05dcc_row6_col4\" class=\"data row6 col4\" >0.33</td>\n      <td id=\"T_05dcc_row6_col5\" class=\"data row6 col5\" >0.33</td>\n      <td id=\"T_05dcc_row6_col6\" class=\"data row6 col6\" >0.33</td>\n      <td id=\"T_05dcc_row6_col7\" class=\"data row6 col7\" >0.00</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_c4190 th {\n  text-align: left;\n}\n#T_c4190 td {\n  text-align: left;\n}\n#T_c4190_row0_col0, #T_c4190_row0_col1, #T_c4190_row0_col2, #T_c4190_row0_col3, #T_c4190_row0_col4, #T_c4190_row0_col5, #T_c4190_row0_col6, #T_c4190_row0_col7, #T_c4190_row1_col0, #T_c4190_row1_col1, #T_c4190_row1_col2, #T_c4190_row1_col3, #T_c4190_row1_col4, #T_c4190_row1_col5, #T_c4190_row1_col6, #T_c4190_row1_col7, #T_c4190_row2_col0, #T_c4190_row2_col1, #T_c4190_row2_col2, #T_c4190_row2_col3, #T_c4190_row2_col4, #T_c4190_row2_col5, #T_c4190_row2_col6, #T_c4190_row2_col7, #T_c4190_row3_col0, #T_c4190_row3_col1, #T_c4190_row3_col2, #T_c4190_row3_col3, #T_c4190_row3_col4, #T_c4190_row3_col5, #T_c4190_row3_col6, #T_c4190_row3_col7, #T_c4190_row4_col0, #T_c4190_row4_col1, #T_c4190_row4_col2, #T_c4190_row4_col3, #T_c4190_row4_col4, #T_c4190_row4_col5, #T_c4190_row4_col6, #T_c4190_row4_col7, #T_c4190_row5_col0, #T_c4190_row5_col1, #T_c4190_row5_col2, #T_c4190_row5_col3, #T_c4190_row5_col4, #T_c4190_row5_col5, #T_c4190_row5_col6, #T_c4190_row5_col7, #T_c4190_row6_col0, #T_c4190_row6_col1, #T_c4190_row6_col2, #T_c4190_row6_col3, #T_c4190_row6_col4, #T_c4190_row6_col5, #T_c4190_row6_col6, #T_c4190_row6_col7 {\n  text-align: left;\n}\n</style>\n<table id=\"T_c4190\">\n  <caption>Allowed directions: row → column; 1 permits an arrow, 0 forbids it</caption>\n  <thead>\n    <tr>\n      <th id=\"T_c4190_level0_col0\" class=\"col_heading level0 col0\" ></th>\n      <th id=\"T_c4190_level0_col1\" class=\"col_heading level0 col1\" >a</th>\n      <th id=\"T_c4190_level0_col2\" class=\"col_heading level0 col2\" >b</th>\n      <th id=\"T_c4190_level0_col3\" class=\"col_heading level0 col3\" >c</th>\n      <th id=\"T_c4190_level0_col4\" class=\"col_heading level0 col4\" >d</th>\n      <th id=\"T_c4190_level0_col5\" class=\"col_heading level0 col5\" >e</th>\n      <th id=\"T_c4190_level0_col6\" class=\"col_heading level0 col6\" >f</th>\n      <th id=\"T_c4190_level0_col7\" class=\"col_heading level0 col7\" >y</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_c4190_row0_col0\" class=\"data row0 col0\" >a</td>\n      <td id=\"T_c4190_row0_col1\" class=\"data row0 col1\" >0</td>\n      <td id=\"T_c4190_row0_col2\" class=\"data row0 col2\" >1</td>\n      <td id=\"T_c4190_row0_col3\" class=\"data row0 col3\" >1</td>\n      <td id=\"T_c4190_row0_col4\" class=\"data row0 col4\" >1</td>\n      <td id=\"T_c4190_row0_col5\" class=\"data row0 col5\" >1</td>\n      <td id=\"T_c4190_row0_col6\" class=\"data row0 col6\" >1</td>\n      <td id=\"T_c4190_row0_col7\" class=\"data row0 col7\" >1</td>\n    </tr>\n    <tr>\n      <td id=\"T_c4190_row1_col0\" class=\"data row1 col0\" >b</td>\n      <td id=\"T_c4190_row1_col1\" class=\"data row1 col1\" >1</td>\n      <td id=\"T_c4190_row1_col2\" class=\"data row1 col2\" >0</td>\n      <td id=\"T_c4190_row1_col3\" class=\"data row1 col3\" >1</td>\n      <td id=\"T_c4190_row1_col4\" class=\"data row1 col4\" >1</td>\n      <td id=\"T_c4190_row1_col5\" class=\"data row1 col5\" >1</td>\n      <td id=\"T_c4190_row1_col6\" class=\"data row1 col6\" >1</td>\n      <td id=\"T_c4190_row1_col7\" class=\"data row1 col7\" >1</td>\n    </tr>\n    <tr>\n      <td id=\"T_c4190_row2_col0\" class=\"data row2 col0\" >c</td>\n      <td id=\"T_c4190_row2_col1\" class=\"data row2 col1\" >1</td>\n      <td id=\"T_c4190_row2_col2\" class=\"data row2 col2\" >1</td>\n      <td id=\"T_c4190_row2_col3\" class=\"data row2 col3\" >0</td>\n      <td id=\"T_c4190_row2_col4\" class=\"data row2 col4\" >1</td>\n      <td id=\"T_c4190_row2_col5\" class=\"data row2 col5\" >1</td>\n      <td id=\"T_c4190_row2_col6\" class=\"data row2 col6\" >1</td>\n      <td id=\"T_c4190_row2_col7\" class=\"data row2 col7\" >1</td>\n    </tr>\n    <tr>\n      <td id=\"T_c4190_row3_col0\" class=\"data row3 col0\" >d</td>\n      <td id=\"T_c4190_row3_col1\" class=\"data row3 col1\" >1</td>\n      <td id=\"T_c4190_row3_col2\" class=\"data row3 col2\" >1</td>\n      <td id=\"T_c4190_row3_col3\" class=\"data row3 col3\" >1</td>\n      <td id=\"T_c4190_row3_col4\" class=\"data row3 col4\" >0</td>\n      <td id=\"T_c4190_row3_col5\" class=\"data row3 col5\" >1</td>\n      <td id=\"T_c4190_row3_col6\" class=\"data row3 col6\" >1</td>\n      <td id=\"T_c4190_row3_col7\" class=\"data row3 col7\" >1</td>\n    </tr>\n    <tr>\n      <td id=\"T_c4190_row4_col0\" class=\"data row4 col0\" >e</td>\n      <td id=\"T_c4190_row4_col1\" class=\"data row4 col1\" >1</td>\n      <td id=\"T_c4190_row4_col2\" class=\"data row4 col2\" >1</td>\n      <td id=\"T_c4190_row4_col3\" class=\"data row4 col3\" >1</td>\n      <td id=\"T_c4190_row4_col4\" class=\"data row4 col4\" >1</td>\n      <td id=\"T_c4190_row4_col5\" class=\"data row4 col5\" >0</td>\n      <td id=\"T_c4190_row4_col6\" class=\"data row4 col6\" >1</td>\n      <td id=\"T_c4190_row4_col7\" class=\"data row4 col7\" >1</td>\n    </tr>\n    <tr>\n      <td id=\"T_c4190_row5_col0\" class=\"data row5 col0\" >f</td>\n      <td id=\"T_c4190_row5_col1\" class=\"data row5 col1\" >1</td>\n      <td id=\"T_c4190_row5_col2\" class=\"data row5 col2\" >1</td>\n      <td id=\"T_c4190_row5_col3\" class=\"data row5 col3\" >1</td>\n      <td id=\"T_c4190_row5_col4\" class=\"data row5 col4\" >1</td>\n      <td id=\"T_c4190_row5_col5\" class=\"data row5 col5\" >1</td>\n      <td id=\"T_c4190_row5_col6\" class=\"data row5 col6\" >0</td>\n      <td id=\"T_c4190_row5_col7\" class=\"data row5 col7\" >1</td>\n    </tr>\n    <tr>\n      <td id=\"T_c4190_row6_col0\" class=\"data row6 col0\" >y</td>\n      <td id=\"T_c4190_row6_col1\" class=\"data row6 col1\" >0</td>\n      <td id=\"T_c4190_row6_col2\" class=\"data row6 col2\" >0</td>\n      <td id=\"T_c4190_row6_col3\" class=\"data row6 col3\" >0</td>\n      <td id=\"T_c4190_row6_col4\" class=\"data row6 col4\" >0</td>\n      <td id=\"T_c4190_row6_col5\" class=\"data row6 col5\" >0</td>\n      <td id=\"T_c4190_row6_col6\" class=\"data row6 col6\" >0</td>\n      <td id=\"T_c4190_row6_col7\" class=\"data row6 col7\" >0</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n## Learn terminal parents exactly, then run MCMC on the remaining structure\n\nOnce $y$ has no outgoing arrows, any subset of the other six variables can be its parents without creating a cycle. Under our fixed pairwise graph prior and decomposable BGe score, its parent-set distribution separates from the remaining graph:\n\n$$\np(G_{-y},\\mathrm{Pa}_y\\mid D,K)\n=p(G_{-y}\\mid D,K)\\,p(\\mathrm{Pa}_y\\mid D,K),\n$$\n\nwhere $K$ is the terminal-node restriction. We can normalize the weights of all $2^6=64$ parent sets for $y$ exactly, while MCMC explores the unresolved graph $G_{-y}$ among the other six variables. After each cold-chain update, an independent draw of $\\mathrm{Pa}_y$ reconstructs a **full seven-node DAG**. We have reduced the sampling problem, not fixed the answer.\n\nThe exact parent weights use the original seven-variable BGe scores and the supported pair priors. Refitting a six-variable model with different parameter-prior settings would not be the same reduction.\n\n::: {#bafc8893 .cell execution_count=7}\n``` {.python .cell-code}\nterminal_posteriors = terminal_parent_distributions(\n    score.table, pairs, baseline_probs,\n)\n```\n:::\n\n\n::: {#b98eaf2e .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Count the search space without enumerating full graphs\"}\ndag_counts = [1]\nfor size in range(1, n_nodes + 1):\n    dag_counts.append(sum(\n        (-1) ** (sinks + 1) * comb(size, sinks)\n        * 2 ** (sinks * (size - sinks)) * dag_counts[size - sinks]\n        for sinks in range(1, size + 1)\n    ))\ncore_nodes = n_nodes - len(terminal_posteriors)\nterminal_combinations = prod(len(masks) for masks, _ in terminal_posteriors.values())\nspace = pd.DataFrame({\n    \"Quantity\": [\n        \"Admissible full DAGs\", \"DAG states left to MCMC\",\n        \"Pairs in MCMC proposals\", \"Admissible local parent sets\",\n    ],\n    \"Unrestricted\": [\n        dag_counts[n_nodes], dag_counts[n_nodes],\n        len(pairs), n_nodes * 2 ** (n_nodes - 1),\n    ],\n    \"Mask + terminal reduction\": [\n        dag_counts[core_nodes] * terminal_combinations, dag_counts[core_nodes],\n        len(pairs_for(core_nodes)), sum(2 ** int(count) for count in allowed.sum(axis=0)),\n    ],\n})\ndisplay(article_table(\n    space, \"Search-space sizes for this mask, not measured runtime speedups\",\n    formats={\"Unrestricted\": \"{:,.0f}\", \"Mask + terminal reduction\": \"{:,.0f}\"},\n))\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_3da9e th {\n  text-align: left;\n}\n#T_3da9e td {\n  text-align: left;\n}\n#T_3da9e_row0_col0, #T_3da9e_row0_col1, #T_3da9e_row0_col2, #T_3da9e_row1_col0, #T_3da9e_row1_col1, #T_3da9e_row1_col2, #T_3da9e_row2_col0, #T_3da9e_row2_col1, #T_3da9e_row2_col2, #T_3da9e_row3_col0, #T_3da9e_row3_col1, #T_3da9e_row3_col2 {\n  text-align: left;\n}\n</style>\n<table id=\"T_3da9e\">\n  <caption>Search-space sizes for this mask, not measured runtime speedups</caption>\n  <thead>\n    <tr>\n      <th id=\"T_3da9e_level0_col0\" class=\"col_heading level0 col0\" >Quantity</th>\n      <th id=\"T_3da9e_level0_col1\" class=\"col_heading level0 col1\" >Unrestricted</th>\n      <th id=\"T_3da9e_level0_col2\" class=\"col_heading level0 col2\" >Mask + terminal reduction</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_3da9e_row0_col0\" class=\"data row0 col0\" >Admissible full DAGs</td>\n      <td id=\"T_3da9e_row0_col1\" class=\"data row0 col1\" >1,138,779,265</td>\n      <td id=\"T_3da9e_row0_col2\" class=\"data row0 col2\" >242,016,192</td>\n    </tr>\n    <tr>\n      <td id=\"T_3da9e_row1_col0\" class=\"data row1 col0\" >DAG states left to MCMC</td>\n      <td id=\"T_3da9e_row1_col1\" class=\"data row1 col1\" >1,138,779,265</td>\n      <td id=\"T_3da9e_row1_col2\" class=\"data row1 col2\" >3,781,503</td>\n    </tr>\n    <tr>\n      <td id=\"T_3da9e_row2_col0\" class=\"data row2 col0\" >Pairs in MCMC proposals</td>\n      <td id=\"T_3da9e_row2_col1\" class=\"data row2 col1\" >21</td>\n      <td id=\"T_3da9e_row2_col2\" class=\"data row2 col2\" >15</td>\n    </tr>\n    <tr>\n      <td id=\"T_3da9e_row3_col0\" class=\"data row3 col0\" >Admissible local parent sets</td>\n      <td id=\"T_3da9e_row3_col1\" class=\"data row3 col1\" >448</td>\n      <td id=\"T_3da9e_row3_col2\" class=\"data row3 col2\" >256</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nThese counts use the fact that this particular mask leaves the six-node core unrestricted. The sink-set recurrence counts DAGs without listing them; it is not a counter for arbitrary masks. MCMC proposes only mutable, supported core pairs. Forbidden directions, fixed pair states, and terminal parent sets receive no wasted proposals. We still keep all 21 pair states in the returned draws so every downstream graph and intervention calculation sees the full structure.\n\n# The graph is a PyMC random variable\n\n`pymc.dims` uses **dimension names in tensor operations**, rather than merely attaching labels to positional arrays. We use ordinary PyTensor indexing to put each pair's state directly into an adjacency matrix, then name its axes `parent` and `child`. Named `.isel(mask=parents)` selects each node's current parent-set score. Concrete initial values and the Numba sampler's mutable arrays remain NumPy arrays; they are not symbolic tensors.\n\n::: {#ec96f5c6 .cell execution_count=9}\n``` {.python .cell-code}\ndef make_graph_model(score, pair_probs, labels):\n    \"\"\"One dataset, one unknown DAG; mechanisms are integrated out.\"\"\"\n    pairs = pairs_for(len(labels))\n    coords = {\n        \"node\": labels, \"parent\": labels, \"child\": labels,\n        \"pair\": [f\"{labels[i]}–{labels[j]}\" for i, j in pairs],\n        \"state\": [\"absent\", \"forward\", \"backward\"],\n        \"mask\": np.arange(2 ** len(labels)),\n    }\n    with pm.Model(coords=coords) as model:\n        probabilities = pmd.as_xtensor(pair_probs, dims=(\"pair\", \"state\"))\n        initial = initial_states(\n            pair_probs, pairs, len(labels), np.random.default_rng(0), empty=True,\n        )\n        edge = pmd.Categorical(\"edge\", p=probabilities, core_dims=\"state\", initval=initial)\n        i, j = pairs.T\n        state = edge.values\n        adjacency = pt.zeros((len(labels), len(labels)), dtype=\"int64\")\n        adjacency = pt.set_subtensor(adjacency[i, j], pt.eq(state, 1))\n        adjacency = pt.set_subtensor(adjacency[j, i], pt.eq(state, 2))\n        adjacency = pmd.as_xtensor(adjacency, dims=(\"parent\", \"child\"))\n        bits = pmd.as_xtensor(1 << np.arange(len(labels)), dims=(\"parent\",))\n        parents = (adjacency * bits).sum(\"parent\").rename({\"child\": \"node\"})\n        local_score = pmd.as_xtensor(score.table, dims=(\"node\", \"mask\"))\n        evidence = local_score.isel(mask=parents).sum(\"node\")\n        reach = adjacency.astype(\"bool\")\n        for k in range(len(labels)):\n            reach = reach | (reach.isel(child=k) & reach.isel(parent=k))\n        diagonal = pmd.as_xtensor(np.eye(len(labels), dtype=bool), dims=(\"parent\", \"child\"))\n        cycle = (reach & diagonal).any()\n        pmd.Potential(\"dag_support\", ptx.where(cycle, -np.inf, 0.0))\n        pmd.Potential(\"marginal_likelihood\", evidence)\n        pmd.Deterministic(\"log_evidence\", evidence)\n        pmd.Deterministic(\"edge_count\", ptx.math.neq(edge, 0).sum(\"pair\"))\n    return model\n```\n:::\n\n\nThe categorical prior gives forbidden states zero support, while transitive closure independently rejects directed cycles. `marginal_likelihood` supplies the integrated likelihood of the **whole dataset**. This is one model with an unknown graph, not one graph per row or a separate fit per candidate.\n\nWe can inspect this model with PyMC's own Graphviz visualization. @fig-pymc-graph-model shows the **probabilistic program**, not a sampled causal DAG or its CPDAG. The `edge` vector contains the unknown pair states; the other nodes impose graph support, add the collapsed likelihood, or record summaries. The regression coefficients and noise scales do not appear because we integrated them out. Likewise, the data enter through the precomputed score table, not a row-level observed random variable.\n\n::: {#cell-fig-pymc-graph-model .cell execution_count=10}\n``` {.python .cell-code}\ngraph_model = make_graph_model(score, baseline_probs, labels)\nmodel_graph = pm.model_to_graphviz(graph_model)\nmodel_graph.graph_attr.update(bgcolor=COLORS[\"bg\"], fontname=\"Inter, Helvetica, Arial, sans-serif\",\n                              fontcolor=COLORS[\"ink\"], color=COLORS[\"primary\"])\nmodel_graph.node_attr.update(fontname=\"Inter, Helvetica, Arial, sans-serif\", fontcolor=COLORS[\"ink\"],\n                             color=COLORS[\"primary\"], fillcolor=COLORS[\"surface_alt\"])\nmodel_graph.edge_attr.update(color=COLORS[\"green_strong\"])\nmodel_graph\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n![One categorical vector represents the unknown causal graph. PyMC's dependency graph shows how its states determine the support, collapsed likelihood, and recorded summaries; its arrows are not causal claims about a through y.](bayesian_cpdag_graph_discovery_files/figure-html/fig-pymc-graph-model-output-1.svg){#fig-pymc-graph-model fig-alt='PyMC model graph with a 21-pair categorical edge vector feeding the DAG-support and marginal-likelihood potentials and the log-evidence and edge-count deterministics.'}\n:::\n:::\n\n\nThese are experimental named-tensor APIs. In the tested PyMC version, the stock categorical Gibbs step does not recognize the named categorical operation. A custom graph step works with its value variable; PyTensor lowers the named operations when compiling the model. Notice the explicit symbolic comparisons, `pt.eq` and `ptx.math.neq`, rather than Python `==`. The [PyMC dims guide](https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/dims_module.html) and [PyTensor xtensor documentation](https://pytensor.readthedocs.io/en/latest/library/xtensor/index.html) explain the distinction between dimension-aware operations and output labels.\n\n## Moving between graphs\n\nNUTS cannot move through discrete graph states. We use a Metropolis kernel compiled with Numba and registered as a PyMC step. A proposal chooses a mutable core pair uniformly, then draws uniformly from **all its supported states, including the current state**. Self-proposals prevent deterministic alternation when only two states remain. Cyclic proposals are also retained as self-transitions; we do not redraw until an acyclic proposal appears. The support is fixed, so the proposal is symmetric and its Metropolis acceptance probability is\n\n$$\n\\min\\left(1,\\exp\\{\\log p(D\\mid G')-\\log p(D\\mid G)\n+\\log\\pi(G')-\\log\\pi(G)\\}\\right).\n$$\n\nThe kernel keeps rejected states. Keeping only accepted graphs would produce the wrong distribution. Its graph representation is just an implementation detail: a parent mask for each node, not one machine integer encoding an entire equivalence class.\n\nLocal moves can get stuck behind low-probability intermediate graphs. We therefore run parallel tempering on the reduced core: replicas target $p(D_{\\rm core}\\mid G_{-y})^\\beta\\pi_{\\rm core}(G_{-y})$, where the likelihood notation denotes the original core-node local scores, not a refitted six-variable prior. Terminal-parent normalizing constants depend on $\\beta$ but not on the core graph, so they cancel from swap ratios. Only the $\\beta=1$ core replica supplies posterior draws; we then sample terminal parents from their exact $\\beta=1$ distribution. A hot graph is not an additional posterior draw.\n\n::: {#d4240f63 .cell execution_count=11}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Independent starts and the PyMC sampling call\"}\nbetas = np.r_[np.geomspace(1.0, 0.002, 15), 0.0]\n\n\ndef fit_graphs(score, probabilities, labels, *, seed, draws, tune, betas, chains=4):\n    \"\"\"Sample unresolved core directions and reconstruct full posterior DAGs.\"\"\"\n    local_pairs = pairs_for(len(labels))\n    starts_rng = np.random.default_rng(seed)\n    starts = [\n        {\"edge\": initial_states(\n            probabilities, local_pairs, len(labels), starts_rng, empty=(chain == 0),\n        )}\n        for chain in range(chains)\n    ]\n    with make_graph_model(score, probabilities, labels) as model:\n        step = TemperedGraphStep(\n            [model[\"edge\"]], score.table, local_pairs, probabilities, betas,\n        )\n        return pm.sample(\n            draws=draws, tune=tune, chains=chains, cores=1,\n            step=step, initvals=starts, random_seed=seed,\n            progressbar=False, compute_convergence_checks=False,\n        )\n\n\ndraws, tune = 12_000, 3_000\nstarted = time.perf_counter()\nposterior = fit_graphs(\n    score, baseline_probs, labels,\n    seed=SEED + 10, draws=draws, tune=tune, betas=betas,\n)\nbaseline_seconds = time.perf_counter() - started\nprint(f\"Four chains × {draws:,} retained full DAGs; {baseline_seconds:.1f}s \"\n      \"including compilation and sampler setup\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 3_000 tune and 12_000 draw iterations (12_000 + 48_000 draws total) took 3 seconds.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nFour chains × 12,000 retained full DAGs; 3.6s including compilation and sampler setup\n```\n:::\n:::\n\n\nThe initializer assigns random topological ranks and constructs pair states directly. It respects forbidden and required states without a parent-mask roundtrip. The four cold chains start at different legal graphs, including the empty graph when the prior permits it; none is initialized from the generating DAG. Each chain receives independent random streams and fresh replica state. `cores=1` does not make them one chain.\n\nThe temperature ladder and proposal do not adapt during `tune`; those iterations discard initial transients. We retain the longer publication run because rare-class directional probabilities can remain noisy even when common graph events mix well. The diagnostics below concern full reconstructed graphs, not just the smaller core.\n\n\n# Did the graph chains explore the posterior?\n\nAcceptance rates alone do not answer this. We inspect rank-normalized $\\widehat R$, bulk and tail effective sample sizes, and Monte Carlo standard errors for **graph events**: each edge's presence and direction, leading-class membership, and whether $d$ has a directed path to $y$. We also inspect the edge count and collapsed log evidence. Treating the arbitrary codes 0, 1, 2 as a continuous diagnostic variable would miss the questions we care about.\n\n**ArviZ computes the diagnostics; our code defines what to diagnose.** Here `arviz_base` (`azb`) builds the labeled inference-data container and `arviz_stats` (`azs`) supplies `summary`. These are ArviZ's modular APIs, not custom replacements for its statistics.\n\nWhy not just call `summary(posterior)`? The mean of the categorical codes 0 = absent, 1 = forward, and 2 = backward is not an edge probability. Instead, we create binary indicators whose means are posterior event probabilities. We preserve the original chain and draw order so ArviZ can estimate their Monte Carlo errors and convergence diagnostics.\n\n`graph_summary` does a different job: it groups sampled DAGs by skeleton and unshielded colliders, accumulates their probability into Markov equivalence classes, and identifies directed paths. ArviZ does not know those graph-theoretic definitions. We classify each distinct DAG once, then map the results back to **every retained draw**; passing only the unique DAGs to ArviZ would destroy the frequencies and autocorrelation. Class IDs are labels too, so we diagnose class-membership indicators rather than their numeric IDs.\n\n::: {#c700a19b .cell execution_count=12}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Map graph draws into labeled events for ArviZ\"}\ndef graph_summary(trace):\n    \"\"\"Aggregate DAGs into equivalence classes, retaining per-draw membership.\"\"\"\n    states = trace.posterior.edge.values\n    unique, inverse, counts = np.unique(states.reshape(-1, len(pairs)), axis=0,\n                                         return_inverse=True, return_counts=True)\n    graphs = [states_to_parents(state, pairs, n_nodes) for state in unique]\n    keys = [mec_key(graph) for graph in graphs]\n    class_counts = Counter()\n    representative = {}\n    for key, graph, count in zip(keys, graphs, counts):\n        class_counts[key] += int(count)\n        representative[key] = graph\n    ranked = [key for key, _ in class_counts.most_common()]\n    class_lookup = {key: index for index, key in enumerate(ranked)}\n    class_id = np.array([class_lookup[key] for key in keys])[inverse].reshape(states.shape[:2])\n    paths = np.array([\n        total_effects(graph, adjacency_of(graph).T.astype(float))[6, 3] != 0\n        for graph in graphs\n    ])[inverse].reshape(states.shape[:2])\n    true_class = class_id == class_lookup[truth_key] if truth_key in class_lookup else np.zeros_like(paths)\n    return {\"states\": states, \"graphs\": graphs, \"ranked\": ranked,\n            \"class_counts\": class_counts, \"representative\": representative,\n            \"class_id\": class_id, \"true_class\": true_class, \"path\": paths}\n\n\ndef graph_diagnostic_data(trace, summary, probabilities):\n    \"\"\"Prepare chain-by-draw graph events; leave all diagnostics to ArviZ.\"\"\"\n    states = summary[\"states\"]\n    names, events, fixed = [], [], []\n    for k, (i, j) in enumerate(pairs):\n        for state, name in [(0, f\"{labels[i]}–{labels[j]} absent\"),\n                            (1, f\"{labels[i]}→{labels[j]}\"), (2, f\"{labels[j]}→{labels[i]}\")]:\n            names.append(name)\n            events.append(states[..., k] == state)\n            fixed.append(probabilities[k, state] == 0 or np.count_nonzero(probabilities[k]) == 1)\n    for index in range(min(4, len(summary[\"ranked\"]))):\n        names.append(f\"Class {index + 1}\")\n        events.append(summary[\"class_id\"] == index)\n        fixed.append(False)\n    names += [\"Generating class\", \"d has a path to y\"]\n    events += [summary[\"true_class\"], summary[\"path\"]]\n    fixed = np.asarray(fixed + [False, False])\n    values = np.stack(events, axis=-1).astype(float)\n    varying = np.ptp(values, axis=(0, 1)) > 0\n    quantities = {\"event\": values[..., varying]}\n    for name in (\"edge_count\", \"log_evidence\"):\n        value = trace.posterior[name].values\n        if np.ptp(value) > 0:\n            quantities[name] = value\n        else:\n            print(f\"{name} is constant; diagnostics not estimable\")\n    print(f\"Indicators fixed by pair support: {fixed.sum()}\")\n    print(f\"Other constant indicators: {(~varying & ~fixed).sum()} (diagnostics not estimable)\")\n    return azb.from_dict(\n        {\"posterior\": quantities},\n        dims={\"event\": [\"graph_event\"]},\n        coords={\"graph_event\": np.asarray(names)[varying]},\n    )\n```\n:::\n\n\nWith that graph-specific translation done, the summary is an ordinary ArviZ call. The table styling below changes presentation only; its means, MCSEs, effective sample sizes, and $\\widehat R$ all come from ArviZ.\n\n::: {#102e02b6 .cell execution_count=13}\n``` {.python .cell-code}\nsummary = graph_summary(posterior)\ndiagnostic_data = graph_diagnostic_data(posterior, summary, baseline_probs)\ndiagnostics = azs.summary(diagnostic_data, ci_prob=0.95, round_to=\"none\")\nprint(f\"Maximum R-hat: {diagnostics.r_hat.max():.4f}\")\nprint(f\"Minimum bulk ESS: {diagnostics.ess_bulk.min():.0f}\")\nprint(f\"Minimum tail ESS: {diagnostics.ess_tail.min():.0f}\")\nprint(f\"Maximum event MCSE: {diagnostics.loc[diagnostics.index.str.startswith('event['), 'mcse_mean'].max():.4f}\")\nprint(f\"Minimum reported bulk ESS per elapsed second: \"\n      f\"{diagnostics.ess_bulk.min() / baseline_seconds:.0f} (including startup)\")\nimportant = [name for name in diagnostics.index if any(\n    term in name for term in (\"d→f\", \"f→d\", \"Generating class\", \"d has a path\", \"edge_count\", \"log_evidence\")\n)]\ndisplay(article_table(diagnostics.loc[important, [\"mean\", \"mcse_mean\", \"ess_bulk\", \"ess_tail\", \"r_hat\"]].reset_index(names=\"Quantity\"),\n                      \"Monte Carlo diagnostics for decision-relevant quantities\",\n                      formats={\"mean\": \"{:.3f}\", \"mcse_mean\": \"{:.4f}\", \"ess_bulk\": \"{:.0f}\",\n                               \"ess_tail\": \"{:.0f}\", \"r_hat\": \"{:.4f}\"}))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIndicators fixed by pair support: 6\nOther constant indicators: 13 (diagnostics not estimable)\nMaximum R-hat: 1.0002\nMinimum bulk ESS: 11345\nMinimum tail ESS: 11345\nMaximum event MCSE: 0.0047\nMinimum reported bulk ESS per elapsed second: 3127 (including startup)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_e50ba th {\n  text-align: left;\n}\n#T_e50ba td {\n  text-align: left;\n}\n#T_e50ba_row0_col0, #T_e50ba_row0_col1, #T_e50ba_row0_col2, #T_e50ba_row0_col3, #T_e50ba_row0_col4, #T_e50ba_row0_col5, #T_e50ba_row1_col0, #T_e50ba_row1_col1, #T_e50ba_row1_col2, #T_e50ba_row1_col3, #T_e50ba_row1_col4, #T_e50ba_row1_col5, #T_e50ba_row2_col0, #T_e50ba_row2_col1, #T_e50ba_row2_col2, #T_e50ba_row2_col3, #T_e50ba_row2_col4, #T_e50ba_row2_col5, #T_e50ba_row3_col0, #T_e50ba_row3_col1, #T_e50ba_row3_col2, #T_e50ba_row3_col3, #T_e50ba_row3_col4, #T_e50ba_row3_col5, #T_e50ba_row4_col0, #T_e50ba_row4_col1, #T_e50ba_row4_col2, #T_e50ba_row4_col3, #T_e50ba_row4_col4, #T_e50ba_row4_col5, #T_e50ba_row5_col0, #T_e50ba_row5_col1, #T_e50ba_row5_col2, #T_e50ba_row5_col3, #T_e50ba_row5_col4, #T_e50ba_row5_col5 {\n  text-align: left;\n}\n</style>\n<table id=\"T_e50ba\">\n  <caption>Monte Carlo diagnostics for decision-relevant quantities</caption>\n  <thead>\n    <tr>\n      <th id=\"T_e50ba_level0_col0\" class=\"col_heading level0 col0\" >Quantity</th>\n      <th id=\"T_e50ba_level0_col1\" class=\"col_heading level0 col1\" >mean</th>\n      <th id=\"T_e50ba_level0_col2\" class=\"col_heading level0 col2\" >mcse_mean</th>\n      <th id=\"T_e50ba_level0_col3\" class=\"col_heading level0 col3\" >ess_bulk</th>\n      <th id=\"T_e50ba_level0_col4\" class=\"col_heading level0 col4\" >ess_tail</th>\n      <th id=\"T_e50ba_level0_col5\" class=\"col_heading level0 col5\" >r_hat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_e50ba_row0_col0\" class=\"data row0 col0\" >event[d→f]</td>\n      <td id=\"T_e50ba_row0_col1\" class=\"data row0 col1\" >0.436</td>\n      <td id=\"T_e50ba_row0_col2\" class=\"data row0 col2\" >0.0040</td>\n      <td id=\"T_e50ba_row0_col3\" class=\"data row0 col3\" >15628</td>\n      <td id=\"T_e50ba_row0_col4\" class=\"data row0 col4\" >15628</td>\n      <td id=\"T_e50ba_row0_col5\" class=\"data row0 col5\" >1.0001</td>\n    </tr>\n    <tr>\n      <td id=\"T_e50ba_row1_col0\" class=\"data row1 col0\" >event[f→d]</td>\n      <td id=\"T_e50ba_row1_col1\" class=\"data row1 col1\" >0.564</td>\n      <td id=\"T_e50ba_row1_col2\" class=\"data row1 col2\" >0.0040</td>\n      <td id=\"T_e50ba_row1_col3\" class=\"data row1 col3\" >15628</td>\n      <td id=\"T_e50ba_row1_col4\" class=\"data row1 col4\" >15628</td>\n      <td id=\"T_e50ba_row1_col5\" class=\"data row1 col5\" >1.0001</td>\n    </tr>\n    <tr>\n      <td id=\"T_e50ba_row2_col0\" class=\"data row2 col0\" >event[Generating class]</td>\n      <td id=\"T_e50ba_row2_col1\" class=\"data row2 col1\" >0.002</td>\n      <td id=\"T_e50ba_row2_col2\" class=\"data row2 col2\" >0.0002</td>\n      <td id=\"T_e50ba_row2_col3\" class=\"data row2 col3\" >45972</td>\n      <td id=\"T_e50ba_row2_col4\" class=\"data row2 col4\" >45972</td>\n      <td id=\"T_e50ba_row2_col5\" class=\"data row2 col5\" >1.0001</td>\n    </tr>\n    <tr>\n      <td id=\"T_e50ba_row3_col0\" class=\"data row3 col0\" >event[d has a path to y]</td>\n      <td id=\"T_e50ba_row3_col1\" class=\"data row3 col1\" >0.939</td>\n      <td id=\"T_e50ba_row3_col2\" class=\"data row3 col2\" >0.0012</td>\n      <td id=\"T_e50ba_row3_col3\" class=\"data row3 col3\" >41633</td>\n      <td id=\"T_e50ba_row3_col4\" class=\"data row3 col4\" >48000</td>\n      <td id=\"T_e50ba_row3_col5\" class=\"data row3 col5\" >1.0001</td>\n    </tr>\n    <tr>\n      <td id=\"T_e50ba_row4_col0\" class=\"data row4 col0\" >edge_count</td>\n      <td id=\"T_e50ba_row4_col1\" class=\"data row4 col1\" >12.228</td>\n      <td id=\"T_e50ba_row4_col2\" class=\"data row4 col2\" >0.0106</td>\n      <td id=\"T_e50ba_row4_col3\" class=\"data row4 col3\" >18754</td>\n      <td id=\"T_e50ba_row4_col4\" class=\"data row4 col4\" >22615</td>\n      <td id=\"T_e50ba_row4_col5\" class=\"data row4 col5\" >1.0001</td>\n    </tr>\n    <tr>\n      <td id=\"T_e50ba_row5_col0\" class=\"data row5 col0\" >log_evidence</td>\n      <td id=\"T_e50ba_row5_col1\" class=\"data row5 col1\" >467.972</td>\n      <td id=\"T_e50ba_row5_col2\" class=\"data row5 col2\" >0.0176</td>\n      <td id=\"T_e50ba_row5_col3\" class=\"data row5 col3\" >17917</td>\n      <td id=\"T_e50ba_row5_col4\" class=\"data row5 col4\" >23631</td>\n      <td id=\"T_e50ba_row5_col5\" class=\"data row5 col5\" >1.0001</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nA forbidden direction is constant **by assumption**, not evidence of perfect convergence. We report those separately from other constant indicators, which can reflect implied restrictions, rare events, or unvisited regions. We do not award any of them an infinite effective sample size. Small $\\widehat R$ values and Monte Carlo errors are useful checks, not proof that every important mode was visited. Divergences and BFMI are HMC diagnostics; they do not apply to this discrete Metropolis kernel.\n\n::: {#cell-fig-graph-diagnostics .cell execution_count=14}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(1, 3, figsize=(12, 3.5))\nfor chain in range(4):\n    axes[0].plot(posterior.posterior.log_evidence.values[chain, :2000], alpha=0.65, lw=0.7,\n                 color=PALETTE[chain], label=f\"Chain {chain + 1}\")\n    axes[1].plot(posterior.posterior.edge_count.values[chain, :2000], alpha=0.65, lw=0.7,\n                 color=PALETTE[chain])\naxes[0].set(title=\"Collapsed log evidence\", xlabel=\"Retained draw\")\naxes[1].set(title=\"Number of arrows\", xlabel=\"Retained draw\")\nfor index, (event, name) in enumerate([(summary[\"true_class\"], \"Generating class\"),\n                                     (summary[\"path\"], \"d has a path to y\")]):\n    axes[2].plot(np.arange(1, 5), event.mean(axis=1), \"o-\", label=name)\naxes[2].set(title=\"Chain agreement\", xlabel=\"Chain\", ylabel=\"Event probability\", xticks=range(1, 5), ylim=(0, 1))\naxes[2].legend(frameon=False, fontsize=8)\nplt.show()\n\nswap_names = [f\"swap_{i}\" for i in range(len(betas) - 1)]\nswap_rates = np.array([float(posterior.sample_stats[name].mean()) for name in swap_names])\nprint(f\"Accepted core changes per attempted update: {float(posterior.sample_stats.cold_accept.mean()):.3f}\")\nprint(f\"Cycle rejection fraction: {float(posterior.sample_stats.cold_invalid.mean()):.3f}\")\nprint(\"Adjacent temperature swap acceptance:\", np.round(swap_rates, 3))\nprint(\"Full cold–hot–cold round trips per chain:\",\n      posterior.sample_stats.roundtrips.sum(\"draw\").values)\n```\n\n::: {.cell-output .cell-output-display}\n![Cold-chain traces and per-chain event frequencies. Agreement matters for graph events, not just for the scalar score. The first two panels show the first 2,000 retained draws; each line is a chain.](bayesian_cpdag_graph_discovery_files/figure-html/fig-graph-diagnostics-output-1.png){#fig-graph-diagnostics width=1877 height=602 fig-alt='Four-chain traces for collapsed evidence and edge count, alongside per-chain generating-class and causal-path probabilities.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nAccepted core changes per attempted update: 0.205\nCycle rejection fraction: 0.089\nAdjacent temperature swap acceptance: [0.533 0.658 0.769 0.85  0.89  0.891 0.858 0.806 0.789 0.815 0.86  0.903\n 0.938 0.959 0.924]\nFull cold–hot–cold round trips per chain: [1773 1764 1735 1757]\n```\n:::\n:::\n\n\nWe inspect every adjacent swap rate because one weak link can isolate the hottest replicas. Swap acceptance is a transport diagnostic, not evidence that the posterior is correct. The temperatures are computational devices; the prior has not changed between replicas.\n\n::: {.callout-note collapse=\"true\"}\n## A finite-state correctness check, separate from discovery\n\nFour nodes are small enough to provide an oracle: 543 DAGs and 185 equivalence classes. We compare the compiled PyMC log density against the intended score for every state, verify that all cycles have zero support, check score equivalence, and check CPDAG orientations against the intersection of **all** members of each exact class.\n\nWe then run the actual compiled graph step and compare its four-node class frequencies with the exact posterior under asymmetric directional priors. Additional masked cases check the reconstructed **full joint DAG distribution**, not only the terminal-parent marginals: a terminal fourth node leaves 200 full DAGs, factored into 25 core DAGs and eight parent sets. The checks also cover required edges, impossible forced cycles, non-last and multiple terminals, fixed graphs, chain resets, tiny positive priors, and the two-state periodicity case. Total variation is half the sum of absolute probability errors. These checks exercise the implementation rather than merely re-evaluating the Metropolis identity; they do not establish mixing on every larger problem.\n\n::: {#a171e38c .cell execution_count=15}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Run the exhaustive four-node oracle and sample its posterior\"}\nchecks = check_small_graphs(make_graph_model)\ndisplay(article_table(pd.DataFrame.from_dict(checks, orient=\"index\", columns=[\"Result\"]).reset_index(names=\"Check\"),\n                      \"Independent finite-state checks\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 2_000 tune and 10_000 draw iterations (8_000 + 40_000 draws total) took 1 seconds.\nSequential sampling (2 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 2 chains for 1_000 tune and 5_000 draw iterations (2_000 + 10_000 draws total) took 0 seconds.\nSequential sampling (1 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 1 chain for 500 tune and 10_000 draw iterations (500 + 10_000 draws total) took 0 seconds.\nSequential sampling (1 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 1 chain for 0 tune and 2_000 draw iterations (0 + 2_000 draws total) took 0 seconds.\nSequential sampling (2 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 2 chains for 500 tune and 3_000 draw iterations (1_000 + 6_000 draws total) took 0 seconds.\nSequential sampling (2 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 2 chains for 500 tune and 3_000 draw iterations (1_000 + 6_000 draws total) took 0 seconds.\nSequential sampling (1 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 1 chain for 100 tune and 300 draw iterations (100 + 300 draws total) took 0 seconds.\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 1_000 tune and 5_000 draw iterations (4_000 + 20_000 draws total) took 1 seconds.\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_bdccc th {\n  text-align: left;\n}\n#T_bdccc td {\n  text-align: left;\n}\n#T_bdccc_row0_col0, #T_bdccc_row0_col1, #T_bdccc_row1_col0, #T_bdccc_row1_col1, #T_bdccc_row2_col0, #T_bdccc_row2_col1, #T_bdccc_row3_col0, #T_bdccc_row3_col1, #T_bdccc_row4_col0, #T_bdccc_row4_col1, #T_bdccc_row5_col0, #T_bdccc_row5_col1, #T_bdccc_row6_col0, #T_bdccc_row6_col1, #T_bdccc_row7_col0, #T_bdccc_row7_col1, #T_bdccc_row8_col0, #T_bdccc_row8_col1, #T_bdccc_row9_col0, #T_bdccc_row9_col1, #T_bdccc_row10_col0, #T_bdccc_row10_col1, #T_bdccc_row11_col0, #T_bdccc_row11_col1, #T_bdccc_row12_col0, #T_bdccc_row12_col1, #T_bdccc_row13_col0, #T_bdccc_row13_col1, #T_bdccc_row14_col0, #T_bdccc_row14_col1, #T_bdccc_row15_col0, #T_bdccc_row15_col1, #T_bdccc_row16_col0, #T_bdccc_row16_col1, #T_bdccc_row17_col0, #T_bdccc_row17_col1, #T_bdccc_row18_col0, #T_bdccc_row18_col1, #T_bdccc_row19_col0, #T_bdccc_row19_col1 {\n  text-align: left;\n}\n</style>\n<table id=\"T_bdccc\">\n  <caption>Independent finite-state checks</caption>\n  <thead>\n    <tr>\n      <th id=\"T_bdccc_level0_col0\" class=\"col_heading level0 col0\" >Check</th>\n      <th id=\"T_bdccc_level0_col1\" class=\"col_heading level0 col1\" >Result</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_bdccc_row0_col0\" class=\"data row0 col0\" >four_node_DAGs</td>\n      <td id=\"T_bdccc_row0_col1\" class=\"data row0 col1\" >543</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row1_col0\" class=\"data row1 col0\" >four_node_CPDAGs</td>\n      <td id=\"T_bdccc_row1_col1\" class=\"data row1 col1\" >185</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row2_col0\" class=\"data row2 col0\" >cyclic_states_rejected</td>\n      <td id=\"T_bdccc_row2_col1\" class=\"data row2 col1\" >186</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row3_col0\" class=\"data row3 col0\" >maximum_target_error</td>\n      <td id=\"T_bdccc_row3_col1\" class=\"data row3 col1\" >0.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row4_col0\" class=\"data row4 col0\" >maximum_score_equivalence_error</td>\n      <td id=\"T_bdccc_row4_col1\" class=\"data row4 col1\" >0.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row5_col0\" class=\"data row5 col0\" >sampled_class_total_variation</td>\n      <td id=\"T_bdccc_row5_col1\" class=\"data row5 col1\" >0.010474</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row6_col0\" class=\"data row6 col0\" >masked_core_full_joint_TV</td>\n      <td id=\"T_bdccc_row6_col1\" class=\"data row6 col1\" >0.004841</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row7_col0\" class=\"data row7 col0\" >subnormal_prior_max_probability_error</td>\n      <td id=\"T_bdccc_row7_col1\" class=\"data row7 col1\" >0.011300</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row8_col0\" class=\"data row8 col0\" >two_state_periodicity_max_probability_error</td>\n      <td id=\"T_bdccc_row8_col1\" class=\"data row8 col1\" >0.003000</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row9_col0\" class=\"data row9 col0\" >y_sink_valid_DAGs</td>\n      <td id=\"T_bdccc_row9_col1\" class=\"data row9 col1\" >200</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row10_col0\" class=\"data row10 col0\" >y_sink_terminal_parent_masks</td>\n      <td id=\"T_bdccc_row10_col1\" class=\"data row10 col1\" >8</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row11_col0\" class=\"data row11 col0\" >y_sink_full_joint_TV</td>\n      <td id=\"T_bdccc_row11_col1\" class=\"data row11 col1\" >0.011368</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row12_col0\" class=\"data row12 col0\" >y_sink_class_TV</td>\n      <td id=\"T_bdccc_row12_col1\" class=\"data row12 col1\" >0.004303</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row13_col0\" class=\"data row13 col0\" >non_last_terminal</td>\n      <td id=\"T_bdccc_row13_col1\" class=\"data row13 col1\" >0</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row14_col0\" class=\"data row14 col0\" >multiple_terminal_count</td>\n      <td id=\"T_bdccc_row14_col1\" class=\"data row14 col1\" >2</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row15_col0\" class=\"data row15 col0\" >non_last_full_joint_TV</td>\n      <td id=\"T_bdccc_row15_col1\" class=\"data row15 col1\" >0.019225</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row16_col0\" class=\"data row16 col0\" >multiple_terminal_full_joint_TV</td>\n      <td id=\"T_bdccc_row16_col1\" class=\"data row16 col1\" >0.017494</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row17_col0\" class=\"data row17 col0\" >fixed_graph_active_pairs</td>\n      <td id=\"T_bdccc_row17_col1\" class=\"data row17 col1\" >0</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row18_col0\" class=\"data row18 col0\" >forced_cycle_rejected</td>\n      <td id=\"T_bdccc_row18_col1\" class=\"data row18 col1\" >True</td>\n    </tr>\n    <tr>\n      <td id=\"T_bdccc_row19_col0\" class=\"data row19 col0\" >reset_trajectory_agreement</td>\n      <td id=\"T_bdccc_row19_col1\" class=\"data row19 col1\" >True</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n:::\n\n# How do DAG probabilities become CPDAG probabilities?\n\nA CPDAG represents a set $[G]$ of DAGs, so its posterior probability is a **sum**, not the score of a chosen representative:\n\n$$\np(C\\mid D)=\\sum_{G\\in C}p(G\\mid D).\n$$\n\nFor MCMC, we estimate this sum by the fraction of retained cold-chain draws whose skeleton and colliders identify class $C$. We keep repeats and divide by the total number of retained draws. We do not renormalize over the classes displayed below.\n\nHere the graph prior already includes the mask. Members excluded by background knowledge contribute zero mass. We still draw the **ordinary observational CPDAG** of each class: an undirected line can describe a direction that the mask forbids in individual draws. It does not reinstate that direction. A knowledge-oriented, maximally oriented PDAG would be a different summary.\n\n::: {#fig-leading-cpdags .cell execution_count=16}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(2, 2, figsize=(10, 8))\nfor index, ax in enumerate(axes.flat):\n    if index >= len(summary[\"ranked\"]):\n        ax.axis(\"off\")\n        continue\n    key = summary[\"ranked\"][index]\n    mass = summary[\"class_counts\"][key] / summary[\"states\"][..., 0].size\n    suffix = \" · generating class\" if key == truth_key else \"\"\n    draw_graph(ax, cpdag(summary[\"representative\"][key]), f\"Class {index + 1}: {mass:.1%}{suffix}\")\nplt.show()\ndisplay(Markdown(\n    f\"The generating class receives **{summary['true_class'].mean():.2%}** of the sampled mass; \"\n    f\"the four leading classes together receive **{np.mean(summary['class_id'] < 4):.1%}**. \"\n    f\"The posterior mean is **{float(posterior.posterior.edge_count.mean()):.1f} arrows**, \"\n    \"compared with eight in the generating graph. This is **not a successful-recovery demonstration**. \"\n    \"The posterior is diffuse and favors denser alternatives under these priors.\"\n))\nprint(f\"Distinct DAGs visited: {len(summary['graphs'])}; classes visited: {len(summary['ranked'])}\")\nprint(f\"Mass outside the four panels: \"\n      f\"{np.mean(summary['class_id'] >= 4):.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![The four most frequently visited observational CPDAGs, weighted by eligible full DAG draws. Undirected dashed edges describe observational reversibility, not uncertain edge existence or permission to violate the hard mask.](bayesian_cpdag_graph_discovery_files/figure-html/fig-leading-cpdags-output-1.png){#fig-leading-cpdags-1 width=1491 height=1277 fig-alt='Four seven-node CPDAGs ranked by estimated posterior mass, with each panel labeling its probability and whether it is the generating class.'}\n:::\n\n::: {#fig-leading-cpdags-2 .cell-output .cell-output-display .cell-output-markdown}\nThe generating class receives **0.15%** of the sampled mass; the four leading classes together receive **3.6%**. The posterior mean is **12.2 arrows**, compared with eight in the generating graph. This is **not a successful-recovery demonstration**. The posterior is diffuse and favors denser alternatives under these priors.\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nDistinct DAGs visited: 22874; classes visited: 14403\nMass outside the four panels: 0.964\n```\n:::\n:::\n\n\nThe most probable individual DAG need not belong to the most probable class. A class may gather substantial mass across several members. Neither a single selected DAG nor a list of the leading classes is the full posterior.\n\n::: {#cell-fig-edge-probabilities .cell execution_count=17}\n``` {.python .cell-code code-fold=\"true\"}\nstates = summary[\"states\"]\nforward = (states == 1).mean(axis=(0, 1))\nbackward = (states == 2).mean(axis=(0, 1))\nfig, ax = plt.subplots(figsize=(8, 7))\npositions = np.arange(len(pairs))\nax.barh(positions, forward, color=COLORS[\"primary\"], label=r\"First $\\rightarrow$ second\")\nax.barh(positions, backward, left=forward, color=COLORS[\"accent\"], label=r\"Second $\\rightarrow$ first\")\nax.set(yticks=positions, yticklabels=[f\"{labels[i]} – {labels[j]}\" for i, j in pairs],\n       xlim=(0, 1), xlabel=\"Posterior probability\", title=\"Connections and their directions\")\nax.invert_yaxis()\nax.legend(frameon=False)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Posterior direction probabilities for every unordered pair. Each bar's remainder is the probability of no edge. These marginal probabilities are not themselves a DAG or CPDAG.](bayesian_cpdag_graph_discovery_files/figure-html/fig-edge-probabilities-output-1.png){#fig-edge-probabilities width=1277 height=1127 fig-alt='Stacked probabilities for the two possible orientations of all 21 node pairs, showing edge and direction uncertainty separately.'}\n:::\n:::\n\n\nThresholding these probabilities independently can create cycles or a graph that received little joint support. We use them to answer pairwise questions, not to manufacture a consensus causal model.\n\n# An informative prior can change the unresolved direction\n\nSuppose knowledge collected **before this dataset** favors $d\\rightarrow f$ over $f\\rightarrow d$ by 9:1, conditional on an edge. For example, $d$ might be a baseline measurement and $f$ a later exposure. We edit two cells of the directional-prior matrix, preserving this pair's absence probability. This is a soft preference: it excludes no additional DAGs beyond the same terminal-$y$ mask.\n\n::: {#7fc104d7 .cell execution_count=18}\n``` {.python .cell-code}\ndf_pair = next(k for k, pair in enumerate(pairs) if tuple(pair) == (3, 5))\ninformed_prior = direction_prior.copy()\ninformed_prior.loc[\"d\", \"f\"] = 0.9 * (2 / 3)\ninformed_prior.loc[\"f\", \"d\"] = 0.1 * (2 / 3)\ninformed_probs = pair_probabilities(informed_prior.to_numpy(), allowed.to_numpy())\ninformed = fit_graphs(\n    score, informed_probs, labels,\n    seed=SEED + 20, draws=draws, tune=tune, betas=betas,\n)\ninformed_summary = graph_summary(informed)\ninformed_diagnostics = azs.summary(\n    graph_diagnostic_data(informed, informed_summary, informed_probs),\n    ci_prob=0.95, round_to=\"none\",\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 3_000 tune and 12_000 draw iterations (12_000 + 48_000 draws total) took 3 seconds.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nIndicators fixed by pair support: 6\nOther constant indicators: 13 (diagnostics not estimable)\n```\n:::\n:::\n\n\nWithin the generating equivalence class, the likelihood is exactly equal for its two DAGs. Therefore their posterior odds equal their prior odds: 1:1 under the baseline, 9:1 under the informative prior. The directional probability below is **conditional on the sampled DAG belonging to this class**; its unconditional counterpart also depends on other classes.\n\n::: {#c527ffae .cell execution_count=19}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Separate a prior-driven orientation from class recovery\"}\norientation_rows = []\nfor name, current, exact in [(\"Symmetric directions\", summary, 0.5),\n                              (\"9:1 for d → f\", informed_summary, 0.9)]:\n    selected = current[\"true_class\"]\n    forward_in_class = selected & (current[\"states\"][..., df_pair] == 1)\n    conditional = forward_in_class.sum() / selected.sum() if selected.any() else np.nan\n    mcse = np.nan\n    if selected.any():\n        influence = forward_in_class.astype(float) - conditional * selected\n        ratio_tree = azb.from_dict({\"posterior\": {\"influence\": influence}})\n        mcse = azs.summary(ratio_tree, round_to=\"none\").loc[\"influence\", \"mcse_mean\"] / selected.mean()\n    orientation_rows.append({\"Prior\": name, \"Class draws\": int(selected.sum()),\n                             \"P(d → f | class)\": conditional, \"MCSE\": mcse,\n                             \"Exact within class\": exact})\ndisplay(article_table(pd.DataFrame(orientation_rows),\n                      \"Separate the exact class-conditional target from its MCMC estimate\",\n                      formats={\"P(d → f | class)\": \"{:.3f}\", \"MCSE\": \"{:.3f}\",\n                               \"Exact within class\": \"{:.1f}\"}))\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_46613 th {\n  text-align: left;\n}\n#T_46613 td {\n  text-align: left;\n}\n#T_46613_row0_col0, #T_46613_row0_col1, #T_46613_row0_col2, #T_46613_row0_col3, #T_46613_row0_col4, #T_46613_row1_col0, #T_46613_row1_col1, #T_46613_row1_col2, #T_46613_row1_col3, #T_46613_row1_col4 {\n  text-align: left;\n}\n</style>\n<table id=\"T_46613\">\n  <caption>Separate the exact class-conditional target from its MCMC estimate</caption>\n  <thead>\n    <tr>\n      <th id=\"T_46613_level0_col0\" class=\"col_heading level0 col0\" >Prior</th>\n      <th id=\"T_46613_level0_col1\" class=\"col_heading level0 col1\" >Class draws</th>\n      <th id=\"T_46613_level0_col2\" class=\"col_heading level0 col2\" >P(d → f | class)</th>\n      <th id=\"T_46613_level0_col3\" class=\"col_heading level0 col3\" >MCSE</th>\n      <th id=\"T_46613_level0_col4\" class=\"col_heading level0 col4\" >Exact within class</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_46613_row0_col0\" class=\"data row0 col0\" >Symmetric directions</td>\n      <td id=\"T_46613_row0_col1\" class=\"data row0 col1\" >74</td>\n      <td id=\"T_46613_row0_col2\" class=\"data row0 col2\" >0.446</td>\n      <td id=\"T_46613_row0_col3\" class=\"data row0 col3\" >0.060</td>\n      <td id=\"T_46613_row0_col4\" class=\"data row0 col4\" >0.5</td>\n    </tr>\n    <tr>\n      <td id=\"T_46613_row1_col0\" class=\"data row1 col0\" >9:1 for d → f</td>\n      <td id=\"T_46613_row1_col1\" class=\"data row1 col1\" >94</td>\n      <td id=\"T_46613_row1_col2\" class=\"data row1 col2\" >0.926</td>\n      <td id=\"T_46613_row1_col3\" class=\"data row1 col3\" >0.027</td>\n      <td id=\"T_46613_row1_col4\" class=\"data row1 col4\" >0.9</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nThe relevant sample size is the number of generating-class draws, not the length of the whole chain. We report that count, the exact class-conditional target, and a ratio-estimator MCSE computed from the full chains. The Monte Carlo estimate need not equal 0.5 or 0.9 exactly; a small unconditional event MCSE does not guarantee a precise estimate within a rare class.\n\nThis does not mean that the observations discovered the direction. We supplied information that observational equivalence cannot provide. The observational CPDAG structure remains unchanged; we retain the member-level posterior weights alongside it.\n\n## What about sparsity and parameter scales?\n\nWe also set both directional entries to 0.15, giving the sparse pair prior $(0.7,0.15,0.15)$ before restrictions, and separately double the parameter scales. Every fit uses the same hard mask. The first change affects $\\pi(G)$; the second changes the BGe evidence itself. These are sensitivity analyses of different assumptions, not one fit per candidate graph.\n\n::: {#b0bf6ab2 .cell execution_count=20}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Refit graph-prior and parameter-prior sensitivities\"}\nsparse_prior = pd.DataFrame(\n    (1 - np.eye(n_nodes)) * 0.15, index=labels, columns=labels,\n)\nsparse_probs = pair_probabilities(sparse_prior.to_numpy(), allowed.to_numpy())\nsparse = fit_graphs(\n    score, sparse_probs, labels,\n    seed=SEED + 30, draws=draws, tune=tune, betas=betas,\n)\nwide_score = BGeScore(data, prior_sd=2 * prior_sd, alpha_mu=1.0, alpha_w=n_nodes + 4)\nwide = fit_graphs(\n    wide_score, baseline_probs, labels,\n    seed=SEED + 40, draws=draws, tune=tune, betas=betas,\n)\nsensitivity_rows = []\nfor name, trace, current, probabilities in [\n    (\"Baseline\", posterior, summary, baseline_probs),\n    (\"Directional knowledge\", informed, informed_summary, informed_probs),\n    (\"Sparse graph prior\", sparse, graph_summary(sparse), sparse_probs),\n    (\"Twice the parameter scales\", wide, graph_summary(wide), baseline_probs),\n]:\n    diagnostic = azs.summary(\n        graph_diagnostic_data(trace, current, probabilities),\n        ci_prob=0.95, round_to=\"none\",\n    )\n    sensitivity_rows.append({\"Specification\": name,\n                             \"P(generating class)\": current[\"true_class\"].mean(),\n                             \"P(d has a path to y)\": current[\"path\"].mean(),\n                             \"Mean arrows\": float(trace.posterior.edge_count.mean()),\n                             \"Max R-hat\": diagnostic.r_hat.max(),\n                             \"Min bulk ESS\": diagnostic.ess_bulk.min()})\ndisplay(article_table(pd.DataFrame(sensitivity_rows),\n                      \"Prior sensitivity with separate graph chains\",\n                      formats={\"P(generating class)\": \"{:.3f}\", \"P(d has a path to y)\": \"{:.3f}\",\n                               \"Mean arrows\": \"{:.2f}\", \"Max R-hat\": \"{:.4f}\", \"Min bulk ESS\": \"{:.0f}\"}))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 3_000 tune and 12_000 draw iterations (12_000 + 48_000 draws total) took 3 seconds.\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 3_000 tune and 12_000 draw iterations (12_000 + 48_000 draws total) took 3 seconds.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nIndicators fixed by pair support: 6\nOther constant indicators: 13 (diagnostics not estimable)\nIndicators fixed by pair support: 6\nOther constant indicators: 13 (diagnostics not estimable)\nIndicators fixed by pair support: 6\nOther constant indicators: 13 (diagnostics not estimable)\nIndicators fixed by pair support: 6\nOther constant indicators: 14 (diagnostics not estimable)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_39283 th {\n  text-align: left;\n}\n#T_39283 td {\n  text-align: left;\n}\n#T_39283_row0_col0, #T_39283_row0_col1, #T_39283_row0_col2, #T_39283_row0_col3, #T_39283_row0_col4, #T_39283_row0_col5, #T_39283_row1_col0, #T_39283_row1_col1, #T_39283_row1_col2, #T_39283_row1_col3, #T_39283_row1_col4, #T_39283_row1_col5, #T_39283_row2_col0, #T_39283_row2_col1, #T_39283_row2_col2, #T_39283_row2_col3, #T_39283_row2_col4, #T_39283_row2_col5, #T_39283_row3_col0, #T_39283_row3_col1, #T_39283_row3_col2, #T_39283_row3_col3, #T_39283_row3_col4, #T_39283_row3_col5 {\n  text-align: left;\n}\n</style>\n<table id=\"T_39283\">\n  <caption>Prior sensitivity with separate graph chains</caption>\n  <thead>\n    <tr>\n      <th id=\"T_39283_level0_col0\" class=\"col_heading level0 col0\" >Specification</th>\n      <th id=\"T_39283_level0_col1\" class=\"col_heading level0 col1\" >P(generating class)</th>\n      <th id=\"T_39283_level0_col2\" class=\"col_heading level0 col2\" >P(d has a path to y)</th>\n      <th id=\"T_39283_level0_col3\" class=\"col_heading level0 col3\" >Mean arrows</th>\n      <th id=\"T_39283_level0_col4\" class=\"col_heading level0 col4\" >Max R-hat</th>\n      <th id=\"T_39283_level0_col5\" class=\"col_heading level0 col5\" >Min bulk ESS</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_39283_row0_col0\" class=\"data row0 col0\" >Baseline</td>\n      <td id=\"T_39283_row0_col1\" class=\"data row0 col1\" >0.002</td>\n      <td id=\"T_39283_row0_col2\" class=\"data row0 col2\" >0.939</td>\n      <td id=\"T_39283_row0_col3\" class=\"data row0 col3\" >12.23</td>\n      <td id=\"T_39283_row0_col4\" class=\"data row0 col4\" >1.0002</td>\n      <td id=\"T_39283_row0_col5\" class=\"data row0 col5\" >11345</td>\n    </tr>\n    <tr>\n      <td id=\"T_39283_row1_col0\" class=\"data row1 col0\" >Directional knowledge</td>\n      <td id=\"T_39283_row1_col1\" class=\"data row1 col1\" >0.002</td>\n      <td id=\"T_39283_row1_col2\" class=\"data row1 col2\" >0.987</td>\n      <td id=\"T_39283_row1_col3\" class=\"data row1 col3\" >12.19</td>\n      <td id=\"T_39283_row1_col4\" class=\"data row1 col4\" >1.0005</td>\n      <td id=\"T_39283_row1_col5\" class=\"data row1 col5\" >12265</td>\n    </tr>\n    <tr>\n      <td id=\"T_39283_row2_col0\" class=\"data row2 col0\" >Sparse graph prior</td>\n      <td id=\"T_39283_row2_col1\" class=\"data row2 col1\" >0.138</td>\n      <td id=\"T_39283_row2_col2\" class=\"data row2 col2\" >0.791</td>\n      <td id=\"T_39283_row2_col3\" class=\"data row2 col3\" >9.64</td>\n      <td id=\"T_39283_row2_col4\" class=\"data row2 col4\" >1.0002</td>\n      <td id=\"T_39283_row2_col5\" class=\"data row2 col5\" >15632</td>\n    </tr>\n    <tr>\n      <td id=\"T_39283_row3_col0\" class=\"data row3 col0\" >Twice the parameter scales</td>\n      <td id=\"T_39283_row3_col1\" class=\"data row3 col1\" >0.000</td>\n      <td id=\"T_39283_row3_col2\" class=\"data row3 col2\" >0.993</td>\n      <td id=\"T_39283_row3_col3\" class=\"data row3 col3\" >15.15</td>\n      <td id=\"T_39283_row3_col4\" class=\"data row3 col4\" >1.0003</td>\n      <td id=\"T_39283_row3_col5\" class=\"data row3 col5\" >20857</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nThe sparse prior's 0.3 edge probability is defined **before conditioning on the mask and acyclicity**. For a pair involving terminal $y$, masking the outgoing direction leaves an incoming-edge probability of $0.15/(0.7+0.15)$ before fitting. These local specifications are not generally the marginal probabilities of the legal-DAG prior. Uniform DAG mass is also not uniform CPDAG mass; a uniform-class prior would need an explicit class-size correction.\n\nThe sensitivity table shows that good mixing is not the same as recovering the generating structure. The sparse graph prior moves mass toward that class, while wider parameter scales favor still denser alternatives here. A reported zero means no retained draw visited the class, not that its posterior probability is mathematically zero.\n\n# A narrower answer can still be prior-sensitive\n\nWhat did the reduced exploration actually learn about $y$? Its exact parent-set posterior lets us answer without Monte Carlo error, then check that the reconstructed graph draws reproduce the same probabilities. This is only the terminal mechanism; the other six-node structure still comes from MCMC.\n\n::: {#c6e070d1 .cell execution_count=21}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Compare exact terminal-parent probabilities with full graph draws\"}\ny_index = labels.index(\"y\")\ny_pairs = np.flatnonzero((pairs[:, 0] == y_index) | (pairs[:, 1] == y_index))\nincoming_states = np.where(pairs[y_pairs, 1] == y_index, 1, 2)\nparent_indices = np.where(pairs[y_pairs, 1] == y_index, pairs[y_pairs, 0], pairs[y_pairs, 1])\nparent_rows, concentration_rows = [], []\ny_distributions = {}\nfor name, trace, probabilities in [\n    (\"Baseline\", posterior, baseline_probs),\n    (\"Sparse prior\", sparse, sparse_probs),\n]:\n    masks, weights = terminal_parent_distributions(score.table, pairs, probabilities)[y_index]\n    y_distributions[name] = (masks, weights)\n    sampled_masks = (\n        (trace.posterior.edge.values[..., y_pairs] == incoming_states)\n        * (1 << parent_indices)\n    ).sum(axis=-1)\n    ranked = np.argsort(weights)[::-1]\n    count = int(np.searchsorted(np.cumsum(weights[ranked]), 0.95) + 1)\n    selected = ranked[:count]\n    concentration_rows.append({\n        \"Prior\": name, \"Admissible parent sets\": len(masks),\n        \"Sets reaching 95% mass\": count, \"Mass covered\": weights[selected].sum(),\n    })\n    for index in selected:\n        parents = \", \".join(labels[node] for node in range(n_nodes) if masks[index] & (1 << node))\n        parent_rows.append({\n            \"Prior\": name, \"Parents of y\": parents or \"None\",\n            \"Exact probability\": weights[index],\n            \"MCMC frequency\": np.mean(sampled_masks == masks[index]),\n        })\n    other = ~np.isin(masks, masks[selected])\n    parent_rows.append({\n        \"Prior\": name, \"Parents of y\": \"Other parent sets\",\n        \"Exact probability\": weights[other].sum(),\n        \"MCMC frequency\": np.mean(~np.isin(sampled_masks, masks[selected])),\n    })\ndisplay(article_table(\n    pd.DataFrame(concentration_rows), \"How far the data narrow y's possible parent sets\",\n    formats={\"Mass covered\": \"{:.5%}\"},\n))\ndisplay(article_table(\n    pd.DataFrame(parent_rows), \"Exact parent-set weights and frequencies in reconstructed full DAGs\",\n    formats={\"Exact probability\": \"{:.2%}\", \"MCMC frequency\": \"{:.2%}\"},\n))\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_73fed th {\n  text-align: left;\n}\n#T_73fed td {\n  text-align: left;\n}\n#T_73fed_row0_col0, #T_73fed_row0_col1, #T_73fed_row0_col2, #T_73fed_row0_col3, #T_73fed_row1_col0, #T_73fed_row1_col1, #T_73fed_row1_col2, #T_73fed_row1_col3 {\n  text-align: left;\n}\n</style>\n<table id=\"T_73fed\">\n  <caption>How far the data narrow y's possible parent sets</caption>\n  <thead>\n    <tr>\n      <th id=\"T_73fed_level0_col0\" class=\"col_heading level0 col0\" >Prior</th>\n      <th id=\"T_73fed_level0_col1\" class=\"col_heading level0 col1\" >Admissible parent sets</th>\n      <th id=\"T_73fed_level0_col2\" class=\"col_heading level0 col2\" >Sets reaching 95% mass</th>\n      <th id=\"T_73fed_level0_col3\" class=\"col_heading level0 col3\" >Mass covered</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_73fed_row0_col0\" class=\"data row0 col0\" >Baseline</td>\n      <td id=\"T_73fed_row0_col1\" class=\"data row0 col1\" >64</td>\n      <td id=\"T_73fed_row0_col2\" class=\"data row0 col2\" >2</td>\n      <td id=\"T_73fed_row0_col3\" class=\"data row0 col3\" >100.00000%</td>\n    </tr>\n    <tr>\n      <td id=\"T_73fed_row1_col0\" class=\"data row1 col0\" >Sparse prior</td>\n      <td id=\"T_73fed_row1_col1\" class=\"data row1 col1\" >64</td>\n      <td id=\"T_73fed_row1_col2\" class=\"data row1 col2\" >2</td>\n      <td id=\"T_73fed_row1_col3\" class=\"data row1 col3\" >99.99998%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n#T_48dcc th {\n  text-align: left;\n}\n#T_48dcc td {\n  text-align: left;\n}\n#T_48dcc_row0_col0, #T_48dcc_row0_col1, #T_48dcc_row0_col2, #T_48dcc_row0_col3, #T_48dcc_row1_col0, #T_48dcc_row1_col1, #T_48dcc_row1_col2, #T_48dcc_row1_col3, #T_48dcc_row2_col0, #T_48dcc_row2_col1, #T_48dcc_row2_col2, #T_48dcc_row2_col3, #T_48dcc_row3_col0, #T_48dcc_row3_col1, #T_48dcc_row3_col2, #T_48dcc_row3_col3, #T_48dcc_row4_col0, #T_48dcc_row4_col1, #T_48dcc_row4_col2, #T_48dcc_row4_col3, #T_48dcc_row5_col0, #T_48dcc_row5_col1, #T_48dcc_row5_col2, #T_48dcc_row5_col3 {\n  text-align: left;\n}\n</style>\n<table id=\"T_48dcc\">\n  <caption>Exact parent-set weights and frequencies in reconstructed full DAGs</caption>\n  <thead>\n    <tr>\n      <th id=\"T_48dcc_level0_col0\" class=\"col_heading level0 col0\" >Prior</th>\n      <th id=\"T_48dcc_level0_col1\" class=\"col_heading level0 col1\" >Parents of y</th>\n      <th id=\"T_48dcc_level0_col2\" class=\"col_heading level0 col2\" >Exact probability</th>\n      <th id=\"T_48dcc_level0_col3\" class=\"col_heading level0 col3\" >MCMC frequency</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_48dcc_row0_col0\" class=\"data row0 col0\" >Baseline</td>\n      <td id=\"T_48dcc_row0_col1\" class=\"data row0 col1\" >a, b, c, d, e, f</td>\n      <td id=\"T_48dcc_row0_col2\" class=\"data row0 col2\" >84.66%</td>\n      <td id=\"T_48dcc_row0_col3\" class=\"data row0 col3\" >84.65%</td>\n    </tr>\n    <tr>\n      <td id=\"T_48dcc_row1_col0\" class=\"data row1 col0\" >Baseline</td>\n      <td id=\"T_48dcc_row1_col1\" class=\"data row1 col1\" >a, b, c, e, f</td>\n      <td id=\"T_48dcc_row1_col2\" class=\"data row1 col2\" >15.34%</td>\n      <td id=\"T_48dcc_row1_col3\" class=\"data row1 col3\" >15.35%</td>\n    </tr>\n    <tr>\n      <td id=\"T_48dcc_row2_col0\" class=\"data row2 col0\" >Baseline</td>\n      <td id=\"T_48dcc_row2_col1\" class=\"data row2 col1\" >Other parent sets</td>\n      <td id=\"T_48dcc_row2_col2\" class=\"data row2 col2\" >0.00%</td>\n      <td id=\"T_48dcc_row2_col3\" class=\"data row2 col3\" >0.00%</td>\n    </tr>\n    <tr>\n      <td id=\"T_48dcc_row3_col0\" class=\"data row3 col0\" >Sparse prior</td>\n      <td id=\"T_48dcc_row3_col1\" class=\"data row3 col1\" >a, b, c, d, e, f</td>\n      <td id=\"T_48dcc_row3_col2\" class=\"data row3 col2\" >54.19%</td>\n      <td id=\"T_48dcc_row3_col3\" class=\"data row3 col3\" >54.42%</td>\n    </tr>\n    <tr>\n      <td id=\"T_48dcc_row4_col0\" class=\"data row4 col0\" >Sparse prior</td>\n      <td id=\"T_48dcc_row4_col1\" class=\"data row4 col1\" >a, b, c, e, f</td>\n      <td id=\"T_48dcc_row4_col2\" class=\"data row4 col2\" >45.81%</td>\n      <td id=\"T_48dcc_row4_col3\" class=\"data row4 col3\" >45.58%</td>\n    </tr>\n    <tr>\n      <td id=\"T_48dcc_row5_col0\" class=\"data row5 col0\" >Sparse prior</td>\n      <td id=\"T_48dcc_row5_col1\" class=\"data row5 col1\" >Other parent sets</td>\n      <td id=\"T_48dcc_row5_col2\" class=\"data row5 col2\" >0.00%</td>\n      <td id=\"T_48dcc_row5_col3\" class=\"data row5 col3\" >0.00%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n::: {#cell-fig-terminal-parent-learning .cell execution_count=22}\n``` {.python .cell-code code-fold=\"true\"}\nprior_masks, prior_weights = terminal_parent_distributions(\n    np.zeros_like(score.table), pairs, baseline_probs,\n)[y_index]\nfig, ax = plt.subplots(figsize=(8, 4.5))\npositions = np.arange(len(parent_indices))\ndistributions = [\n    (\"Baseline prior\", prior_masks, prior_weights, COLORS[\"accent\"]),\n    (\"Baseline posterior\", *y_distributions[\"Baseline\"], COLORS[\"primary\"]),\n    (\"Sparse posterior\", *y_distributions[\"Sparse prior\"], COLORS[\"green_strong\"]),\n]\nfor index, (name, masks, weights, color) in enumerate(distributions):\n    inclusion = [weights[(masks & (1 << node)) != 0].sum() for node in parent_indices]\n    ax.bar(positions + (index - 1) * 0.25, inclusion, width=0.25, label=name, color=color)\nax.set(xticks=positions, xticklabels=[labels[node] for node in parent_indices],\n       ylim=(0, 1.22), yticks=np.linspace(0, 1, 6),\n       xlabel=\"Candidate parent of y\", ylabel=\"Arrow inclusion probability\",\n       title=\"A terminal outcome still has uncertain parents\")\nax.legend(loc=\"upper center\", ncol=3, frameon=False, fontsize=9)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Conditioning on y being terminal leaves its parents unknown. Five incoming arrows receive strong support under both graph priors; the extra d→y arrow remains prior-sensitive. Exact terminal probabilities are not MCMC estimates.](bayesian_cpdag_graph_discovery_files/figure-html/fig-terminal-parent-learning-output-1.png){#fig-terminal-parent-learning width=1277 height=752 fig-alt='Grouped bars compare prior and posterior inclusion probabilities for each candidate parent of y, with the disputed direct arrow from d highlighted by its prior sensitivity.'}\n:::\n:::\n\n\nThe generating graph has no direct $d\\rightarrow y$ arrow. The baseline nevertheless favors adding it, and the sparse prior weakens that preference. This is concentration on a partly wrong structure, not a successful-recovery certificate. The table gives a focused set of alternatives while preserving this uncertainty; small residual masses may round to zero without being hard exclusions.\n\nNo incoming arrow into $y$ was fixed by the mask. Conversely, the six outgoing arrows are zero by assumption, not because MCMC learned that they were impossible. Reducing computation and adding scientific information are different operations, and both should be visible in the report.\n\n\n# What does this uncertainty mean for an intervention?\n\nOur question is now concrete: how does the mean of $y$ change when we intervene to increase $d$ by one unit?\n\n$$\n\\tau_{d\\to y}=\\frac{\\partial}{\\partial t}\\mathbb E[y\\mid\\operatorname{do}(d=t)].\n$$\n\nIn a linear DAG, this total effect is the sum of products along every directed path from $d$ to $y$. Under the generating graph there is one path, $d\\rightarrow f\\rightarrow y$, and its true effect is 0.72. Under the observational twin, $d$ has no path to $y$, so the effect is exactly zero. A CPDAG alone cannot choose between those answers.\n\nWe draw a DAG from the sampled graph posterior, then draw all of its mechanisms from $p(\\theta_G\\mid D,G)$. Those parameter draws use the **same** normal-Wishart hyperparameters that produced its BGe score. This is composition sampling from the joint posterior, not a second regression with unrelated priors.\n\n::: {#761c2e25 .cell execution_count=23}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Draw joint mechanisms and propagate intervention effects\"}\ndef effect_draws(trace, current_score, size=8_000):\n    retained = trace.posterior.edge.values.reshape(-1, len(pairs))\n    selected = rng_effect.integers(len(retained), size=size)\n    effects = np.empty(size)\n    for draw, index in enumerate(selected):\n        graph = states_to_parents(retained[index], pairs, n_nodes)\n        intercept, coefficients, variance = draw_parameters(current_score, graph, rng_effect)\n        effects[draw] = total_effects(graph, coefficients)[6, 3]\n    return effects\n\n\neffects = effect_draws(posterior, score)\ninformed_effects = effect_draws(informed, score)\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Recovering the mechanisms after collapsing them\n\nFor node $j$ with parents $P$, define\n\n$$\nb_j=R_{PP}^{-1}R_{Pj},\\qquad\ns_j=R_{jj}-R_{jP}R_{PP}^{-1}R_{Pj},\\qquad\n\\kappa=N+\\alpha_\\mu.\n$$\n\nThen draw\n\n$$\n\\sigma_j^2=\\frac{s_j}{\\chi^2_{N+\\alpha_W-p+|P|+1}},\\qquad\n\\beta_j\\mid\\sigma_j^2,D,G\\sim\\mathcal N(b_j,\\sigma_j^2R_{PP}^{-1}).\n$$\n\nWith $m=(N\\bar x+\\alpha_\\mu\\nu)/\\kappa$, the intercept conditional on these draws is\n$\\alpha_j\\sim\\mathcal N(m_j-\\beta_j^\\top m_P,\\sigma_j^2/\\kappa)$.\nThe empty-parent case has no coefficient draw. Setting $N=0$, $R=T$, and $m=\\nu$ recovers the prior used below. The implementation uses Cholesky solves rather than explicit inverses.\n\nOne coefficient realization is used for every path in an effect draw. Drawing paths independently would break their shared-parameter dependence. Graphs with no causal path contribute an exact zero; we do not replace that atom with a narrow Gaussian.\n:::\n\n::: {#cell-fig-model-averaged-effect .cell execution_count=24}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\nfor index, (name, samples, color) in enumerate([\n    (\"Baseline\", effects, COLORS[\"green_strong\"]),\n    (\"Directional prior\", informed_effects, COLORS[\"brown\"]),\n]):\n    zero_mass = np.mean(samples == 0)\n    axes[0].bar(index, zero_mass, color=color)\n    axes[0].text(index, zero_mass + 0.02, f\"{zero_mass:.1%}\", ha=\"center\")\n    nonzero = samples[samples != 0]\n    grid = np.linspace(nonzero.min() - 0.1, nonzero.max() + 0.1, 400)\n    axes[1].plot(grid, gaussian_kde(nonzero)(grid), color=color, lw=2, label=name)\n    print(f\"{name}: mean effect {samples.mean():.3f}; P(exact zero) {zero_mass:.3f}; \"\n          f\"nonzero 95% interval {np.quantile(nonzero, [0.025, 0.975]).round(3)}\")\naxes[0].set(xticks=[0, 1], xticklabels=[\"Baseline\", \"Directional prior\"], ylim=(0, 1),\n            ylabel=\"Posterior probability\", title=\"No causal path: exact zero\")\naxes[1].axvline(0.72, color=COLORS[\"ink_muted\"], linestyle=\"--\", label=\"Generating effect\")\naxes[1].set(xlabel=\"Effect of do(d + 1) on mean y\", ylabel=\"Conditional density\",\n            title=\"Effect given a nonzero path\")\naxes[1].legend(frameon=False, fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBaseline: mean effect 0.483; P(exact zero) 0.063; nonzero 95% interval [0.044 1.018]\nDirectional prior: mean effect 0.782; P(exact zero) 0.013; nonzero 95% interval [0.129 1.069]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![The graph-averaged intervention posterior has a point mass at zero and a continuous component. The informative d→f prior changes their weights. The density panel is conditional on a nonzero effect; its area is one, not the nonzero mixture mass.](bayesian_cpdag_graph_discovery_files/figure-html/fig-model-averaged-effect-output-2.png){#fig-model-averaged-effect width=1577 height=677 fig-alt='A bar chart compares exact-zero probabilities under two graph priors; a second panel shows their conditional nonzero effect densities with the generating effect 0.72 marked.'}\n:::\n:::\n\n\nA posterior mean can fall between “no effect” and a positive-effect component without describing either causal story well. We report the zero mass separately. More observations from the same observational distribution cannot resolve the $d$–$f$ ambiguity within this class; intervention data or defensible background knowledge can.\n\nThe full posterior's zero mass need not equal the 50% split within the generating class. Other classes can add a direct $d\\rightarrow y$ arrow or other directed paths. Fresh coefficient draws preserve that graph uncertainty; resampling stored DAGs does not increase the graph chain's effective sample size.\n\n# Do the prior and posterior predict plausible data?\n\nWe should check the parameter prior in data space, not only inspect its hyperparameters. For each replicate, we draw one legal graph and one complete set of mechanisms, then generate 300 observations in topological order. The graph is shared across all rows.\n\nThe acyclicity constraint is a `Potential`. PyMC's ordinary forward prior-predictive sampling does **not** condition on potentials, so raw categorical draws could contain cycles among the core variables. We instead use the same hard mask and reduced graph kernel with zero data: MCMC explores the legal core prior, exact terminal-parent draws reconstruct full graphs, and conditional mechanism draws generate datasets. These are not independent prior draws of the entire graph.\n\n::: {#89b0ee1b .cell execution_count=25}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Sample the legal graph prior and generate complete datasets\"}\nprior_score = BGeScore(np.empty((0, n_nodes)), prior_sd=prior_sd,\n                       alpha_mu=1.0, alpha_w=n_nodes + 4)\nprior_graphs = fit_graphs(\n    prior_score, baseline_probs, labels,\n    seed=SEED + 50, draws=4_000, tune=1_000, betas=np.array([1.0]),\n)\nprior_diagnostics = azs.summary(\n    graph_diagnostic_data(prior_graphs, graph_summary(prior_graphs), baseline_probs),\n    ci_prob=0.95, round_to=\"none\",\n)\n\n\ndef predictive_statistics(trace, current_score, size=400):\n    retained = trace.posterior.edge.values.reshape(-1, len(pairs))\n    output = np.empty((size, 3))\n    for draw, index in enumerate(rng_predictive.integers(len(retained), size=size)):\n        graph = states_to_parents(retained[index], pairs, n_nodes)\n        intercept, coefficients, variance = draw_parameters(current_score, graph, rng_predictive)\n        replicated = simulate_scm(graph, intercept, coefficients, variance, n_obs, rng_predictive)\n        output[draw] = [replicated[:, 6].mean(), replicated[:, 6].std(ddof=1),\n                        np.corrcoef(replicated[:, 3], replicated[:, 6])[0, 1]]\n    return output\n\n\nprior_predictive = predictive_statistics(prior_graphs, prior_score)\nposterior_predictive = predictive_statistics(posterior, score)\nobserved_statistics = np.array([y.mean(), y.std(ddof=1), np.corrcoef(d, y)[0, 1]])\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSequential sampling (4 chains in 1 job)\nTemperedGraphStep: [edge]\nSampling 4 chains for 1_000 tune and 4_000 draw iterations (4_000 + 16_000 draws total) took 1 seconds.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nlog_evidence is constant; diagnostics not estimable\nIndicators fixed by pair support: 6\nOther constant indicators: 1 (diagnostics not estimable)\n```\n:::\n:::\n\n\n::: {#cell-fig-prior-posterior-predictive .cell execution_count=26}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(1, 3, figsize=(12, 3.5))\nfor index, (ax, name) in enumerate(zip(axes, [\"Mean of y\", \"SD of y\", \"Correlation of d and y\"])):\n    limits = np.r_[prior_predictive[:, index], posterior_predictive[:, index]]\n    bins = np.linspace(limits.min(), limits.max(), 35)\n    ax.hist(prior_predictive[:, index], bins=bins, density=True, alpha=0.45,\n            color=COLORS[\"accent\"], label=\"Prior predictive\")\n    ax.hist(posterior_predictive[:, index], bins=bins, density=True, alpha=0.75,\n            color=COLORS[\"primary\"], label=\"Posterior predictive\")\n    ax.axvline(observed_statistics[index], color=COLORS[\"brown\"], linestyle=\"--\", label=\"Observed\")\n    ax.set(xlabel=name, ylabel=\"Density\")\naxes[0].legend(frameon=False, fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Prior and posterior predictive distributions of three dataset summaries. Each replicate uses one graph, jointly drawn mechanisms, and fresh observation noise. Vertical lines mark the observed summaries. These checks probe the model's data implications, not the truth of its causal directions.](bayesian_cpdag_graph_discovery_files/figure-html/fig-prior-posterior-predictive-output-1.png){#fig-prior-posterior-predictive width=1877 height=602 fig-alt='Histograms compare prior and posterior predictions for mean y, standard deviation of y, and correlation between d and y, with observed values marked.'}\n:::\n:::\n\n\nThe two equivalent DAGs can predict the same observed association between $d$ and $y$ while disagreeing about $\\operatorname{do}(d)$. A good posterior predictive fit does not settle that causal question. Nor do these three summaries exhaust model checking: residual structure, tails, nonlinear dependence, and relevant subgroups can expose failures these panels miss.\n\n# What if the relationship is not linear?\n\nLet's keep a simple graph, $x\\rightarrow z$, but change how the arrow works:\n\n$$\nx\\sim\\operatorname{Uniform}(-2,2),\\qquad z=x^2+\\varepsilon,\n\\quad \\varepsilon\\sim\\mathcal N(0,0.25^2),\\quad \\varepsilon\\perp x.\n$$\n\nThe population covariance is zero by symmetry, yet knowing $x$ tells us a great deal about $z$. We compare the three two-node **linear-Gaussian** DAGs with equal graph priors. The least-squares line and curve are visual guides, not alternative Bayesian evidence calculations.\n\n::: {#cell-fig-nonlinear-misspecification .cell execution_count=27}\n``` {.python .cell-code code-fold=\"true\"}\nrng_nonlinear = np.random.default_rng(SEED + 60)\nx = rng_nonlinear.uniform(-2, 2, size=600)\nz = x ** 2 + rng_nonlinear.normal(0, 0.25, size=600)\nnonlinear_score = BGeScore(np.column_stack([x, z]), prior_sd=np.array([1.0, 1.5]))\nnonlinear_probability = softmax([nonlinear_score.graph_score(graph) for graph in ([0, 0], [0, 1], [2, 0])])\ngrid = np.linspace(-2, 2, 200)\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\naxes[0].scatter(x, z, s=8, alpha=0.5, color=COLORS[\"primary\"], rasterized=True)\naxes[0].plot(grid, np.polyval(np.polyfit(x, z, 1), grid), linestyle=\"--\", color=COLORS[\"ink_muted\"], label=\"Line\")\naxes[0].plot(grid, np.polyval(np.polyfit(x, z, 2), grid), color=COLORS[\"green_strong\"], label=\"Quadratic\")\naxes[0].set(xlabel=\"x\", ylabel=\"z\", title=\"A curved mechanism\")\naxes[0].legend(frameon=False)\naxes[1].barh([\"No edge\", r\"$x \\rightarrow z$\", r\"$z \\rightarrow x$\"], nonlinear_probability, color=COLORS[\"primary\"])\naxes[1].set(xlim=(0, 1), xlabel=\"Posterior probability\", title=\"What the Gaussian family supports\")\nplt.show()\nprint(f\"P(no edge | nonlinear data, Gaussian candidates) = {nonlinear_probability[0]:.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![A linear-Gaussian graph score can favor no edge despite visible nonlinear dependence. The candidate family, not graph notation itself, misses the curve.](bayesian_cpdag_graph_discovery_files/figure-html/fig-nonlinear-misspecification-output-1.png){#fig-nonlinear-misspecification width=1577 height=677 fig-alt='A U-shaped scatter with a nearly flat line and fitted quadratic, next to BGe probabilities for no edge and the two arrow directions.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nP(no edge | nonlinear data, Gaussian candidates) = 0.841\n```\n:::\n:::\n\n\nBGe uses the sample size, means, and covariances. Those summaries miss the shape of this dependence. More careful graph MCMC cannot repair a likelihood that represents the wrong mechanisms.\n\nDAGs can represent nonlinear systems. We would need a likelihood and priors that allow them, rather than continuing to use BGe. With additional restrictions—such as nonlinear additive mechanisms with independent noise—observations can sometimes distinguish directions that conditional independences leave unresolved ([Hoyer et al., 2008](https://proceedings.neurips.cc/paper_files/paper/2008/file/f7664060cc52bc6f3d620bcedc94a4b6-Paper.pdf)). That does not hold for every nonlinear model, and we have not fitted such an orientation method here.\n\nA CPDAG still summarizes Markov equivalence. A richer model may use information beyond conditional independences to weight its members differently. We should not carry BGe's score-equivalence guarantee into a different model family.\n\n# Why PyMC, and what has it not supplied?\n\nPyMC holds the discrete unknown, compiles its log density, manages chains and random streams, and returns dimension-labeled posterior draws and sampler statistics. The named-tensor model makes the target inspectable. BGe supplies the exact parameter integral; the custom graph kernel supplies legal discrete moves. Merely writing an adjacency variable in a probabilistic program supplies neither.\n\nStan cannot directly sample a discrete graph parameter; a tractable finite candidate set can instead be marginalized. PyMC, NumPyro, and TensorFlow Probability can combine appropriate discrete and continuous kernels, but ordinary HMC or NUTS does not traverse DAG states. For nonlinear or nonconjugate mechanisms, both the marginal-likelihood calculation and the sampling design would need reconsideration.\n\nThis example is therefore a genuine PyMC graph posterior, but not a generic causal-discovery library. Its fast local table still grows as $p2^{p-1}$, and difficult posteriors may need better proposals or different graph representations. More nodes do not become free because the inner loop is compiled.\n\n\n# Considerations\n\n## What have we still assumed away?\n\nWe have compared DAGs on fixed, correctly measured nodes, with complete independent observations, linear-Gaussian mechanisms, no hidden common causes, and the graphical assumptions stated earlier. Our nonlinear example shows that a confident answer can survive a failure of those assumptions.\n\nSome limits cannot be checked from observational fit alone. A hidden cause can leave competing causal explanations observationally indistinguishable. Posterior predictive checks can reveal some model failures, but passing them does not prove a causal graph is correct. Agreement with the four-node oracle checks a small instance of our computation, not our scientific assumptions.\n\nHard restrictions deserve particular care. Our terminal-$y$ mask changes the candidate set; it is not a discovery from these observations. A cap of fewer than five parents would exclude both members of the generating class, and no amount of sampling could bring them back. Time ordering or forbidden arrows can be valuable knowledge, but a knowledge-oriented PDAG would be a different summary from the ordinary observational CPDAGs shown here. We also do not freeze directions merely because an early chain gives them low probability.\n\nHidden confounding, selection, missing data, feedback, and mixed variable types need methods and likelihoods that represent them. Hidden common causes, for example, call for other graph summaries, such as maximal ancestral graphs (MAGs) and partial ancestral graphs (PAGs). Those methods are outside this implementation.\n\n## What would I explore next?\n\nFirst, I would compare **selected-DAG and model-averaged effect posteriors across repeated simulations**. Start inside our candidate family, then introduce controlled errors such as hidden confounding or nonlinear mechanisms. Measure credible-set coverage, set size, and mistakes in intervention decisions. The sets should preserve the zero atom and allow separate components, rather than force everything into one bell-shaped interval.\n\nThat coverage study has not been run here. The open question is when carrying both structural and within-model uncertainty improves calibration, and when shared model errors still make the answer overconfident.\n\nTwo recent papers helped motivate this question. [Stith, Rahmani, and Cresswell (2026), *Causal Foundation Models*](https://arxiv.org/abs/2609.03003), average causal quantities over a posterior on data-generating processes. [Qi et al. (2026), *SurvivalPFN*](https://arxiv.org/abs/2605.15488), apply a related idea to survival prediction. They are useful starting points for this study, not a guarantee that our graph mixture has calibrated intervals.\n\n::: {.callout-note collapse=\"true\"}\n## What do those papers establish?\n\n*Causal Foundation Models* describes the averaging in §2.5 and discusses calibration separately in §5.2.4. The distinction matters: defining a Bayesian target and checking its calibration are different tasks.\n\n*SurvivalPFN*'s consistency result concerns an identifiable Bayesian predictive target under regularity conditions. It holds for almost every generating process under the prior; applying it to the network also requires exact or vanishing approximation error (Appendix C). Neither result gives our graph mixture a finite-sample coverage guarantee under arbitrary misspecification.\n:::\n\nSecond, I would ask what new evidence could separate the causal stories. In our generating class, changing $d$ affects $y$ under one DAG and does not under the other. An intervention on $d$, with $y$ measured afterward, could distinguish those two members. That is not yet an optimal experiment over the full posterior, and it needs an intervention model. But it is a more targeted next step than collecting more of the same observations and hoping the unresolved arrow will disappear.\n\n# Conclusions\n\nWe started with a small discomfort: a Bayesian posterior can describe uncertainty carefully while leaving the model itself unquestioned.\n\nOur response was not to remove assumptions. It was to make one part of them uncertain. We encoded directional beliefs and a hard mask, ran PyMC MCMC on the unresolved core, and reconstructed full graphs with exact terminal-parent draws. We then grouped observationally equivalent graphs into CPDAGs and carried their member probabilities into an intervention effect. Both the hard restriction and the prior-driven directions remain explicit.\n\nFour things are worth keeping:\n\n1. **A graph is part of a model, not the whole model.** Its probability depends on the mechanisms, parameter priors, and graph prior we chose.\n2. **A CPDAG preserves an unresolved question instead of inventing an answer.** “Completed” means all compelled directions are present, not that every direction is known.\n3. **Model averaging preserves alternatives; it does not guarantee truth.** An exact-zero component and a positive-effect component can both matter. A posterior mean misses their distinction. Even the full posterior can miss a mechanism outside its candidate family.\n4. **Reduce exploration without erasing uncertainty.** A justified mask excludes impossible directions; an exact terminal update replaces unnecessary MCMC. Neither operation makes the remaining causal conclusions automatically correct.\n\nFor practice, I would report the leading classes, Monte Carlo standard errors for graph-event probabilities, prior sensitivities, and how graph and prior uncertainty affect the decision. That is more useful than handing someone a single DAG and a precise-looking effect estimate.\n\n**If the decision depends on whether changing $d$ changes $y$, what evidence would separate the remaining causal stories?**\n\n\n## Recommended readings\n\n1. [Verma, T. and Pearl, J. (1990), *Equivalence and Synthesis of Causal Models*](https://ftp.cs.ucla.edu/pub/stat_ser/R150.pdf).\n2. [Geiger, D. and Heckerman, D. (1994), *Learning Gaussian Networks*](https://www.microsoft.com/en-us/research/publication/learning-gaussian-networks/).\n3. [Kuipers, J., Moffa, G., and Heckerman, D. (2014), *Addendum on the Scoring of Gaussian Directed Acyclic Graphical Models*](https://doi.org/10.1214/14-AOS1217).\n4. [Vehtari, A. et al. (2021), *Rank-Normalization, Folding, and Localization: An Improved R-hat for Assessing Convergence of MCMC*](https://doi.org/10.1214/20-BA1221).\n5. [Stith, C., Rahmani, H., and Cresswell, J. C. (2026), *Causal Foundation Models*](https://arxiv.org/abs/2609.03003).\n6. [Qi, S. et al. (2026), *SurvivalPFN: Amortizing Survival Prediction via In-Context Bayesian Inference*](https://arxiv.org/abs/2605.15488).\n\n7. [Chickering, D. M. (2002), *Learning Equivalence Classes of Bayesian-Network Structures*](https://www.jmlr.org/papers/volume2/chickering02a/chickering02a.pdf), especially the DAG-to-CPDAG algorithms in Figures 4–5.\n8. [PyMC: named dimensions](https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/dims_module.html) and [PyTensor: xtensor](https://pytensor.readthedocs.io/en/latest/library/xtensor/index.html).\n\n---\n\n## Watermark\n\n::: {#dc88fc22 .cell execution_count=28}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Executed software versions\"}\nfor package in (\"pymc\", \"pytensor\", \"arviz\", \"arviz-base\", \"arviz-stats\", \"numpy\", \"scipy\", \"numba\"):\n    print(f\"{package}: {version(package)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npymc: 6.3.2\npytensor: 3.3.1\narviz: 1.3.0\narviz-base: 1.3.0\narviz-stats: 1.3.2\nnumpy: 2.4.6\nscipy: 1.18.0\nnumba: 0.65.1\n```\n:::\n:::\n\n\n",
    "supporting": [
      "bayesian_cpdag_graph_discovery_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}