<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Carlos Trujillo">
<meta name="dcterms.date" content="2026-07-12">
<meta name="description" content="What PyTensor is missing for LLM inference—and how straightforward it is to build. A Python-native exploration of symbolic graphs, GGUF weights, C, Numba, MLX, and the path to a composable LLM runtime.">

<title>PyTensor Beyond PyMC: Building LLM Inference in Python — Carlos Trujillo – Marketing Science Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/icon/fav.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7dc88c0e4071ecedd75eb36a363dad2b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;family=Manrope:wght@600;700;800&amp;display=swap" rel="stylesheet">
<style>
  .navbar-title { background: none; -webkit-text-fill-color: initial; }
</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="PyTensor Beyond PyMC: Building LLM Inference in Python — Carlos Trujillo">
<meta property="og:description" content="What PyTensor is missing for LLM inference—and how straightforward it is to build. A Python-native exploration of symbolic graphs, GGUF weights, C, Numba, MLX, and the path to a composable LLM runtime.">
<meta property="og:image" content="https://cetagostini.github.io/images/alchemize_pytensor_mlx_gemma_3n.jpg">
<meta property="og:site_name" content="Marketing Science Blog">
<meta property="og:image:alt" content="Alchemize logo over PyTensor and MLX symbols representing LLM inference in Python">
<meta name="twitter:title" content="PyTensor Beyond PyMC: Building LLM Inference in Python — Carlos Trujillo">
<meta name="twitter:description" content="What PyTensor is missing for LLM inference—and how straightforward it is to build. A Python-native exploration of symbolic graphs, GGUF weights, C, Numba, MLX, and the path to a composable LLM runtime.">
<meta name="twitter:image" content="https://cetagostini.github.io/images/alchemize_pytensor_mlx_gemma_3n.jpg">
<meta name="twitter:image:alt" content="Alchemize logo over PyTensor and MLX symbols representing LLM inference in Python">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Marketing Science Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../articles.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../diary.html"> 
<span class="menu-text">Diary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../talks.html"> 
<span class="menu-text">Talks</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#what-alchemize-reveals" id="toc-what-alchemize-reveals" class="nav-link" data-scroll-target="#what-alchemize-reveals">What Alchemize reveals!</a></li>
  <li><a href="#building-gemma-3n-inference-in-pytensor" id="toc-building-gemma-3n-inference-in-pytensor" class="nav-link" data-scroll-target="#building-gemma-3n-inference-in-pytensor">Building Gemma 3n inference in PyTensor</a>
  <ul class="collapse">
  <li><a href="#stream-weights-instead-of-expanding-the-model" id="toc-stream-weights-instead-of-expanding-the-model" class="nav-link" data-scroll-target="#stream-weights-instead-of-expanding-the-model">Stream weights instead of expanding the model</a></li>
  <li><a href="#write-the-equations-once" id="toc-write-the-equations-once" class="nav-link" data-scroll-target="#write-the-equations-once">Write the equations once</a></li>
  <li><a href="#choose-the-backend-at-compilation" id="toc-choose-the-backend-at-compilation" class="nav-link" data-scroll-target="#choose-the-backend-at-compilation">Choose the backend at compilation</a></li>
  <li><a href="#run-gemma-inference-from-python" id="toc-run-gemma-inference-from-python" class="nav-link" data-scroll-target="#run-gemma-inference-from-python">Run Gemma inference from Python</a>
  <ul class="collapse">
  <li><a href="#ccvm-vs-numba-vs-mlx-performance-comparison" id="toc-ccvm-vs-numba-vs-mlx-performance-comparison" class="nav-link" data-scroll-target="#ccvm-vs-numba-vs-mlx-performance-comparison">C/CVM vs Numba vs MLX: performance comparison</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#what-the-current-speed-tells-us" id="toc-what-the-current-speed-tells-us" class="nav-link" data-scroll-target="#what-the-current-speed-tells-us">What the current speed tells us</a></li>
  <li><a href="#where-pytensor-and-llama.cpp-differ-and-why-that-matters" id="toc-where-pytensor-and-llama.cpp-differ-and-why-that-matters" class="nav-link" data-scroll-target="#where-pytensor-and-llama.cpp-differ-and-why-that-matters">Where PyTensor and llama.cpp differ — and why that matters</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/cetagostini/cetagostini.github.io/edit/main/articles/alchemize_pytensor_mlx_gemma_3n/alchemize_pytensor_mlx_gemma_3n.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cetagostini/cetagostini.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<a class="skip-link" href="#quarto-document-content">Skip to content</a>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Add the navbar-title class to the navbar brand
    const navbarBrand = document.querySelector('.navbar-brand');
    if (navbarBrand) {
      navbarBrand.classList.add('navbar-title');
    }
  });
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">PyTensor Beyond PyMC: Building LLM Inference in Python</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">python</div>
    <div class="quarto-category">pytensor</div>
    <div class="quarto-category">mlx</div>
    <div class="quarto-category">numba</div>
    <div class="quarto-category">llm</div>
    <div class="quarto-category">gguf</div>
    <div class="quarto-category">gemma</div>
  </div>
  </div>

<div>
  <div class="description">
    What PyTensor is missing for LLM inference—and how straightforward it is to build. A Python-native exploration of symbolic graphs, GGUF weights, C, Numba, MLX, and the path to a composable LLM runtime.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Carlos Trujillo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<link rel="canonical" href="https://cetagostini.github.io/articles/alchemize_pytensor_mlx_gemma_3n/alchemize_pytensor_mlx_gemma_3n.html">
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Most practitioners meet <a href="https://pytensor.readthedocs.io/">PyTensor</a> through PyMC. We write a probabilistic model, PyMC builds a symbolic graph, and PyTensor compiles the mathematics into something a machine can execute.</p>
<p>That description is accurate. It is also incomplete.</p>
<p>PyTensor is a general symbolic tensor compiler. It does not know what a prior is, and it does not require a likelihood. It is the graph compiler at the heart of probabilistic programming, but its architecture was never limited to that domain. This article explores what happens when we push it toward something the authors may not have originally intended—local LLM inference—and what that tells us about where PyTensor, and the <a href="https://github.com/pymc-labs/pytensor-ml">pytensor-ml</a> project, could go next.</p>
<p>Here is what PyTensor itself already has: multi-backend execution (JAX, MLX, Numba, C) and symbolic graph optimization that simplifies computation before it hits hardware. The ML layer lives one level up, in the ecosystem around it: <a href="https://github.com/jessegrabowski/pytensor_ml"><code>pytensor-ml</code></a> already demonstrates working inference for small models, GGUF dequantization comes from the <a href="https://github.com/ggml-org/llama.cpp/tree/master/gguf-py"><code>gguf</code></a> library, and the <a href="https://github.com/pymc-labs/alchemize">Alchemize</a> pipeline auto-generates PyTensor modules from GGUF metadata.</p>
<p>Here is what is missing: production KV caching, continuous batching, mmap zero-copy loading, and the performance tuning that makes <code>llama.cpp</code> serve models at scale. Those gaps define the roadmap. Here we build the complete vertical slice underneath them: model loading, symbolic execution, generation, and independent numerical validation.</p>
<p>The story this article tells is not about replacing <code>llama.cpp</code>. It is about discovering how straightforward it is to assemble an LLM inference stack in PyTensor—weights, tokenization, a symbolic transformer, a generation loop, and numerical validation—once the graph compiler is freed from its probabilistic assumptions. And it is about what becomes possible when those pieces come together.</p>
<p>It will be really cool be able to run the following in full pytensor no? And if you think it would not, imagine the advantages:</p>
<ul>
<li><strong>One definition, any backend.</strong> The same symbolic equations compile through C, Numba, MLX, or JAX. Swapping hardware targets is a one-argument change, not a rewrite.</li>
<li><strong>Inference that composes.</strong> The model is a graph inside the scientific Python stack—chain it with a PyMC posterior, a SciPy optimizer, or any custom computation, all in the same framework.</li>
<li><strong>A graph you can open.</strong> Every operation is inspectable and rewritable. You can ask what a rewrite changed instead of trusting a black box.</li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pytensor <span class="im">import</span> load_llm</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> load_llm(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"/path/to/gemma-3n-E4B-it-lm-4bit/snapshot"</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    backend<span class="op">=</span><span class="st">"c"</span>, <span class="co"># or any other.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> inference(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    model,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span><span class="op">=</span><span class="st">"What's causal inference?"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    max_tokens<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>That small interface is our destination.</p>
<p>To reach it, we have to assemble the full stack ourselves. PyTensor owns exactly one layer—rewriting the graph and linking it to MLX, C/CVM, or Numba—and everything around it is explicit Python: weight adapters that validate, map, dequantize, and orient GGUF or safetensors weights; tokenizer adapters that apply the model’s chat template and produce exact token IDs; a symbolic model that expresses normalization, RoPE, attention, residual paths, and MLPs; a generation runtime that runs prefill, updates KV state, chooses tokens, and stops; and a report layer that returns text, timings, memory, and differential checks. The first step on that path is <a href="https://github.com/pymc-labs/alchemize">Alchemize</a>: it reads the GGUF metadata and hands us the map—the tensor-name inventory, the block structure, and the exact contracts that are missing. Then we build—one piece at a time.</p>
<p>We build each piece against Gemma 3n E4B through C/CVM, Numba, and MLX, measure what the current speed tells us, and project forward.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The argument
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>PyTensor already has the graph, rewrite, and linker abstractions to become the computational core of a Python-native LLM runtime. What is missing is not the foundation—it is the production engineering on top of it. And building that engineering in PyTensor is surprisingly straightforward.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is Alchemize?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="https://github.com/pymc-labs/alchemize">Alchemize</a> is an LLM-based, self-correcting transpiler from PyMC Labs. It acts as an AI agent that compiles computational models between frameworks: PyMC, Stan, JAX, PyTorch, and Rust—with numerical validation at every step. The agent reasons about the full computational graph and applies optimizations a domain expert would: loop fusion, memory pre-allocation, cache-friendly access patterns.</p>
</div>
</div>
</div>
</section>
<section id="what-alchemize-reveals" class="level1">
<h1>What Alchemize reveals!</h1>
<p>With the destination visible, we can rewind and follow the path that produced it—starting with what is missing.</p>
<p>We begin with <code>SmolLM2-135M-Instruct-Q4_K_M.gguf</code>, a roughly 105 MB GGUF file. Our first attempt is to ask <a href="https://github.com/pymc-labs/alchemize">Alchemize</a> for a PyTensor implementation:</p>
<div id="fc26c207" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show Alchemize call</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> alchemize <span class="im">import</span> compile_model</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> compile_model(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    model_path<span class="op">=</span>Path(<span class="st">"/path/to/SmolLM2-135M-Instruct-Q4_K_M.gguf"</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    target<span class="op">=</span><span class="st">"pytensor"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Alchemize reads the GGUF metadata and generates a module with the right architecture skeleton. That is valuable: it gives us the tensor-name map, the block inventory, and the layer structure without writing any of it by hand.</p>
<p>But the generated implementation cannot run. Its central loading assumption is wrong:</p>
<div id="8eb35c1c" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show generated materialize_tensor</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> materialize_tensor(tensor):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> <span class="bu">getattr</span>(tensor, <span class="st">"data"</span>, <span class="va">None</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    array <span class="op">=</span> np.asarray(data)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.issubdtype(array.dtype, np.floating):</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.asarray(array, dtype<span class="op">=</span>np.float32)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">NotImplementedError</span>(<span class="st">"a dequantizer is required"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Most tensors in this GGUF are not floating arrays. They are packed quantized values. The generated implementation recognizes the problem and stops, but it never calls <code>gguf.dequantize</code>.</p>
<p>The static audit therefore gives us:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Check</th>
<th>Result</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Provenance and syntax</td>
<td>pass</td>
<td>the artifact is pinned and valid Python</td>
</tr>
<tr class="even">
<td>GGUF dequantization</td>
<td><code>STATIC_FAIL</code></td>
<td>packed weights are never dequantized</td>
</tr>
<tr class="odd">
<td>Attention head reshape</td>
<td><code>STATIC_FAIL</code> audit flag</td>
<td>symbolic reshapes do not preserve the repaired runtime’s static contracts</td>
</tr>
<tr class="even">
<td>Runtime</td>
<td><code>BLOCKED</code></td>
<td>generated code is never executed</td>
</tr>
<tr class="odd">
<td>Semantics</td>
<td><code>UNVERIFIED</code></td>
<td>valid syntax does not establish correct logits</td>
</tr>
</tbody>
</table>
<p>This is not a failure. It is a map.</p>
<p>Alchemize accelerated architecture discovery and told us exactly what is missing. The generated code gives us the skeleton; the static audit tells us which contracts need hand-built replacements. We keep the tensor-name map and block inventory, then build the pieces that fill the gaps: materialization, orientation, graph construction, caching, execution, and validation.</p>
</section>
<section id="building-gemma-3n-inference-in-pytensor" class="level1">
<h1>Building Gemma 3n inference in PyTensor</h1>
<p>A correct answer depends on a chain of contracts: quantized weight dequantization, tensor orientation, tokenization, rotary embeddings, grouped-query attention, KV caching, and backend compilation. Break one contract and the model may still produce plausible text. So we build each contract explicitly and compose them into a working pipeline.</p>
<p>Our target is Gemma 3n E4B—a much larger and stranger model than a typical first experiment. It adds four AltUp residual streams, a learned low-rank LAuReL path, per-layer token embeddings, sparse and dense activation variants, sliding and full attention, and a 262,400-token vocabulary. Can we express all of that in PyTensor’s symbolic language without changing the framework?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th style="text-align: right;">E4B configuration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decoder layers</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td>Hidden size</td>
<td style="text-align: right;">2,048</td>
</tr>
<tr class="odd">
<td>Query / KV heads</td>
<td style="text-align: right;">8 / 2</td>
</tr>
<tr class="even">
<td>Head dimension</td>
<td style="text-align: right;">256</td>
</tr>
<tr class="odd">
<td>MLP width</td>
<td style="text-align: right;">16,384</td>
</tr>
<tr class="even">
<td>Vocabulary</td>
<td style="text-align: right;">262,400</td>
</tr>
<tr class="odd">
<td>AltUp streams</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>LAuReL rank</td>
<td style="text-align: right;">64</td>
</tr>
<tr class="odd">
<td>Sliding window</td>
<td style="text-align: right;">512</td>
</tr>
<tr class="even">
<td>Final logit softcap</td>
<td style="text-align: right;">30</td>
</tr>
</tbody>
</table>
<p>This case deliberately validates <strong>multi-token, full-prefix generation</strong>. It does not retain a KV cache between decoding steps. Instead, every step rebuilds the complete prefix, creates the model’s shared-KV topology for that one forward, and discards it afterward.</p>
<section id="stream-weights-instead-of-expanding-the-model" class="level2">
<h2 class="anchored" data-anchor-id="stream-weights-instead-of-expanding-the-model">Stream weights instead of expanding the model</h2>
<p>The 3.86 GB checkpoint stores each affine-4 linear module as packed <code>uint32</code> weights plus BF16 scales and biases. Eight four-bit values occupy one word:</p>
<p><span class="math display">
W_{r,c} = q_{r,c}s_{r,g(c)} + b_{r,g(c)}.
</span></p>
<p>Here, <span class="math inline">q_{r,c}</span> is the stored nibble at output row <span class="math inline">r</span> and input column <span class="math inline">c</span>; <span class="math inline">s_{r,g(c)}</span> and <span class="math inline">b_{r,g(c)}</span> are the scale and bias for its group.</p>
<p>Fully expanding all logical parameters would need about <strong>25.6 GiB</strong> for FP32 weights alone. We instead:</p>
<ul>
<li>load only requested embedding rows,</li>
<li>dequantize one decoder layer at a time,</li>
<li>release it before loading the next layer, and</li>
<li>project vocabulary logits in chunks of 4,096 rows.</li>
</ul>
<div id="702abbd3" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show weight streaming</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor.weights <span class="im">import</span> Gemma3nWeightLoader</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> Gemma3nWeightLoader.from_snapshot(snapshot_path) <span class="im">as</span> loader:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    token_rows <span class="op">=</span> loader.load_input_embedding_rows(token_ids)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    layer_0 <span class="op">=</span> loader.load_layer(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Streaming changes the problem from “hold the expanded model” to “hold the current expanded layer.”</p>
</section>
<section id="write-the-equations-once" class="level2">
<h2 class="anchored" data-anchor-id="write-the-equations-once">Write the equations once</h2>
<p>The shared normalization is ordinary PyTensor:</p>
<div id="23ee3f9b" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show rmsnorm_symbolic</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor.ops <span class="im">import</span> rmsnorm_symbolic</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>normalized <span class="op">=</span> rmsnorm_symbolic(hidden, gamma, eps<span class="op">=</span><span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The important detail is not the formula. It is that <code>rmsnorm_symbolic</code> knows nothing about C, Numba, or MLX.</p>
<p>The same is true for grouped-query attention, RoPE, masks, AltUp, and LAuReL. Gemma’s sparse and dense GELU paths produce two specialized <code>FunctionGraph</code>s; full versus sliding attention arrives as mask and RoPE data. The operation order follows the pinned MLX-LM implementation—including LAuReL’s apparent repeated residual and the sparse GELU sparsity pattern read from the checkpoint.</p>
</section>
<section id="choose-the-backend-at-compilation" class="level2">
<h2 class="anchored" data-anchor-id="choose-the-backend-at-compilation">Choose the backend at compilation</h2>
<p>Backend selection is now a small, reusable utility:</p>
<div id="2c0698f3" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show backend selection</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor.backends <span class="im">import</span> get_mode</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>c_mode <span class="op">=</span> get_mode(<span class="st">"c"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>numba_mode <span class="op">=</span> get_mode(<span class="st">"numba"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>mlx_mode <span class="op">=</span> get_mode(<span class="st">"mlx"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>c_layer <span class="op">=</span> pytensor.function(layer_inputs, layer_output, mode<span class="op">=</span>c_mode)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>numba_layer <span class="op">=</span> pytensor.function(layer_inputs, layer_output, mode<span class="op">=</span>numba_mode)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>mlx_layer <span class="op">=</span> pytensor.function(layer_inputs, layer_output, mode<span class="op">=</span>mlx_mode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The model definition did not change. Only the linker and rewrite policy changed.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
One model, multiple compiler experiments
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we change a symbolic equation, every backend inherits it. If we change only a rewrite or linker, the model remains fixed. That separation is PyTensor’s main contribution to this experiment.</p>
</div>
</div>
</section>
<section id="run-gemma-inference-from-python" class="level2">
<h2 class="anchored" data-anchor-id="run-gemma-inference-from-python">Run Gemma inference from Python</h2>
<p>The same public entry point now targets a different artifact and backend:</p>
<div id="2c7c765e" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor <span class="im">import</span> Gemma3n, inference</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>gemma <span class="op">=</span> Gemma3n.from_snapshot(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"/path/to/gemma-3n-E4B-it-lm-4bit/snapshot"</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    backend<span class="op">=</span><span class="st">"c"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> inference(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    gemma,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span><span class="op">=</span><span class="st">"What's causal inference?"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    max_tokens<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>result.output, result.output_token_ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre class="text"><code>('## Causal Inference: Understanding "Why" vs. "Correlation"\n\n'
 'Causal inference is a branch of statistics and statistics is a field '
 'of statistics that aims',
 (1408, 565, 90718, 157036, 236787, 40411, 623, 11355, 236775,
  7728, 236761, 623, 131426, 236775, 108, 236780, 90718, 34711,
  563, 496, 9911, 529, 14906, 532, 14906, 563, 496, 2135,
  529, 14906, 600, 17269))</code></pre>
<p>That is an actual continuation, not one next-token prediction. It is also not polished prose: greedy decoding reaches the 32-token cap mid-sentence and becomes repetitive after the differential path separates. The point is to make generation inspectable, not to present a language-quality benchmark.</p>
<div id="6df2c2cb" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show validation report</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>result.report.validation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<pre class="text"><code>{
    'final_top1_match': True,
    'all_top1_match': False,
    'pearson_mean': 0.998932415848074,
    'top10_overlap_mean': 9.533333333333333,
    'thresholds_passed': True,
    'scope': 'all_generated_prefixes_fresh_cache',
    'all_generated_tokens_match': False,
}</code></pre>
<p>The initial 15-token prompt passes the publication thresholds and selects the same next token in PyTensor and MLX-LM. Generation then validates each growing PyTensor prefix against an MLX-LM forward over that exact prefix. Each oracle call creates a fresh shared-KV object and discards it; no decode state survives into the next step.</p>
<p>The first 20 generated decisions agree. At token 21, PyTensor chooses <code>9911</code> while the fresh-prefix MLX oracle chooses <code>2135</code>. The report records that divergence and keeps evaluating MLX on the subsequent <strong>PyTensor prefix</strong>, so later comparisons remain well-defined. It does not compare two independently drifting streams, and it no longer throws away an expensive completed generation because cached <code>stream_generate</code> follows a different path.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Multi-token result</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Visible tokens</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td>Matching fresh-prefix decisions</td>
<td style="text-align: right;">31 / 32</td>
</tr>
<tr class="odd">
<td>First divergence</td>
<td style="text-align: right;">token 21</td>
</tr>
<tr class="even">
<td>Prefix graph compilations</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td>Additional generation wall time</td>
<td style="text-align: right;">1,612.038 s</td>
</tr>
<tr class="even">
<td>Peak process RSS</td>
<td style="text-align: right;">9,668.61 MiB</td>
</tr>
<tr class="odd">
<td>Stop reason</td>
<td style="text-align: right;"><code>max_tokens</code></td>
</tr>
</tbody>
</table>
<p>The cost is the lesson. After the initial validated prompt pass, the remaining full-prefix generation loop took <strong>1,612.038 seconds</strong>, or about <strong>26.9 minutes</strong>. This is an educational execution strategy that exposes every graph and comparison; it is not an efficient decoder.</p>
<section id="ccvm-vs-numba-vs-mlx-performance-comparison" class="level3">
<h3 class="anchored" data-anchor-id="ccvm-vs-numba-vs-mlx-performance-comparison">C/CVM vs Numba vs MLX: performance comparison</h3>
<p>All three backends compile the same symbolic equations and select the same top-1 token as the independent MLX-LM oracle at all 20 prompt positions. Their mean all-logit Pearson correlation with the oracle is 0.9986, and their mean top-10 overlap is 9.7 out of 10.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">C/CVM</th>
<th style="text-align: right;">Numba</th>
<th style="text-align: right;">MLX</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Graph compilation</td>
<td style="text-align: right;">7.738 s</td>
<td style="text-align: right;">0.775 s</td>
<td style="text-align: right;"><strong>0.755 s</strong></td>
</tr>
<tr class="even">
<td>One full forward (20 positions)</td>
<td style="text-align: right;">51.441 s</td>
<td style="text-align: right;">53.800 s</td>
<td style="text-align: right;"><strong>50.211 s</strong></td>
</tr>
<tr class="odd">
<td>Mean per-layer time</td>
<td style="text-align: right;">1.272 s</td>
<td style="text-align: right;">1.266 s</td>
<td style="text-align: right;"><strong>1.246 s</strong></td>
</tr>
<tr class="even">
<td>Logit projection</td>
<td style="text-align: right;"><strong>3.024 s</strong></td>
<td style="text-align: right;">4.700 s</td>
<td style="text-align: right;">3.086 s</td>
</tr>
<tr class="odd">
<td>Whole-process peak RSS</td>
<td style="text-align: right;"><strong>4,523 MiB</strong></td>
<td style="text-align: right;">4,663 MiB</td>
<td style="text-align: right;">5,111 MiB</td>
</tr>
</tbody>
</table>
<p>These are single-run measurements of an intentionally streamed educational pipeline, not a throughput benchmark. MLX compiles about 10 times faster than C and records the shortest forward, but only by 2.4%. C still wins the 262,400-vocabulary projection. Weight dequantization, Python orchestration, and per-layer streaming dominate enough that the three full forwards remain in the same range.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How the failed MLX probe became a working backend
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first MLX probe failed because the generated draft relied on shapes and operations that the pinned linker could not lower safely. We did not patch the installed PyTensor package or mutate a process-global dispatch registry. Instead, we expressed projections as rank-2 matrix multiplies with explicit reshapes, kept attention in ordinary tensor primitives, and replaced Gemma’s AltUp clip sites with a repository-local symbolic helper built from comparisons and <code>where</code>.</p>
<p>The resulting graph compiles through PyTensor 3.1.2’s built-in <code>pytensor.compile.mode.MLX</code>. MLX evaluates lazily, so the runner materializes 103 ordered boundaries: two initial projections, 35 decoder layers, one final unembed, and 65 vocabulary chunks. Intermediate tensors remain device-resident; only completed logit chunks cross back to owning NumPy arrays. The measured MLX allocator peak was 455 MiB beyond its near-zero baseline, while whole-process RSS reached 5,111 MiB.</p>
</div>
</div>
</div>
<p>The complete reports are available for the independent <a href="results/gemma3n_mlx_lm_oracle.json">MLX-LM oracle</a>, <a href="results/gemma3n_pytensor_c.json">C/CVM</a>, <a href="results/gemma3n_pytensor_numba.json">Numba</a>, and <a href="results/gemma3n_pytensor_mlx.json">MLX</a>. A separate validator reloaded the temporary raw logits, recomputed every metric instead of trusting the reports, and passed <a href="results/gemma3n_report_validation.json">896 of 896 gates</a>. The large raw arrays are not committed; the reports preserve their shapes, dtypes, byte counts, and cryptographic hashes. The earlier 32-token generation run remains in <a href="results/gemma3n_pytensor_generation.json"><code>gemma3n_pytensor_generation.json</code></a>.</p>
</section>
</section>
</section>
<section id="what-the-current-speed-tells-us" class="level1">
<h1>What the current speed tells us</h1>
<p>The numbers above are not benchmarks. They are measurements of an educational pipeline, and they should be read that way. But they are honest, and they tell us something precise about where the engineering effort needs to go.</p>
<p>Gemma 3n through full-prefix regeneration runs at roughly <strong>0.02 tokens per second</strong>. That is the cost of recompiling and re-evaluating the entire prefix for every generated token. It is deliberately expensive—it validates correctness—but it is not how a production system would work.</p>
<p>The engineering roadmap from here is clear:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Bottleneck</th>
<th>Current state</th>
<th>What unlocks it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>KV cache</td>
<td>fixed-capacity, O(C) write per layer</td>
<td>paged or ring-buffer cache, continuous batching</td>
</tr>
<tr class="even">
<td>Weight loading</td>
<td>per-layer streaming (dequantize on demand)</td>
<td>mmap zero-copy, quantized kernels</td>
</tr>
<tr class="odd">
<td>Backend execution</td>
<td>C/CVM, Numba, and MLX on Apple Silicon</td>
<td>backend-native quantized kernels and less host-device movement</td>
</tr>
<tr class="even">
<td>Graph compilation</td>
<td>recompilation per prefix length</td>
<td>cached compiled functions per shape, or JIT</td>
</tr>
</tbody>
</table>
<p><code>llama.cpp</code> has spent years on every row of that table. PyTensor has the graph compiler and the multi-backend architecture; it does not yet have the serving infrastructure. The question is not whether PyTensor can match <code>llama.cpp</code>’s throughput today—it cannot—but whether the pieces are in place to build that infrastructure in Python. The answer, after this experiment, is yes.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The composability advantage
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>llama.cpp</code> is a self-contained inference engine. PyTensor is a graph compiler that can compose with JAX transformations, NumPy operations, SciPy optimizers, and the rest of the scientific Python stack. The moment LLM inference lives inside that ecosystem, you can chain it with Bayesian analysis, gradient-based optimization, or custom symbolic computation—workflows that a standalone C++ engine was never designed to support.</p>
</div>
</div>
</section>
<section id="where-pytensor-and-llama.cpp-differ-and-why-that-matters" class="level1">
<h1>Where PyTensor and llama.cpp differ — and why that matters</h1>
<p>Now we can make the comparison precise:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Capability</th>
<th>This PyTensor stack</th>
<th><code>llama.cpp</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inspectable symbolic graph</td>
<td>yes</td>
<td>not its primary user abstraction</td>
</tr>
<tr class="even">
<td>User-defined graph rewrites</td>
<td>yes</td>
<td>no equivalent Python rewrite database</td>
</tr>
<tr class="odd">
<td>C, Numba, and MLX experiments</td>
<td>demonstrated on Gemma 3n E4B</td>
<td>purpose-built CPU, Metal, CUDA, and other backends</td>
</tr>
<tr class="even">
<td>GGUF parsing</td>
<td>supplied by <code>gguf-py</code> adapter</td>
<td>built in</td>
</tr>
<tr class="odd">
<td>Native quantized matmul</td>
<td>not implemented here</td>
<td>built in</td>
</tr>
<tr class="even">
<td>Tokenization and chat templates</td>
<td>Python adapters</td>
<td>built in</td>
</tr>
<tr class="odd">
<td>Autoregressive loop</td>
<td>Python, model-specific</td>
<td>built in</td>
</tr>
<tr class="even">
<td>Production KV cache and batching</td>
<td>no</td>
<td>built in</td>
</tr>
<tr class="odd">
<td>Broad architecture support</td>
<td>one validated fixture (Gemma 3n)</td>
<td>broad, maintained model coverage</td>
</tr>
<tr class="even">
<td>Composability with scientific Python</td>
<td>native</td>
<td>not designed for it</td>
</tr>
</tbody>
</table>
<p><code>llama.cpp</code> wins on integrated inference engineering. That is exactly what it is built for.</p>
<p>But the local LLM ecosystem is not just about running one model fast. It is about what you do with the model afterward.</p>
<p>The recent history of Ollama—<a href="https://sleepingrobots.com/dreams/stop-using-ollama/">documented thoroughly by sleepingrobots</a>—shows what happens when a wrapper obscures its dependencies and pivots to cloud. The ecosystem needs alternatives built on honest, transparent foundations. PyTensor and <code>llama.cpp</code> are those foundations.</p>
<ul>
<li><strong><code>llama.cpp</code></strong> is the C++ engine for running any GGUF model fast. It owns the full serving stack: quantized kernels, KV cache management, continuous batching, broad architecture support. If you need to serve models at production scale today, <code>llama.cpp</code> is the answer.</li>
<li><strong>PyTensor</strong> is the Python-native graph compiler for studying, modifying, and composing LLM inference. You do not just run a model—you can ask what a rewrite changed, compile the same equations through another linker, chain inference with a Bayesian posterior or a custom optimization loop, and validate every contract numerically.</li>
</ul>
<p>The honest claim is not “PyTensor replaces <code>llama.cpp</code>”. It is this:</p>
<p><span style="color:var(--green-strong)">PyTensor</span> plus explicit Python adapters is a credible <em>Python-native alternative</em> to <code>llama.cpp</code> that <strong>composes with the scientific computing stack</strong>—Bayesian analysis, optimization, custom computation graphs—in ways a standalone C++ engine was never designed for.</p>
<p>If someone builds KV caching, mmap zero-copy loading, and continuous batching on PyTensor’s JAX backend, and <a href="https://github.com/pymc-labs/alchemize">Alchemize</a> matures for auto-generating new architectures from GGUF metadata, we could see PyTensor become the “language” for running multiple LLMs the way <code>llama.cpp</code> is today. Not faster at inference—or maybe at some point—but more capable as a general-purpose LLM runtime that plugs into workflows <code>llama.cpp</code> was never built for.</p>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<ol type="1">
<li><strong>PyTensor is a general graph compiler.</strong> PyMC is its most visible consumer, not the boundary of what it can express.</li>
<li><strong>Building LLM inference in PyTensor is straightforward.</strong> Weight loaders, symbolic transformers, KV caches, generation loops, and numerical validation—all assembled from Python without modifying the framework.</li>
<li><strong>One symbolic definition survives multiple backends.</strong> Gemma 3n executes through C/CVM, Numba, and MLX without a second model implementation.</li>
<li><strong>Independent logits beat plausible prose.</strong> Exact tokens and all-position numerical agreement are stronger evidence than plausible-looking text.</li>
<li><strong>PyTensor and <code>llama.cpp</code> are complementary.</strong> <code>llama.cpp</code> owns production serving. PyTensor owns graph transparency and composability with scientific Python.</li>
<li><strong>The remaining gaps are engineering, not architecture.</strong> Native quantized kernels, paged KV caching, mmap zero-copy loading, and broader backend coverage are all buildable on PyTensor’s existing foundation. The pytensor-ml project has already begun this work.</li>
</ol>
<p>Recommended readings:</p>
<ol type="1">
<li><a href="https://pytensor.readthedocs.io/">PyTensor documentation</a></li>
<li><a href="https://pytensor.readthedocs.io/en/latest/extending/graph_rewriting.html">PyTensor graph rewriting</a></li>
<li><a href="https://pytensor.readthedocs.io/en/latest/library/compile/mode.html">PyTensor compilation modes</a></li>
<li><a href="https://github.com/ggml-org/llama.cpp">llama.cpp</a></li>
<li><a href="https://github.com/ml-explore/mlx-lm">MLX-LM</a></li>
<li><a href="https://github.com/pymc-labs/alchemize">Alchemize</a></li>
<li><a href="https://github.com/pymc-labs/pytensor-ml">pytensor-ml</a></li>
<li><a href="https://sleepingrobots.com/dreams/stop-using-ollama/">Friends Don’t Let Friends Use Ollama</a></li>
</ol>
<p>The recorded experiment used:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th>Version or pin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Python</td>
<td><code>3.13.14</code></td>
</tr>
<tr class="even">
<td>PyTensor</td>
<td><code>3.1.2</code></td>
</tr>
<tr class="odd">
<td>PyTensor-ML</td>
<td><code>f6ecf81d58da180cce50b77a43cf5d2c3d95e470</code></td>
</tr>
<tr class="even">
<td>MLX</td>
<td><code>0.32.0</code></td>
</tr>
<tr class="odd">
<td>Numba</td>
<td><code>0.65.1</code></td>
</tr>
<tr class="even">
<td>MLX-LM</td>
<td><code>0.31.3</code></td>
</tr>
<tr class="odd">
<td>Machine</td>
<td>Apple M3 Max, 128 GB unified memory</td>
</tr>
</tbody>
</table>
<p>The exact environment is recorded in <a href="environment.yml"><code>environment.yml</code></a>. Code cells are not executed during the website build because the model artifacts are intentionally excluded from Git; the committed JSON reports preserve the artifact hashes and measured outputs. The PyTensor suite passed 934 tests with 30 skips, and the gated real-model runner tests passed all 189 checks; the compact record is in <a href="results/gemma3n_test_summary.json"><code>gemma3n_test_summary.json</code></a>.</p>
<hr>
<p>The public package, model-specific implementations, tests, generated draft, audits, and sanitized result reports are available in the <a href="https://github.com/cetagostini/cetagostini.github.io">site repository</a>.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/cetagostini\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb11" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "PyTensor Beyond PyMC: Building LLM Inference in Python"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="an">pagetitle:</span><span class="co"> "PyTensor Beyond PyMC: Building LLM Inference in Python — Carlos Trujillo"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Carlos Trujillo"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-07-12"</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "What PyTensor is missing for LLM inference—and how straightforward it is to build. A Python-native exploration of symbolic graphs, GGUF weights, C, Numba, MLX, and the path to a composable LLM runtime."</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="an">aliases:</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">  - gemma3n_e4b_symbolic_pytensor_inference.html</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [python, pytensor, mlx, numba, llm, gguf, gemma]</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> "/images/alchemize_pytensor_mlx_gemma_3n.jpg"</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="an">image-alt:</span><span class="co"> "Alchemize logo over PyTensor and MLX symbols representing LLM inference in Python"</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co">  eval: false</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co">  freeze: false</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>Most practitioners meet <span class="co">[</span><span class="ot">PyTensor</span><span class="co">](https://pytensor.readthedocs.io/)</span> through PyMC. We write a probabilistic model, PyMC builds a symbolic graph, and PyTensor compiles the mathematics into something a machine can execute.</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>That description is accurate. It is also incomplete.</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>PyTensor is a general symbolic tensor compiler. It does not know what a prior is, and it does not require a likelihood. It is the graph compiler at the heart of probabilistic programming, but its architecture was never limited to that domain. This article explores what happens when we push it toward something the authors may not have originally intended—local LLM inference—and what that tells us about where PyTensor, and the <span class="co">[</span><span class="ot">pytensor-ml</span><span class="co">](https://github.com/pymc-labs/pytensor-ml)</span> project, could go next.</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>Here is what PyTensor itself already has: multi-backend execution (JAX, MLX, Numba, C) and symbolic graph optimization that simplifies computation before it hits hardware. The ML layer lives one level up, in the ecosystem around it: <span class="co">[</span><span class="ot">`pytensor-ml`</span><span class="co">](https://github.com/jessegrabowski/pytensor_ml)</span> already demonstrates working inference for small models, GGUF dequantization comes from the <span class="co">[</span><span class="ot">`gguf`</span><span class="co">](https://github.com/ggml-org/llama.cpp/tree/master/gguf-py)</span> library, and the <span class="co">[</span><span class="ot">Alchemize</span><span class="co">](https://github.com/pymc-labs/alchemize)</span> pipeline auto-generates PyTensor modules from GGUF metadata.</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>Here is what is missing: production KV caching, continuous batching, mmap zero-copy loading, and the performance tuning that makes <span class="in">`llama.cpp`</span> serve models at scale. Those gaps define the roadmap. Here we build the complete vertical slice underneath them: model loading, symbolic execution, generation, and independent numerical validation.</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>The story this article tells is not about replacing <span class="in">`llama.cpp`</span>. It is about discovering how straightforward it is to assemble an LLM inference stack in PyTensor—weights, tokenization, a symbolic transformer, a generation loop, and numerical validation—once the graph compiler is freed from its probabilistic assumptions. And it is about what becomes possible when those pieces come together.</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>It will be really cool be able to run the following in full pytensor no? And if you think it would not, imagine the advantages:</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**One definition, any backend.** The same symbolic equations compile through C, Numba, MLX, or JAX. Swapping hardware targets is a one-argument change, not a rewrite.</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Inference that composes.** The model is a graph inside the scientific Python stack—chain it with a PyMC posterior, a SciPy optimizer, or any custom computation, all in the same framework.</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**A graph you can open.** Every operation is inspectable and rewritable. You can ask what a rewrite changed instead of trusting a black box.</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pytensor <span class="im">import</span> load_llm</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> load_llm(</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"/path/to/gemma-3n-E4B-it-lm-4bit/snapshot"</span>),</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>    backend<span class="op">=</span><span class="st">"c"</span>, <span class="co"># or any other.</span></span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> inference(</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>    model,</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span><span class="op">=</span><span class="st">"What's causal inference?"</span>,</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>    max_tokens<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>That small interface is our destination.</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>To reach it, we have to assemble the full stack ourselves. PyTensor owns exactly one layer—rewriting the graph and linking it to MLX, C/CVM, or Numba—and everything around it is explicit Python: weight adapters that validate, map, dequantize, and orient GGUF or safetensors weights; tokenizer adapters that apply the model's chat template and produce exact token IDs; a symbolic model that expresses normalization, RoPE, attention, residual paths, and MLPs; a generation runtime that runs prefill, updates KV state, chooses tokens, and stops; and a report layer that returns text, timings, memory, and differential checks. The first step on that path is <span class="co">[</span><span class="ot">Alchemize</span><span class="co">](https://github.com/pymc-labs/alchemize)</span>: it reads the GGUF metadata and hands us the map—the tensor-name inventory, the block structure, and the exact contracts that are missing. Then we build—one piece at a time.</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>We build each piece against Gemma 3n E4B through C/CVM, Numba, and MLX, measure what the current speed tells us, and project forward.</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="simple"}</span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## The argument</span></span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>PyTensor already has the graph, rewrite, and linker abstractions to become the computational core of a Python-native LLM runtime. What is missing is not the foundation—it is the production engineering on top of it. And building that engineering in PyTensor is surprisingly straightforward.</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="simple"}</span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a><span class="fu">## What is Alchemize?</span></span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Alchemize</span><span class="co">](https://github.com/pymc-labs/alchemize)</span> is an LLM-based, self-correcting transpiler from PyMC Labs. It acts as an AI agent that compiles computational models between frameworks: PyMC, Stan, JAX, PyTorch, and Rust—with numerical validation at every step. The agent reasons about the full computational graph and applies optimizations a domain expert would: loop fusion, memory pre-allocation, cache-friendly access patterns.</span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a><span class="fu"># What Alchemize reveals!</span></span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>With the destination visible, we can rewind and follow the path that produced it—starting with what is missing.</span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>We begin with <span class="in">`SmolLM2-135M-Instruct-Q4_K_M.gguf`</span>, a roughly 105 MB GGUF file. Our first attempt is to ask <span class="co">[</span><span class="ot">Alchemize</span><span class="co">](https://github.com/pymc-labs/alchemize)</span> for a PyTensor implementation:</span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show Alchemize call"</span></span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> alchemize <span class="im">import</span> compile_model</span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> compile_model(</span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a>    model_path<span class="op">=</span>Path(<span class="st">"/path/to/SmolLM2-135M-Instruct-Q4_K_M.gguf"</span>),</span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a>    target<span class="op">=</span><span class="st">"pytensor"</span>,</span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a>Alchemize reads the GGUF metadata and generates a module with the right architecture skeleton. That is valuable: it gives us the tensor-name map, the block inventory, and the layer structure without writing any of it by hand.</span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a>But the generated implementation cannot run. Its central loading assumption is wrong:</span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show generated materialize_tensor"</span></span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> materialize_tensor(tensor):</span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> <span class="bu">getattr</span>(tensor, <span class="st">"data"</span>, <span class="va">None</span>)</span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a>    array <span class="op">=</span> np.asarray(data)</span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.issubdtype(array.dtype, np.floating):</span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.asarray(array, dtype<span class="op">=</span>np.float32)</span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">NotImplementedError</span>(<span class="st">"a dequantizer is required"</span>)</span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a>Most tensors in this GGUF are not floating arrays. They are packed quantized values. The generated implementation recognizes the problem and stops, but it never calls <span class="in">`gguf.dequantize`</span>.</span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a>The static audit therefore gives us:</span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Check <span class="pp">|</span> Result <span class="pp">|</span> Why <span class="pp">|</span></span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Provenance and syntax <span class="pp">|</span> pass <span class="pp">|</span> the artifact is pinned and valid Python <span class="pp">|</span></span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> GGUF dequantization <span class="pp">|</span> <span class="in">`STATIC_FAIL`</span> <span class="pp">|</span> packed weights are never dequantized <span class="pp">|</span></span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Attention head reshape <span class="pp">|</span> <span class="in">`STATIC_FAIL`</span> audit flag <span class="pp">|</span> symbolic reshapes do not preserve the repaired runtime's static contracts <span class="pp">|</span></span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Runtime <span class="pp">|</span> <span class="in">`BLOCKED`</span> <span class="pp">|</span> generated code is never executed <span class="pp">|</span></span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Semantics <span class="pp">|</span> <span class="in">`UNVERIFIED`</span> <span class="pp">|</span> valid syntax does not establish correct logits <span class="pp">|</span></span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a>This is not a failure. It is a map.</span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a>Alchemize accelerated architecture discovery and told us exactly what is missing. The generated code gives us the skeleton; the static audit tells us which contracts need hand-built replacements. We keep the tensor-name map and block inventory, then build the pieces that fill the gaps: materialization, orientation, graph construction, caching, execution, and validation.</span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a><span class="fu"># Building Gemma 3n inference in PyTensor</span></span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a>A correct answer depends on a chain of contracts: quantized weight dequantization, tensor orientation, tokenization, rotary embeddings, grouped-query attention, KV caching, and backend compilation. Break one contract and the model may still produce plausible text. So we build each contract explicitly and compose them into a working pipeline.</span>
<span id="cb11-131"><a href="#cb11-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-132"><a href="#cb11-132" aria-hidden="true" tabindex="-1"></a>Our target is Gemma 3n E4B—a much larger and stranger model than a typical first experiment. It adds four AltUp residual streams, a learned low-rank LAuReL path, per-layer token embeddings, sparse and dense activation variants, sliding and full attention, and a 262,400-token vocabulary. Can we express all of that in PyTensor's symbolic language without changing the framework?</span>
<span id="cb11-133"><a href="#cb11-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Component <span class="pp">|</span> E4B configuration <span class="pp">|</span></span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Decoder layers <span class="pp">|</span> 35 <span class="pp">|</span></span>
<span id="cb11-137"><a href="#cb11-137" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Hidden size <span class="pp">|</span> 2,048 <span class="pp">|</span></span>
<span id="cb11-138"><a href="#cb11-138" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Query / KV heads <span class="pp">|</span> 8 / 2 <span class="pp">|</span></span>
<span id="cb11-139"><a href="#cb11-139" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Head dimension <span class="pp">|</span> 256 <span class="pp">|</span></span>
<span id="cb11-140"><a href="#cb11-140" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> MLP width <span class="pp">|</span> 16,384 <span class="pp">|</span></span>
<span id="cb11-141"><a href="#cb11-141" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Vocabulary <span class="pp">|</span> 262,400 <span class="pp">|</span></span>
<span id="cb11-142"><a href="#cb11-142" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> AltUp streams <span class="pp">|</span> 4 <span class="pp">|</span></span>
<span id="cb11-143"><a href="#cb11-143" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LAuReL rank <span class="pp">|</span> 64 <span class="pp">|</span></span>
<span id="cb11-144"><a href="#cb11-144" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Sliding window <span class="pp">|</span> 512 <span class="pp">|</span></span>
<span id="cb11-145"><a href="#cb11-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Final logit softcap <span class="pp">|</span> 30 <span class="pp">|</span></span>
<span id="cb11-146"><a href="#cb11-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-147"><a href="#cb11-147" aria-hidden="true" tabindex="-1"></a>This case deliberately validates **multi-token, full-prefix generation**. It does not retain a KV cache between decoding steps. Instead, every step rebuilds the complete prefix, creates the model's shared-KV topology for that one forward, and discards it afterward.</span>
<span id="cb11-148"><a href="#cb11-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-149"><a href="#cb11-149" aria-hidden="true" tabindex="-1"></a><span class="fu">## Stream weights instead of expanding the model</span></span>
<span id="cb11-150"><a href="#cb11-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-151"><a href="#cb11-151" aria-hidden="true" tabindex="-1"></a>The 3.86 GB checkpoint stores each affine-4 linear module as packed <span class="in">`uint32`</span> weights plus BF16 scales and biases. Eight four-bit values occupy one word:</span>
<span id="cb11-152"><a href="#cb11-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-153"><a href="#cb11-153" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb11-154"><a href="#cb11-154" aria-hidden="true" tabindex="-1"></a>W_{r,c} = q_{r,c}s_{r,g(c)} + b_{r,g(c)}.</span>
<span id="cb11-155"><a href="#cb11-155" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb11-156"><a href="#cb11-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-157"><a href="#cb11-157" aria-hidden="true" tabindex="-1"></a>Here, $q_{r,c}$ is the stored nibble at output row $r$ and input column $c$; $s_{r,g(c)}$ and $b_{r,g(c)}$ are the scale and bias for its group.</span>
<span id="cb11-158"><a href="#cb11-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-159"><a href="#cb11-159" aria-hidden="true" tabindex="-1"></a>Fully expanding all logical parameters would need about **25.6 GiB** for FP32 weights alone. We instead:</span>
<span id="cb11-160"><a href="#cb11-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-161"><a href="#cb11-161" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>load only requested embedding rows,</span>
<span id="cb11-162"><a href="#cb11-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>dequantize one decoder layer at a time,</span>
<span id="cb11-163"><a href="#cb11-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>release it before loading the next layer, and</span>
<span id="cb11-164"><a href="#cb11-164" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>project vocabulary logits in chunks of 4,096 rows.</span>
<span id="cb11-165"><a href="#cb11-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-168"><a href="#cb11-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-169"><a href="#cb11-169" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-170"><a href="#cb11-170" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show weight streaming"</span></span>
<span id="cb11-171"><a href="#cb11-171" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor.weights <span class="im">import</span> Gemma3nWeightLoader</span>
<span id="cb11-172"><a href="#cb11-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-173"><a href="#cb11-173" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> Gemma3nWeightLoader.from_snapshot(snapshot_path) <span class="im">as</span> loader:</span>
<span id="cb11-174"><a href="#cb11-174" aria-hidden="true" tabindex="-1"></a>    token_rows <span class="op">=</span> loader.load_input_embedding_rows(token_ids)</span>
<span id="cb11-175"><a href="#cb11-175" aria-hidden="true" tabindex="-1"></a>    layer_0 <span class="op">=</span> loader.load_layer(<span class="dv">0</span>)</span>
<span id="cb11-176"><a href="#cb11-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-177"><a href="#cb11-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-178"><a href="#cb11-178" aria-hidden="true" tabindex="-1"></a>Streaming changes the problem from “hold the expanded model” to “hold the current expanded layer.”</span>
<span id="cb11-179"><a href="#cb11-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-180"><a href="#cb11-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## Write the equations once</span></span>
<span id="cb11-181"><a href="#cb11-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-182"><a href="#cb11-182" aria-hidden="true" tabindex="-1"></a>The shared normalization is ordinary PyTensor:</span>
<span id="cb11-183"><a href="#cb11-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-186"><a href="#cb11-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-187"><a href="#cb11-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-188"><a href="#cb11-188" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show rmsnorm_symbolic"</span></span>
<span id="cb11-189"><a href="#cb11-189" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor.ops <span class="im">import</span> rmsnorm_symbolic</span>
<span id="cb11-190"><a href="#cb11-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-191"><a href="#cb11-191" aria-hidden="true" tabindex="-1"></a>normalized <span class="op">=</span> rmsnorm_symbolic(hidden, gamma, eps<span class="op">=</span><span class="fl">1e-6</span>)</span>
<span id="cb11-192"><a href="#cb11-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-193"><a href="#cb11-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-194"><a href="#cb11-194" aria-hidden="true" tabindex="-1"></a>The important detail is not the formula. It is that <span class="in">`rmsnorm_symbolic`</span> knows nothing about C, Numba, or MLX.</span>
<span id="cb11-195"><a href="#cb11-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-196"><a href="#cb11-196" aria-hidden="true" tabindex="-1"></a>The same is true for grouped-query attention, RoPE, masks, AltUp, and LAuReL. Gemma's sparse and dense GELU paths produce two specialized <span class="in">`FunctionGraph`</span>s; full versus sliding attention arrives as mask and RoPE data. The operation order follows the pinned MLX-LM implementation—including LAuReL's apparent repeated residual and the sparse GELU sparsity pattern read from the checkpoint.</span>
<span id="cb11-197"><a href="#cb11-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-198"><a href="#cb11-198" aria-hidden="true" tabindex="-1"></a><span class="fu">## Choose the backend at compilation</span></span>
<span id="cb11-199"><a href="#cb11-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-200"><a href="#cb11-200" aria-hidden="true" tabindex="-1"></a>Backend selection is now a small, reusable utility:</span>
<span id="cb11-201"><a href="#cb11-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-204"><a href="#cb11-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-205"><a href="#cb11-205" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-206"><a href="#cb11-206" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show backend selection"</span></span>
<span id="cb11-207"><a href="#cb11-207" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor.backends <span class="im">import</span> get_mode</span>
<span id="cb11-208"><a href="#cb11-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-209"><a href="#cb11-209" aria-hidden="true" tabindex="-1"></a>c_mode <span class="op">=</span> get_mode(<span class="st">"c"</span>)</span>
<span id="cb11-210"><a href="#cb11-210" aria-hidden="true" tabindex="-1"></a>numba_mode <span class="op">=</span> get_mode(<span class="st">"numba"</span>)</span>
<span id="cb11-211"><a href="#cb11-211" aria-hidden="true" tabindex="-1"></a>mlx_mode <span class="op">=</span> get_mode(<span class="st">"mlx"</span>)</span>
<span id="cb11-212"><a href="#cb11-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-213"><a href="#cb11-213" aria-hidden="true" tabindex="-1"></a>c_layer <span class="op">=</span> pytensor.function(layer_inputs, layer_output, mode<span class="op">=</span>c_mode)</span>
<span id="cb11-214"><a href="#cb11-214" aria-hidden="true" tabindex="-1"></a>numba_layer <span class="op">=</span> pytensor.function(layer_inputs, layer_output, mode<span class="op">=</span>numba_mode)</span>
<span id="cb11-215"><a href="#cb11-215" aria-hidden="true" tabindex="-1"></a>mlx_layer <span class="op">=</span> pytensor.function(layer_inputs, layer_output, mode<span class="op">=</span>mlx_mode)</span>
<span id="cb11-216"><a href="#cb11-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-217"><a href="#cb11-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-218"><a href="#cb11-218" aria-hidden="true" tabindex="-1"></a>The model definition did not change. Only the linker and rewrite policy changed.</span>
<span id="cb11-219"><a href="#cb11-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-220"><a href="#cb11-220" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip appearance="simple"}</span>
<span id="cb11-221"><a href="#cb11-221" aria-hidden="true" tabindex="-1"></a><span class="fu">## One model, multiple compiler experiments</span></span>
<span id="cb11-222"><a href="#cb11-222" aria-hidden="true" tabindex="-1"></a>If we change a symbolic equation, every backend inherits it. If we change only a rewrite or linker, the model remains fixed. That separation is PyTensor's main contribution to this experiment.</span>
<span id="cb11-223"><a href="#cb11-223" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-224"><a href="#cb11-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-225"><a href="#cb11-225" aria-hidden="true" tabindex="-1"></a><span class="fu">## Run Gemma inference from Python</span></span>
<span id="cb11-226"><a href="#cb11-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-227"><a href="#cb11-227" aria-hidden="true" tabindex="-1"></a>The same public entry point now targets a different artifact and backend:</span>
<span id="cb11-228"><a href="#cb11-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-231"><a href="#cb11-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-232"><a href="#cb11-232" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb11-233"><a href="#cb11-233" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb11-234"><a href="#cb11-234" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cetagostini.utils.pytensor <span class="im">import</span> Gemma3n, inference</span>
<span id="cb11-235"><a href="#cb11-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-236"><a href="#cb11-236" aria-hidden="true" tabindex="-1"></a>gemma <span class="op">=</span> Gemma3n.from_snapshot(</span>
<span id="cb11-237"><a href="#cb11-237" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"/path/to/gemma-3n-E4B-it-lm-4bit/snapshot"</span>),</span>
<span id="cb11-238"><a href="#cb11-238" aria-hidden="true" tabindex="-1"></a>    backend<span class="op">=</span><span class="st">"c"</span>,</span>
<span id="cb11-239"><a href="#cb11-239" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-240"><a href="#cb11-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-241"><a href="#cb11-241" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> inference(</span>
<span id="cb11-242"><a href="#cb11-242" aria-hidden="true" tabindex="-1"></a>    gemma,</span>
<span id="cb11-243"><a href="#cb11-243" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span><span class="op">=</span><span class="st">"What's causal inference?"</span>,</span>
<span id="cb11-244"><a href="#cb11-244" aria-hidden="true" tabindex="-1"></a>    max_tokens<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb11-245"><a href="#cb11-245" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-246"><a href="#cb11-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-247"><a href="#cb11-247" aria-hidden="true" tabindex="-1"></a>result.output, result.output_token_ids</span>
<span id="cb11-248"><a href="#cb11-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-249"><a href="#cb11-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-250"><a href="#cb11-250" aria-hidden="true" tabindex="-1"></a><span class="in">```text</span></span>
<span id="cb11-251"><a href="#cb11-251" aria-hidden="true" tabindex="-1"></a><span class="in">('## Causal Inference: Understanding "Why" vs. "Correlation"\n\n'</span></span>
<span id="cb11-252"><a href="#cb11-252" aria-hidden="true" tabindex="-1"></a><span class="in"> 'Causal inference is a branch of statistics and statistics is a field '</span></span>
<span id="cb11-253"><a href="#cb11-253" aria-hidden="true" tabindex="-1"></a><span class="in"> 'of statistics that aims',</span></span>
<span id="cb11-254"><a href="#cb11-254" aria-hidden="true" tabindex="-1"></a><span class="in"> (1408, 565, 90718, 157036, 236787, 40411, 623, 11355, 236775,</span></span>
<span id="cb11-255"><a href="#cb11-255" aria-hidden="true" tabindex="-1"></a><span class="in">  7728, 236761, 623, 131426, 236775, 108, 236780, 90718, 34711,</span></span>
<span id="cb11-256"><a href="#cb11-256" aria-hidden="true" tabindex="-1"></a><span class="in">  563, 496, 9911, 529, 14906, 532, 14906, 563, 496, 2135,</span></span>
<span id="cb11-257"><a href="#cb11-257" aria-hidden="true" tabindex="-1"></a><span class="in">  529, 14906, 600, 17269))</span></span>
<span id="cb11-258"><a href="#cb11-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-259"><a href="#cb11-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-260"><a href="#cb11-260" aria-hidden="true" tabindex="-1"></a>That is an actual continuation, not one next-token prediction. It is also not polished prose: greedy decoding reaches the 32-token cap mid-sentence and becomes repetitive after the differential path separates. The point is to make generation inspectable, not to present a language-quality benchmark.</span>
<span id="cb11-261"><a href="#cb11-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-264"><a href="#cb11-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-265"><a href="#cb11-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-266"><a href="#cb11-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show validation report"</span></span>
<span id="cb11-267"><a href="#cb11-267" aria-hidden="true" tabindex="-1"></a>result.report.validation</span>
<span id="cb11-268"><a href="#cb11-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-269"><a href="#cb11-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-270"><a href="#cb11-270" aria-hidden="true" tabindex="-1"></a><span class="in">```text</span></span>
<span id="cb11-271"><a href="#cb11-271" aria-hidden="true" tabindex="-1"></a><span class="in">{</span></span>
<span id="cb11-272"><a href="#cb11-272" aria-hidden="true" tabindex="-1"></a><span class="in">    'final_top1_match': True,</span></span>
<span id="cb11-273"><a href="#cb11-273" aria-hidden="true" tabindex="-1"></a><span class="in">    'all_top1_match': False,</span></span>
<span id="cb11-274"><a href="#cb11-274" aria-hidden="true" tabindex="-1"></a><span class="in">    'pearson_mean': 0.998932415848074,</span></span>
<span id="cb11-275"><a href="#cb11-275" aria-hidden="true" tabindex="-1"></a><span class="in">    'top10_overlap_mean': 9.533333333333333,</span></span>
<span id="cb11-276"><a href="#cb11-276" aria-hidden="true" tabindex="-1"></a><span class="in">    'thresholds_passed': True,</span></span>
<span id="cb11-277"><a href="#cb11-277" aria-hidden="true" tabindex="-1"></a><span class="in">    'scope': 'all_generated_prefixes_fresh_cache',</span></span>
<span id="cb11-278"><a href="#cb11-278" aria-hidden="true" tabindex="-1"></a><span class="in">    'all_generated_tokens_match': False,</span></span>
<span id="cb11-279"><a href="#cb11-279" aria-hidden="true" tabindex="-1"></a><span class="in">}</span></span>
<span id="cb11-280"><a href="#cb11-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-281"><a href="#cb11-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-282"><a href="#cb11-282" aria-hidden="true" tabindex="-1"></a>The initial 15-token prompt passes the publication thresholds and selects the same next token in PyTensor and MLX-LM. Generation then validates each growing PyTensor prefix against an MLX-LM forward over that exact prefix. Each oracle call creates a fresh shared-KV object and discards it; no decode state survives into the next step.</span>
<span id="cb11-283"><a href="#cb11-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-284"><a href="#cb11-284" aria-hidden="true" tabindex="-1"></a>The first 20 generated decisions agree. At token 21, PyTensor chooses <span class="in">`9911`</span> while the fresh-prefix MLX oracle chooses <span class="in">`2135`</span>. The report records that divergence and keeps evaluating MLX on the subsequent **PyTensor prefix**, so later comparisons remain well-defined. It does not compare two independently drifting streams, and it no longer throws away an expensive completed generation because cached <span class="in">`stream_generate`</span> follows a different path.</span>
<span id="cb11-285"><a href="#cb11-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-286"><a href="#cb11-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Multi-token result <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb11-287"><a href="#cb11-287" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb11-288"><a href="#cb11-288" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Visible tokens <span class="pp">|</span> 32 <span class="pp">|</span></span>
<span id="cb11-289"><a href="#cb11-289" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Matching fresh-prefix decisions <span class="pp">|</span> 31 / 32 <span class="pp">|</span></span>
<span id="cb11-290"><a href="#cb11-290" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> First divergence <span class="pp">|</span> token 21 <span class="pp">|</span></span>
<span id="cb11-291"><a href="#cb11-291" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Prefix graph compilations <span class="pp">|</span> 32 <span class="pp">|</span></span>
<span id="cb11-292"><a href="#cb11-292" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Additional generation wall time <span class="pp">|</span> 1,612.038 s <span class="pp">|</span></span>
<span id="cb11-293"><a href="#cb11-293" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Peak process RSS <span class="pp">|</span> 9,668.61 MiB <span class="pp">|</span></span>
<span id="cb11-294"><a href="#cb11-294" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Stop reason <span class="pp">|</span> <span class="in">`max_tokens`</span> <span class="pp">|</span></span>
<span id="cb11-295"><a href="#cb11-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-296"><a href="#cb11-296" aria-hidden="true" tabindex="-1"></a>The cost is the lesson. After the initial validated prompt pass, the remaining full-prefix generation loop took **1,612.038 seconds**, or about **26.9 minutes**. This is an educational execution strategy that exposes every graph and comparison; it is not an efficient decoder.</span>
<span id="cb11-297"><a href="#cb11-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-298"><a href="#cb11-298" aria-hidden="true" tabindex="-1"></a><span class="fu">### C/CVM vs Numba vs MLX: performance comparison</span></span>
<span id="cb11-299"><a href="#cb11-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-300"><a href="#cb11-300" aria-hidden="true" tabindex="-1"></a>All three backends compile the same symbolic equations and select the same top-1 token as the independent MLX-LM oracle at all 20 prompt positions. Their mean all-logit Pearson correlation with the oracle is 0.9986, and their mean top-10 overlap is 9.7 out of 10.</span>
<span id="cb11-301"><a href="#cb11-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-302"><a href="#cb11-302" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> C/CVM <span class="pp">|</span> Numba <span class="pp">|</span> MLX <span class="pp">|</span></span>
<span id="cb11-303"><a href="#cb11-303" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb11-304"><a href="#cb11-304" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Graph compilation <span class="pp">|</span> 7.738 s <span class="pp">|</span> 0.775 s <span class="pp">|</span> **0.755 s** <span class="pp">|</span></span>
<span id="cb11-305"><a href="#cb11-305" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> One full forward (20 positions) <span class="pp">|</span> 51.441 s <span class="pp">|</span> 53.800 s <span class="pp">|</span> **50.211 s** <span class="pp">|</span></span>
<span id="cb11-306"><a href="#cb11-306" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mean per-layer time <span class="pp">|</span> 1.272 s <span class="pp">|</span> 1.266 s <span class="pp">|</span> **1.246 s** <span class="pp">|</span></span>
<span id="cb11-307"><a href="#cb11-307" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Logit projection <span class="pp">|</span> **3.024 s** <span class="pp">|</span> 4.700 s <span class="pp">|</span> 3.086 s <span class="pp">|</span></span>
<span id="cb11-308"><a href="#cb11-308" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Whole-process peak RSS <span class="pp">|</span> **4,523 MiB** <span class="pp">|</span> 4,663 MiB <span class="pp">|</span> 5,111 MiB <span class="pp">|</span></span>
<span id="cb11-309"><a href="#cb11-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-310"><a href="#cb11-310" aria-hidden="true" tabindex="-1"></a>These are single-run measurements of an intentionally streamed educational pipeline, not a throughput benchmark. MLX compiles about 10 times faster than C and records the shortest forward, but only by 2.4%. C still wins the 262,400-vocabulary projection. Weight dequantization, Python orchestration, and per-layer streaming dominate enough that the three full forwards remain in the same range.</span>
<span id="cb11-311"><a href="#cb11-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-312"><a href="#cb11-312" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="simple"}</span>
<span id="cb11-313"><a href="#cb11-313" aria-hidden="true" tabindex="-1"></a><span class="fu">## How the failed MLX probe became a working backend</span></span>
<span id="cb11-314"><a href="#cb11-314" aria-hidden="true" tabindex="-1"></a>The first MLX probe failed because the generated draft relied on shapes and operations that the pinned linker could not lower safely. We did not patch the installed PyTensor package or mutate a process-global dispatch registry. Instead, we expressed projections as rank-2 matrix multiplies with explicit reshapes, kept attention in ordinary tensor primitives, and replaced Gemma's AltUp clip sites with a repository-local symbolic helper built from comparisons and <span class="in">`where`</span>.</span>
<span id="cb11-315"><a href="#cb11-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-316"><a href="#cb11-316" aria-hidden="true" tabindex="-1"></a>The resulting graph compiles through PyTensor 3.1.2's built-in <span class="in">`pytensor.compile.mode.MLX`</span>. MLX evaluates lazily, so the runner materializes 103 ordered boundaries: two initial projections, 35 decoder layers, one final unembed, and 65 vocabulary chunks. Intermediate tensors remain device-resident; only completed logit chunks cross back to owning NumPy arrays. The measured MLX allocator peak was 455 MiB beyond its near-zero baseline, while whole-process RSS reached 5,111 MiB.</span>
<span id="cb11-317"><a href="#cb11-317" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-318"><a href="#cb11-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-319"><a href="#cb11-319" aria-hidden="true" tabindex="-1"></a>The complete reports are available for the independent <span class="co">[</span><span class="ot">MLX-LM oracle</span><span class="co">](results/gemma3n_mlx_lm_oracle.json)</span>, <span class="co">[</span><span class="ot">C/CVM</span><span class="co">](results/gemma3n_pytensor_c.json)</span>, <span class="co">[</span><span class="ot">Numba</span><span class="co">](results/gemma3n_pytensor_numba.json)</span>, and <span class="co">[</span><span class="ot">MLX</span><span class="co">](results/gemma3n_pytensor_mlx.json)</span>. A separate validator reloaded the temporary raw logits, recomputed every metric instead of trusting the reports, and passed <span class="co">[</span><span class="ot">896 of 896 gates</span><span class="co">](results/gemma3n_report_validation.json)</span>. The large raw arrays are not committed; the reports preserve their shapes, dtypes, byte counts, and cryptographic hashes. The earlier 32-token generation run remains in <span class="co">[</span><span class="ot">`gemma3n_pytensor_generation.json`</span><span class="co">](results/gemma3n_pytensor_generation.json)</span>.</span>
<span id="cb11-320"><a href="#cb11-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-321"><a href="#cb11-321" aria-hidden="true" tabindex="-1"></a><span class="fu"># What the current speed tells us</span></span>
<span id="cb11-322"><a href="#cb11-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-323"><a href="#cb11-323" aria-hidden="true" tabindex="-1"></a>The numbers above are not benchmarks. They are measurements of an educational pipeline, and they should be read that way. But they are honest, and they tell us something precise about where the engineering effort needs to go.</span>
<span id="cb11-324"><a href="#cb11-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-325"><a href="#cb11-325" aria-hidden="true" tabindex="-1"></a>Gemma 3n through full-prefix regeneration runs at roughly **0.02 tokens per second**. That is the cost of recompiling and re-evaluating the entire prefix for every generated token. It is deliberately expensive—it validates correctness—but it is not how a production system would work.</span>
<span id="cb11-326"><a href="#cb11-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-327"><a href="#cb11-327" aria-hidden="true" tabindex="-1"></a>The engineering roadmap from here is clear:</span>
<span id="cb11-328"><a href="#cb11-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-329"><a href="#cb11-329" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bottleneck <span class="pp">|</span> Current state <span class="pp">|</span> What unlocks it <span class="pp">|</span></span>
<span id="cb11-330"><a href="#cb11-330" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb11-331"><a href="#cb11-331" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> KV cache <span class="pp">|</span> fixed-capacity, O(C) write per layer <span class="pp">|</span> paged or ring-buffer cache, continuous batching <span class="pp">|</span></span>
<span id="cb11-332"><a href="#cb11-332" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Weight loading <span class="pp">|</span> per-layer streaming (dequantize on demand) <span class="pp">|</span> mmap zero-copy, quantized kernels <span class="pp">|</span></span>
<span id="cb11-333"><a href="#cb11-333" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Backend execution <span class="pp">|</span> C/CVM, Numba, and MLX on Apple Silicon <span class="pp">|</span> backend-native quantized kernels and less host-device movement <span class="pp">|</span></span>
<span id="cb11-334"><a href="#cb11-334" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Graph compilation <span class="pp">|</span> recompilation per prefix length <span class="pp">|</span> cached compiled functions per shape, or JIT <span class="pp">|</span></span>
<span id="cb11-335"><a href="#cb11-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-336"><a href="#cb11-336" aria-hidden="true" tabindex="-1"></a><span class="in">`llama.cpp`</span> has spent years on every row of that table. PyTensor has the graph compiler and the multi-backend architecture; it does not yet have the serving infrastructure. The question is not whether PyTensor can match <span class="in">`llama.cpp`</span>'s throughput today—it cannot—but whether the pieces are in place to build that infrastructure in Python. The answer, after this experiment, is yes.</span>
<span id="cb11-337"><a href="#cb11-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-338"><a href="#cb11-338" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip appearance="simple"}</span>
<span id="cb11-339"><a href="#cb11-339" aria-hidden="true" tabindex="-1"></a><span class="fu">## The composability advantage</span></span>
<span id="cb11-340"><a href="#cb11-340" aria-hidden="true" tabindex="-1"></a><span class="in">`llama.cpp`</span> is a self-contained inference engine. PyTensor is a graph compiler that can compose with JAX transformations, NumPy operations, SciPy optimizers, and the rest of the scientific Python stack. The moment LLM inference lives inside that ecosystem, you can chain it with Bayesian analysis, gradient-based optimization, or custom symbolic computation—workflows that a standalone C++ engine was never designed to support.</span>
<span id="cb11-341"><a href="#cb11-341" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-342"><a href="#cb11-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-343"><a href="#cb11-343" aria-hidden="true" tabindex="-1"></a><span class="fu"># Where PyTensor and llama.cpp differ — and why that matters</span></span>
<span id="cb11-344"><a href="#cb11-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-345"><a href="#cb11-345" aria-hidden="true" tabindex="-1"></a>Now we can make the comparison precise:</span>
<span id="cb11-346"><a href="#cb11-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-347"><a href="#cb11-347" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Capability <span class="pp">|</span> This PyTensor stack <span class="pp">|</span> <span class="in">`llama.cpp`</span> <span class="pp">|</span></span>
<span id="cb11-348"><a href="#cb11-348" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb11-349"><a href="#cb11-349" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Inspectable symbolic graph <span class="pp">|</span> yes <span class="pp">|</span> not its primary user abstraction <span class="pp">|</span></span>
<span id="cb11-350"><a href="#cb11-350" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> User-defined graph rewrites <span class="pp">|</span> yes <span class="pp">|</span> no equivalent Python rewrite database <span class="pp">|</span></span>
<span id="cb11-351"><a href="#cb11-351" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C, Numba, and MLX experiments <span class="pp">|</span> demonstrated on Gemma 3n E4B <span class="pp">|</span> purpose-built CPU, Metal, CUDA, and other backends <span class="pp">|</span></span>
<span id="cb11-352"><a href="#cb11-352" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> GGUF parsing <span class="pp">|</span> supplied by <span class="in">`gguf-py`</span> adapter <span class="pp">|</span> built in <span class="pp">|</span></span>
<span id="cb11-353"><a href="#cb11-353" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Native quantized matmul <span class="pp">|</span> not implemented here <span class="pp">|</span> built in <span class="pp">|</span></span>
<span id="cb11-354"><a href="#cb11-354" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tokenization and chat templates <span class="pp">|</span> Python adapters <span class="pp">|</span> built in <span class="pp">|</span></span>
<span id="cb11-355"><a href="#cb11-355" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Autoregressive loop <span class="pp">|</span> Python, model-specific <span class="pp">|</span> built in <span class="pp">|</span></span>
<span id="cb11-356"><a href="#cb11-356" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Production KV cache and batching <span class="pp">|</span> no <span class="pp">|</span> built in <span class="pp">|</span></span>
<span id="cb11-357"><a href="#cb11-357" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Broad architecture support <span class="pp">|</span> one validated fixture (Gemma 3n) <span class="pp">|</span> broad, maintained model coverage <span class="pp">|</span></span>
<span id="cb11-358"><a href="#cb11-358" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Composability with scientific Python <span class="pp">|</span> native <span class="pp">|</span> not designed for it <span class="pp">|</span></span>
<span id="cb11-359"><a href="#cb11-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-360"><a href="#cb11-360" aria-hidden="true" tabindex="-1"></a><span class="in">`llama.cpp`</span> wins on integrated inference engineering. That is exactly what it is built for.</span>
<span id="cb11-361"><a href="#cb11-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-362"><a href="#cb11-362" aria-hidden="true" tabindex="-1"></a>But the local LLM ecosystem is not just about running one model fast. It is about what you do with the model afterward.</span>
<span id="cb11-363"><a href="#cb11-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-364"><a href="#cb11-364" aria-hidden="true" tabindex="-1"></a>The recent history of Ollama—<span class="co">[</span><span class="ot">documented thoroughly by sleepingrobots</span><span class="co">](https://sleepingrobots.com/dreams/stop-using-ollama/)</span>—shows what happens when a wrapper obscures its dependencies and pivots to cloud. The ecosystem needs alternatives built on honest, transparent foundations. PyTensor and <span class="in">`llama.cpp`</span> are those foundations.</span>
<span id="cb11-365"><a href="#cb11-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-366"><a href="#cb11-366" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`llama.cpp`** is the C++ engine for running any GGUF model fast. It owns the full serving stack: quantized kernels, KV cache management, continuous batching, broad architecture support. If you need to serve models at production scale today, <span class="in">`llama.cpp`</span> is the answer.</span>
<span id="cb11-367"><a href="#cb11-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**PyTensor** is the Python-native graph compiler for studying, modifying, and composing LLM inference. You do not just run a model—you can ask what a rewrite changed, compile the same equations through another linker, chain inference with a Bayesian posterior or a custom optimization loop, and validate every contract numerically.</span>
<span id="cb11-368"><a href="#cb11-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-369"><a href="#cb11-369" aria-hidden="true" tabindex="-1"></a>The honest claim is not "PyTensor replaces <span class="in">`llama.cpp`</span>". It is this:</span>
<span id="cb11-370"><a href="#cb11-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-371"><a href="#cb11-371" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">PyTensor</span><span class="co">]</span>{style="color:var(--green-strong)"} plus explicit Python adapters is a credible *Python-native alternative* to `llama.cpp` that **composes with the scientific computing stack**—Bayesian analysis, optimization, custom computation graphs—in ways a standalone C++ engine was never designed for.</span>
<span id="cb11-372"><a href="#cb11-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-373"><a href="#cb11-373" aria-hidden="true" tabindex="-1"></a>If someone builds KV caching, mmap zero-copy loading, and continuous batching on PyTensor's JAX backend, and <span class="co">[</span><span class="ot">Alchemize</span><span class="co">](https://github.com/pymc-labs/alchemize)</span> matures for auto-generating new architectures from GGUF metadata, we could see PyTensor become the "language" for running multiple LLMs the way <span class="in">`llama.cpp`</span> is today. Not faster at inference—or maybe at some point—but more capable as a general-purpose LLM runtime that plugs into workflows <span class="in">`llama.cpp`</span> was never built for.</span>
<span id="cb11-374"><a href="#cb11-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-375"><a href="#cb11-375" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusions</span></span>
<span id="cb11-376"><a href="#cb11-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-377"><a href="#cb11-377" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**PyTensor is a general graph compiler.** PyMC is its most visible consumer, not the boundary of what it can express.</span>
<span id="cb11-378"><a href="#cb11-378" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Building LLM inference in PyTensor is straightforward.** Weight loaders, symbolic transformers, KV caches, generation loops, and numerical validation—all assembled from Python without modifying the framework.</span>
<span id="cb11-379"><a href="#cb11-379" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**One symbolic definition survives multiple backends.** Gemma 3n executes through C/CVM, Numba, and MLX without a second model implementation.</span>
<span id="cb11-380"><a href="#cb11-380" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Independent logits beat plausible prose.** Exact tokens and all-position numerical agreement are stronger evidence than plausible-looking text.</span>
<span id="cb11-381"><a href="#cb11-381" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**PyTensor and `llama.cpp` are complementary.** <span class="in">`llama.cpp`</span> owns production serving. PyTensor owns graph transparency and composability with scientific Python.</span>
<span id="cb11-382"><a href="#cb11-382" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**The remaining gaps are engineering, not architecture.** Native quantized kernels, paged KV caching, mmap zero-copy loading, and broader backend coverage are all buildable on PyTensor's existing foundation. The pytensor-ml project has already begun this work.</span>
<span id="cb11-383"><a href="#cb11-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-384"><a href="#cb11-384" aria-hidden="true" tabindex="-1"></a>Recommended readings:</span>
<span id="cb11-385"><a href="#cb11-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-386"><a href="#cb11-386" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span><span class="co">[</span><span class="ot">PyTensor documentation</span><span class="co">](https://pytensor.readthedocs.io/)</span></span>
<span id="cb11-387"><a href="#cb11-387" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span><span class="co">[</span><span class="ot">PyTensor graph rewriting</span><span class="co">](https://pytensor.readthedocs.io/en/latest/extending/graph_rewriting.html)</span></span>
<span id="cb11-388"><a href="#cb11-388" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span><span class="co">[</span><span class="ot">PyTensor compilation modes</span><span class="co">](https://pytensor.readthedocs.io/en/latest/library/compile/mode.html)</span></span>
<span id="cb11-389"><a href="#cb11-389" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span><span class="co">[</span><span class="ot">llama.cpp</span><span class="co">](https://github.com/ggml-org/llama.cpp)</span></span>
<span id="cb11-390"><a href="#cb11-390" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span><span class="co">[</span><span class="ot">MLX-LM</span><span class="co">](https://github.com/ml-explore/mlx-lm)</span></span>
<span id="cb11-391"><a href="#cb11-391" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span><span class="co">[</span><span class="ot">Alchemize</span><span class="co">](https://github.com/pymc-labs/alchemize)</span></span>
<span id="cb11-392"><a href="#cb11-392" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span><span class="co">[</span><span class="ot">pytensor-ml</span><span class="co">](https://github.com/pymc-labs/pytensor-ml)</span></span>
<span id="cb11-393"><a href="#cb11-393" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span><span class="co">[</span><span class="ot">Friends Don't Let Friends Use Ollama</span><span class="co">](https://sleepingrobots.com/dreams/stop-using-ollama/)</span></span>
<span id="cb11-394"><a href="#cb11-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-395"><a href="#cb11-395" aria-hidden="true" tabindex="-1"></a>The recorded experiment used:</span>
<span id="cb11-396"><a href="#cb11-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-397"><a href="#cb11-397" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Component <span class="pp">|</span> Version or pin <span class="pp">|</span></span>
<span id="cb11-398"><a href="#cb11-398" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb11-399"><a href="#cb11-399" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Python <span class="pp">|</span> <span class="in">`3.13.14`</span> <span class="pp">|</span></span>
<span id="cb11-400"><a href="#cb11-400" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PyTensor <span class="pp">|</span> <span class="in">`3.1.2`</span> <span class="pp">|</span></span>
<span id="cb11-401"><a href="#cb11-401" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PyTensor-ML <span class="pp">|</span> <span class="in">`f6ecf81d58da180cce50b77a43cf5d2c3d95e470`</span> <span class="pp">|</span></span>
<span id="cb11-402"><a href="#cb11-402" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> MLX <span class="pp">|</span> <span class="in">`0.32.0`</span> <span class="pp">|</span></span>
<span id="cb11-403"><a href="#cb11-403" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Numba <span class="pp">|</span> <span class="in">`0.65.1`</span> <span class="pp">|</span></span>
<span id="cb11-404"><a href="#cb11-404" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> MLX-LM <span class="pp">|</span> <span class="in">`0.31.3`</span> <span class="pp">|</span></span>
<span id="cb11-405"><a href="#cb11-405" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Machine <span class="pp">|</span> Apple M3 Max, 128 GB unified memory <span class="pp">|</span></span>
<span id="cb11-406"><a href="#cb11-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-407"><a href="#cb11-407" aria-hidden="true" tabindex="-1"></a>The exact environment is recorded in <span class="co">[</span><span class="ot">`environment.yml`</span><span class="co">](environment.yml)</span>. Code cells are not executed during the website build because the model artifacts are intentionally excluded from Git; the committed JSON reports preserve the artifact hashes and measured outputs. The PyTensor suite passed 934 tests with 30 skips, and the gated real-model runner tests passed all 189 checks; the compact record is in <span class="co">[</span><span class="ot">`gemma3n_test_summary.json`</span><span class="co">](results/gemma3n_test_summary.json)</span>.</span>
<span id="cb11-408"><a href="#cb11-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-409"><a href="#cb11-409" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb11-410"><a href="#cb11-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-411"><a href="#cb11-411" aria-hidden="true" tabindex="-1"></a>The public package, model-specific implementations, tests, generated draft, audits, and sanitized result reports are available in the <span class="co">[</span><span class="ot">site repository</span><span class="co">](https://github.com/cetagostini/cetagostini.github.io)</span>.</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Connect with me:
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 © 2026 Carlos Trujillo
  </li>  
</ul>
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/cetagostini/cetagostini.github.io/edit/main/articles/alchemize_pytensor_mlx_gemma_3n/alchemize_pytensor_mlx_gemma_3n.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cetagostini/cetagostini.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/cetagostini">
      <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/cetagostini">
      <i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/cetagostini">
      <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://instagram.com/cetagostini">
      <i class="bi bi-instagram" role="img" aria-label="Instagram">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:carlos.trujillo.agostini@gmail.com">
      <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script src="../../js/cookie-consent.js"></script>




</body></html>