{
  "hash": "640f3a4fc7da5adba0c5c8cb6d3e9912",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Can You Trust Your Quasi-Experiment? A Bayesian Framework for Auditing Time-Series Causal Estimates\"\ndate: \"2026-04-07\"\nauthor:\n    - name: Carlos Trujillo\n    - name: Anton Bugaev\ncategories: [python, experimentation, quasi-experiments, bayesian, pymc]\nimage: \"../images/placebo_bayesian_quasi_experiments.png\"\njupyter: cetagostini_web\nformat:\n  html:\n    code-fold: true\n    code-tools: true\n    code-overflow: wrap\n---\n\n\n\n::: {.callout-tip}\n## The Five-Step Recipe\n\n1. **Choose your estimator** and define the intervention window length.\n2. **Run placebo tests** on $J$ historical windows where no treatment occurred.\n3. **Pool the placebo residuals** into a hierarchical null model to learn the structural volatility.\n4. **Specify your minimum detectable effect** (ROPE — the band around zero you'd call \"practically no effect\") and expected lift (alternative hypothesis). We'll formalize this concept in the Decision Rules section below.\n5. **Simulate operating characteristics.** If assurance is too low or FPR too high, improve the model or reconsider the experiment.\n\nEach step is explained below and demonstrated on the Wendy's case study.\n:::\n\n## Introduction\n\nIn September 2024, Wendy's launched the \"[Krabby Patty Kollab](https://secretatlanta.co/krabby-patties-atlanta/)\", a limited-time partnership with Nickelodeon's SpongeBob SquarePants that generated massive buzz across social media and news outlets. Suppose the Wendy's analytics team wanted to measure the campaign's impact on brand search interest using Google Trends data. They can't randomize who sees a viral fast-food collaboration, so they turn to a quasi-experimental design: Synthetic Control, using other fast-food chains as untreated references.\n\nThe model runs. It reports a cumulative lift of +14.5 Google Trends index points over the campaign month, with a tight 95% credible interval of [12.3, 16.6]. Should they trust this number?\n\nThe honest answer is: *it depends on the structural reliability of the estimator in this specific data environment.* That tight credible interval captures inherent time-series noise (what statisticians call *aleatoric uncertainty*) and parameter uncertainty (*epistemic uncertainty*), but only conditional on the model's identifying assumptions holding exactly. It says nothing about whether the model itself is trustworthy. When the identifying assumptions are violated — due to seasonal drift, competitor activity, or weak correlations between Wendy's and the control brands — the counterfactual prediction deviates from the true unobserved outcome. We call this deviation the **structural error**, and the broader epistemic uncertainty it reflects **structural uncertainty**. This is what standard quasi-experimental software ignores.\n\nThis paper presents a framework that quantifies both. By running the same estimator on historical periods where no campaign occurred (placebo tests), pooling those \"false alarms\" into a hierarchical model, and simulating decision outcomes, we produce a calibrated answer: *\"This design has a 40.8% structural false positive rate and 90.1% probability of detecting effects in the expected range.\"*\n\nThe framework is:\n\n- **Estimator-agnostic.** It wraps around any time-series quasi-experimental method (Interrupted Time Series, Synthetic Control, Difference-in-Differences, Bayesian Structural Time Series) without modifying the estimator itself.\n- **Pre-intervention.** The entire analysis runs before the campaign launches, enabling go/no-go decisions based on quantified risk.\n- **Implemented in open-source Python.** PyMC for Bayesian inference, CausalPy for quasi-experimental estimation, PreliZ for prior elicitation, and nutpie for MCMC sampling.\n\n## The Problem: Two Kinds of Uncertainty\n\nIf you've designed an A/B test, you've already dealt with **aleatoric uncertainty**: the inherent randomness in your metric. You account for it when you size your test (power analysis) and when you interpret results (confidence or credible intervals). This uncertainty is irreducible: no amount of data collection or modeling can eliminate it.\n\nTime-series quasi-experiments have aleatoric uncertainty too. But they have an additional problem: **epistemic uncertainty**, the part of our ignorance that is in principle reducible through better data or better models (Hüllermeier & Waegeman, 2021). Because the counterfactual must be *modeled* rather than *randomized*, the estimate is exposed to a specific form of epistemic uncertainty: the identifying assumptions may be violated. When they are, the counterfactual prediction deviates from the true unobserved outcome. We call this deviation the **structural error**, and the broader uncertainty it reflects **structural uncertainty**. We use *structural* as shorthand throughout this post.\n\nBayesian credible intervals capture aleatoric uncertainty and parameter uncertainty well, but only conditional on the model being correctly specified. If the identifying assumptions break down, the estimator may attribute structural error to the intervention, producing a false positive. The framework presented here empirically characterizes the structural uncertainty distribution by calibrating the estimator against its own historical performance.\n\n## Setting Up: Code and Data\n\nBefore touching any model, we need to answer a fundamental question: **how good are our control units at predicting the treated unit?** If none of the control brands track Wendy's search interest very well, the synthetic counterfactual will be imprecise — and any gap between real and synthetic could be mistaken for a treatment effect.\n\n::: {#f3ae4346 .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — imports, configuration, and data loading\"}\nimport contextlib\nimport io\nfrom pathlib import Path\nfrom typing import Any, Callable\n\nimport arviz as az\nimport causalpy as cp\nimport matplotlib\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as mpatches\nimport matplotlib.gridspec as gridspec\nimport numpy as np\nimport pandas as pd\nimport preliz as pz\nimport pymc as pm\nimport scipy.stats as stats\nimport xarray as xr\nfrom pydantic import BaseModel\nfrom types import SimpleNamespace\n\n# --- Configuration ---\n_dir = Path(\"..\").resolve()\n\ncfg = SimpleNamespace(\n    DATA_PATH=\"files/google_trends_demo.csv\",\n    DPI=300,\n    SEED=42,\n    TREATMENT_COL=\"wendys\",\n    TREATED_UNITS=[\"wendys\"],\n    CONTROL_UNITS=[\n        \"mcdonalds\", \"burger_king\", \"kfc\",\n        \"taco_bell\", \"subway\", \"pizza_hut\", \"five_guys\",\n    ],\n    INTERVENTION_START=\"2024-09-01\",\n    INTERVENTION_MONTHS=3,\n    PLACEBO_MONTHS=2,\n    N_FOLDS=4,\n    MIN_TRAINING_PCT=0.30,\n    EXCLUDE_MONTHS={\"2024-10\", \"2024-11\"},\n    ROPE_HALF_WIDTH=2.5,\n    DECISION_THRESHOLD=0.95,\n    EXPECTED_EFFECT_LOWER=5.0,\n    EXPECTED_EFFECT_UPPER=25.0,\n    N_MCMC_DRAWS=1000,\n    N_MCMC_TUNE=1000,\n    N_CHAINS=4,\n    C_TREATMENT=\"#7c3aed\",\n    C_NULL=\"#94a3b8\",\n    C_ALT=\"#2563eb\",\n    C_FPR=\"#E24A33\",\n    C_ASSURANCE=\"#348ABD\",\n    C_INDET=\"#988ED5\",\n    C_NEGATIVE=\"#b91c1c\",\n    C_OTHER_BRANDS=\"#a8d4f0\",\n    BRAND_COLORS={\n        \"wendys\": \"#7c3aed\",\n        \"mcdonalds\": \"#b8ddf0\",\n        \"burger_king\": \"#9dcee8\",\n        \"kfc\": \"#82bfe0\",\n        \"taco_bell\": \"#67b0d8\",\n        \"subway\": \"#4ca1d0\",\n        \"pizza_hut\": \"#3192c8\",\n        \"five_guys\": \"#1a83b8\",\n    },\n    FOLD_COLORS=[\"#348ABD\", \"#E24A33\", \"#988ED5\", \"#8EBA42\", \"#FFB347\"],\n)\n\n# --- Plot style ---\nplt.style.use(\"seaborn-v0_8-whitegrid\")\nplt.rcParams.update({\n    \"figure.figsize\": [9, 5],\n    \"figure.dpi\": 150,\n    \"font.family\": \"sans-serif\",\n    \"font.sans-serif\": [\"Source Sans Pro\", \"Helvetica Neue\", \"Arial\"],\n    \"font.size\": 9,\n    \"axes.labelsize\": 9,\n    \"axes.titlesize\": 10,\n    \"axes.titleweight\": \"bold\",\n    \"xtick.labelsize\": 8,\n    \"ytick.labelsize\": 8,\n    \"legend.fontsize\": 8,\n    \"figure.titlesize\": 11,\n    \"axes.spines.top\": False,\n    \"axes.spines.right\": False,\n    \"axes.edgecolor\": \"#64748b\",\n    \"axes.labelcolor\": \"#334155\",\n    \"xtick.color\": \"#64748b\",\n    \"ytick.color\": \"#64748b\",\n    \"grid.alpha\": 0.3,\n})\n\n# --- Load data ---\ndf = pd.read_csv(cfg.DATA_PATH, parse_dates=[\"Time\"])\ndf.columns = [\n    \"date\", \"mcdonalds\", \"burger_king\", \"wendys\", \"kfc\",\n    \"taco_bell\", \"subway\", \"pizza_hut\", \"five_guys\",\n]\ndf = df.set_index(\"date\").sort_index().astype(float)\nintervention_ts = pd.Timestamp(cfg.INTERVENTION_START)\ndf_pre = df.loc[df.index < intervention_ts].copy()\n\nprint(f\"Data loaded: {len(df)} months ({df.index.min():%Y-%m} to {df.index.max():%Y-%m}).\")\nprint(f\"Pre-intervention: {len(df_pre)} months available for calibration.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData loaded: 40 months (2022-12 to 2026-03).\nPre-intervention: 21 months available for calibration.\n```\n:::\n:::\n\n\n### The raw data: eight fast-food brands on Google Trends\n\nHere's what we're working with: monthly search interest for eight fast-food brands from late 2022 through early 2026. Wendy's (purple) is the brand that ran the campaign; the other seven are potential \"donor\" brands that the Synthetic Control will blend together to build a counterfactual.\n\n::: {#cd31c278 .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — raw data plot\"}\nfig, ax = plt.subplots(figsize=(10, 5))\n\nfor brand in cfg.CONTROL_UNITS:\n    ax.plot(\n        df.index, df[brand],\n        color=cfg.BRAND_COLORS.get(brand, cfg.C_OTHER_BRANDS),\n        alpha=0.4, linewidth=1,\n        label=brand.replace(\"_\", \" \").title() + \" (control)\",\n    )\nax.plot(\n    df.index, df[cfg.TREATMENT_COL],\n    color=cfg.C_TREATMENT, linewidth=2.5,\n    label=\"Wendy's (treatment)\",\n)\nax.axvline(\n    intervention_ts, color=\"#0f172a\", linestyle=\"--\", linewidth=1.2,\n    alpha=0.7, label=\"Planned intervention\",\n)\nax.axvspan(\n    intervention_ts, intervention_ts + pd.DateOffset(months=cfg.INTERVENTION_MONTHS),\n    alpha=0.08, color=cfg.C_TREATMENT,\n)\nax.set_xlabel(\"Date\")\nax.set_ylabel(\"Google Trends Index\")\nax.set_title(\"Google Trends: Fast Food Brands (Monthly)\")\nax.legend(\n    loc=\"upper left\", frameon=True, fancybox=False,\n    edgecolor=\"#e2e8f0\", fontsize=7, ncol=2,\n)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-4-output-1.png){width=1488 height=739}\n:::\n:::\n\n\n### How well do the controls predict Wendy's?\n\nTwo diagnostics tell the story. The **correlation matrix** shows how strongly each brand correlates with Wendy's — correlations range from near-zero to ~0.45. In A/B testing terms, this is like having a very noisy control group. The **Variance Inflation Factors** show how much the control brands overlap with each other: high VIF means redundant donors.\n\n::: {#efd62197 .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — correlation matrix and VIF diagnostics\"}\n_cols = [cfg.TREATMENT_COL] + cfg.CONTROL_UNITS\n_corr = df_pre[_cols].corr()\n\nfig, (ax_heat, ax_vif) = plt.subplots(\n    1, 2, figsize=(12, 5),\n    gridspec_kw={\"width_ratios\": [1, 1.2]},\n)\n\n# Panel A: Correlation heatmap\nim = ax_heat.imshow(\n    _corr.values, cmap=\"Blues\", vmin=-1, vmax=1, aspect=\"auto\",\n)\n_labels = [c.replace(\"_\", \" \").title() for c in _cols]\nax_heat.set_xticks(range(len(_cols)))\nax_heat.set_yticks(range(len(_cols)))\nax_heat.set_xticklabels(_labels, rotation=45, ha=\"right\", fontsize=7)\nax_heat.set_yticklabels(_labels, fontsize=7)\nfor i in range(len(_cols)):\n    for j in range(len(_cols)):\n        ax_heat.text(\n            j, i, f\"{_corr.values[i, j]:.2f}\",\n            ha=\"center\", va=\"center\", fontsize=6.5,\n            color=\"white\" if abs(_corr.values[i, j]) > 0.5 else \"black\",\n        )\nfig.colorbar(im, ax=ax_heat, shrink=0.8)\nax_heat.set_title(\"A: Correlation Matrix (Pre-Intervention)\")\n\n# Panel B: VIF\n_X_ctrl = df_pre[cfg.CONTROL_UNITS].values\nvifs = {}\nfor j_idx, ctrl in enumerate(cfg.CONTROL_UNITS):\n    _y_j = _X_ctrl[:, j_idx]\n    _X_rest = np.delete(_X_ctrl, j_idx, axis=1)\n    _X_rest = np.column_stack([np.ones(_X_rest.shape[0]), _X_rest])\n    _coef, *_ = np.linalg.lstsq(_X_rest, _y_j, rcond=None)\n    _ss_res = np.sum((_y_j - _X_rest @ _coef) ** 2)\n    _ss_tot = np.sum((_y_j - _y_j.mean()) ** 2)\n    _r_sq = 1 - _ss_res / _ss_tot if _ss_tot > 0 else 0.0\n    vifs[ctrl] = 1.0 / (1.0 - _r_sq) if _r_sq < 1.0 else np.inf\n\n_sorted_brands = sorted(vifs, key=vifs.get)\n_vif_vals = [vifs[b] for b in _sorted_brands]\n_bar_colors = [cfg.BRAND_COLORS.get(b, cfg.C_OTHER_BRANDS) for b in _sorted_brands]\n_bar_labels = [b.replace(\"_\", \" \").title() for b in _sorted_brands]\n\nax_vif.barh(\n    _bar_labels, _vif_vals, color=_bar_colors,\n    edgecolor=\"white\", linewidth=0.5,\n)\nax_vif.axvline(\n    5, color=\"#64748b\", linestyle=\"--\", linewidth=0.8, label=\"VIF = 5\",\n)\nax_vif.set_xlabel(\"Variance Inflation Factor\")\nax_vif.set_title(\"B: Donor Pool Multicollinearity (VIF)\")\nax_vif.legend(\n    frameon=True, fancybox=False, edgecolor=\"#e2e8f0\",\n    fontsize=6.5, loc=\"lower right\",\n)\n\nfig.suptitle(\n    f\"Treatment\\u2013Control Relationships \"\n    f\"(n = {len(df_pre)} months, pre-intervention)\",\n    fontweight=\"bold\", fontsize=10,\n)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-5-output-1.png){width=1790 height=745}\n:::\n:::\n\n\n**Bottom line:** We're building a counterfactual from mediocre predictors. That's not a reason to abandon the analysis — it's a reason to *calibrate how much error that introduces*.\n\n## The Framework\n\n### Design Inputs\n\nBefore running any analysis, two sets of inputs must be defined.\n\n**Stakeholder inputs** (risk tolerance):\n\n- **ROPE half-width ($\\Delta$):** The threshold below which an effect is \"practically zero.\" For the Wendy's case, we set $\\Delta = 2.5$ Google Trends points, as a bimonthly lift smaller than 2.5 points is not meaningfully distinguishable from organic fluctuation.\n- **Decision threshold ($p^*$):** The required posterior probability for a definitive call. We use $p^* = 0.95$.\n\n**Domain-knowledge inputs** (market expertise):\n\n- **Expected-Effect Prior ($S_{alt}$):** A probability distribution encoding \"if this campaign works, how big will the lift be?\" For Wendy's, the marketing team might judge that a successful viral campaign should produce a bimonthly lift in the range of 5 to 25 GT points.\n- **Placebo schedule ($J$, $L$):** The number and length of historical windows for calibration. We use $J = 4$ bimonthly windows randomly selected from the pre-campaign period.\n\n### Placebo-in-Time Tests\n\nThe core idea is simple: run your estimator on periods where you *know* the true effect is zero. Any non-zero estimate reveals structural noise: the \"background radiation\" of your data environment.\n\nWe pick several historical windows — periods well before the actual campaign — where we *know* the true treatment effect is zero. We run the exact same Synthetic Control model on each window, pretending an intervention started there. Whatever the model reports as a \"causal effect\" is entirely due to structural noise: trends drifting, donors being imperfect, the model's assumptions not quite holding.\n\nWe use **random** fold selection: we draw pseudo-intervention times uniformly from eligible months (each must have at least 30% of the pre-period as training data, and can't overlap the real campaign). Random windows sample different structural regimes, avoid temporal correlation between adjacent folds, and make the exchangeability assumption of the hierarchical model more plausible.\n\nThe code cell below defines the utility functions we'll use throughout the rest of the analysis — the Synthetic Control factory, the RandomPlaceboAnalysis runner, the ROPE decision rule, the hierarchical null fitter, and the operating characteristics simulator.\n\n::: {#4cc233ec .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — utility functions\"}\n# --- Synthetic Control factory ---\ndef sc_factory(dataset, treatment_time, treatment_time_end):\n    \"\"\"CausalPy Synthetic Control factory.\"\"\"\n    return cp.SyntheticControl(\n        dataset,\n        treatment_time,\n        control_units=cfg.CONTROL_UNITS,\n        treated_units=cfg.TREATED_UNITS,\n        model=cp.pymc_models.WeightedSumFitter(\n            sample_kwargs={\n                \"target_accept\": 0.95,\n                \"random_seed\": cfg.SEED,\n                \"progressbar\": False,\n            }\n        ),\n    )\n\n\n# --- Random Placebo Analysis ---\nclass RandomPlaceboAnalysis(BaseModel):\n    \"\"\"Placebo-in-time analysis with randomly selected windows.\"\"\"\n\n    model_config = {\"arbitrary_types_allowed\": True}\n\n    experiment_factory: Callable\n    dataset: pd.DataFrame\n    intervention_start_date: str\n    intervention_months: int = 1\n    n_folds: int = 4\n    min_training_pct: float = 0.30\n    min_gap: int = 1\n    exclude_months: set[str] | None = None\n    seed: int = 42\n\n    def run(self) -> list[dict[str, Any]]:\n        treatment_time = pd.Timestamp(self.intervention_start_date)\n        pre_df = self.dataset.loc[self.dataset.index < treatment_time].copy()\n        if pre_df.empty:\n            raise ValueError(\"No observations before treatment_time.\")\n\n        n_total = len(pre_df)\n        min_training = int(np.ceil(self.min_training_pct * n_total))\n        exclude = self.exclude_months or set()\n        all_dates = pre_df.index.sort_values()\n\n        candidates = []\n        for date in all_dates:\n            pseudo_end = date + pd.DateOffset(months=self.intervention_months)\n            if date.strftime(\"%Y-%m\") in exclude:\n                continue\n            n_pre = (all_dates < date).sum()\n            if n_pre < min_training:\n                continue\n            if pseudo_end > treatment_time:\n                continue\n            candidates.append(date)\n\n        if len(candidates) < self.n_folds:\n            raise ValueError(\n                f\"Only {len(candidates)} eligible periods, \"\n                f\"but {self.n_folds} folds requested.\"\n            )\n\n        rng = np.random.default_rng(self.seed)\n        pool = list(range(len(candidates)))\n        selected_idx = []\n        for _ in range(self.n_folds):\n            valid = [\n                i for i in pool\n                if all(abs(i - s) >= self.min_gap for s in selected_idx)\n            ]\n            if not valid:\n                raise ValueError(\n                    \"Cannot select enough folds with min_gap constraint.\"\n                )\n            pick = rng.choice(valid)\n            selected_idx.append(pick)\n            pool.remove(pick)\n\n        selected = sorted([candidates[i] for i in selected_idx])\n\n        results = []\n        for fold_idx, pseudo_start in enumerate(selected, 1):\n            pseudo_end = pseudo_start + pd.DateOffset(months=self.intervention_months)\n            fold_df = pre_df.loc[pre_df.index < pseudo_end].sort_index()\n            result = self.experiment_factory(fold_df, pseudo_start, pseudo_end)\n            results.append({\n                \"fold\": fold_idx,\n                \"pseudo_start\": pseudo_start,\n                \"pseudo_end\": pseudo_end,\n                \"result\": result,\n            })\n        return results\n\n\n# --- ROPE decision rule ---\ndef bayesian_rope_decision(samples, rope_half_width, threshold):\n    \"\"\"Classify a posterior sample under the ROPE decision rule.\"\"\"\n    if samples.ndim != 1:\n        samples = np.asarray(samples).ravel()\n    prob_pos = (samples > rope_half_width).mean()\n    prob_neg = (samples < -rope_half_width).mean()\n    prob_null = (np.abs(samples) <= rope_half_width).mean()\n    if prob_pos >= threshold:\n        return \"positive\"\n    elif prob_neg >= threshold:\n        return \"negative\"\n    elif prob_null >= threshold:\n        return \"null\"\n    else:\n        return \"indeterminate\"\n\n\n# --- Extract posteriors from placebo results ---\ndef extract_posteriors(results):\n    \"\"\"Extract cumulative posterior summaries from placebo fold results.\"\"\"\n    post_impact = xr.concat(\n        [\n            r[\"result\"]\n            .post_impact.sum(\"obs_ind\")\n            .isel(treated_units=0)\n            .stack(sample=(\"chain\", \"draw\"))\n            for r in results\n        ],\n        dim=\"fold\",\n    )\n    post_impact = post_impact.assign_coords(\n        sample=np.arange(post_impact.sizes[\"sample\"])\n    )\n    n_folds = post_impact.sizes[\"fold\"]\n    fold_means = np.array([\n        post_impact.isel(fold=i).mean().item() for i in range(n_folds)\n    ])\n    fold_sds = np.array([\n        post_impact.isel(fold=i).std().item() for i in range(n_folds)\n    ])\n    fold_sds = np.where(fold_sds < 1e-6, 1e-6, fold_sds)\n    return post_impact, fold_means, fold_sds\n\n\n# --- Hierarchical null model ---\ndef fit_hierarchical_null(fold_means, fold_sds, draws_per_chain):\n    \"\"\"Fit hierarchical normal-normal null model; return theta_new samples.\"\"\"\n    n_folds = len(fold_means)\n    prior_mu_scale = (\n        float(np.nanstd(fold_means)) if np.nanstd(fold_means) > 0 else 1.0\n    )\n    coords = {\"fold\": np.arange(n_folds)}\n    with pm.Model(coords=coords) as model:\n        pm.Data(\"obs_means\", fold_means, dims=\"fold\")\n        obs_sd = pm.Data(\"obs_sd\", fold_sds, dims=\"fold\")\n        mu = pm.Normal(\"mu\", mu=0.0, sigma=2.0 * prior_mu_scale)\n        tau = pm.HalfNormal(\"tau\", sigma=2.0 * prior_mu_scale)\n        z = pm.Normal(\"z\", mu=0.0, sigma=1.0, dims=\"fold\")\n        theta = pm.Deterministic(\"theta\", mu + tau * z, dims=\"fold\")\n        pm.Normal(\n            \"lik\", mu=theta, sigma=obs_sd,\n            observed=fold_means, dims=\"fold\",\n        )\n        idata = pm.sample(\n            draws=draws_per_chain, tune=cfg.N_MCMC_TUNE,\n            chains=cfg.N_CHAINS, target_accept=0.97,\n            nuts_sampler=\"nutpie\", random_seed=cfg.SEED,\n            progressbar=False\n        )\n    with model:\n        model.add_coords({\"new\": np.arange(1)})\n        pm.Normal(\"theta_new\", mu=mu, sigma=tau, dims=\"new\")\n        ppc = pm.sample_posterior_predictive(\n            idata, var_names=[\"theta_new\"], random_seed=cfg.SEED,\n            progressbar=False,\n        )\n    return (\n        ppc[\"posterior_predictive\"][\"theta_new\"]\n        .stack(sample=(\"chain\", \"draw\")).values.squeeze()\n    )\n\n\n# --- Operating characteristics simulator ---\ndef compute_oc(theta_new_samples, fold_sds, expected_effect_samples, n_samples_total):\n    \"\"\"Compute operating characteristics via ROPE simulation.\"\"\"\n    n_reps = int(min(theta_new_samples.size, expected_effect_samples.size))\n    rng = np.random.default_rng(cfg.SEED)\n    null_decisions, alt_decisions = [], []\n    for i in range(n_reps):\n        sd_sim = rng.choice(fold_sds)\n        post_null = rng.normal(\n            float(theta_new_samples[i]), sd_sim, size=n_samples_total,\n        )\n        null_decisions.append(\n            bayesian_rope_decision(post_null, cfg.ROPE_HALF_WIDTH, cfg.DECISION_THRESHOLD)\n        )\n        post_alt = rng.normal(\n            float(expected_effect_samples[i] + theta_new_samples[i]),\n            sd_sim, size=n_samples_total,\n        )\n        alt_decisions.append(\n            bayesian_rope_decision(post_alt, cfg.ROPE_HALF_WIDTH, cfg.DECISION_THRESHOLD)\n        )\n    null_decisions = np.array(null_decisions)\n    alt_decisions = np.array(alt_decisions)\n    _null_act = (null_decisions == \"positive\") | (null_decisions == \"negative\")\n    _alt_act = (alt_decisions == \"positive\") | (alt_decisions == \"negative\")\n    return {\n        \"FPR\": float(np.mean(_null_act)),\n        \"Assurance\": float(np.mean(_alt_act)),\n        \"Null Indet.\": float(np.mean(null_decisions == \"indeterminate\")),\n        \"Alt Indet.\": float(np.mean(alt_decisions == \"indeterminate\")),\n        \"Null True Neg.\": float(np.mean(null_decisions == \"null\")),\n        \"Alt False Neg.\": float(np.mean(alt_decisions == \"null\")),\n        \"null_decisions\": null_decisions,\n        \"alt_decisions\": alt_decisions,\n    }\n```\n:::\n\n\n#### Running the Placebo Tests\n\nFrom the 21-month pre-campaign period, four pseudo-intervention times were randomly selected (seed = 42), subject to the eligibility constraints: each fold requires at least 30% of pre-intervention data as training, and the placebo windows do not overlap with the intervention period. For each, we fit a Bayesian Synthetic Control model (CausalPy's `WeightedSumFitter`) using the seven control brands as donor units.\n\n::: {#a797fc94 .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — run placebo calibration\"}\n_pa = RandomPlaceboAnalysis(\n    experiment_factory=sc_factory,\n    dataset=df_pre,\n    intervention_start_date=cfg.INTERVENTION_START,\n    intervention_months=cfg.PLACEBO_MONTHS,\n    n_folds=cfg.N_FOLDS,\n    min_training_pct=cfg.MIN_TRAINING_PCT,\n    min_gap=2,\n    exclude_months=cfg.EXCLUDE_MONTHS,\n    seed=cfg.SEED\n)\nresults_placebo = _pa.run()\n\nprint(f\"Placebo calibration complete: {len(results_placebo)} folds fitted.\")\nprint(\n    \"Pseudo-intervention start months:\",\n    \", \".join(r[\"pseudo_start\"].strftime(\"%b %Y\") for r in results_placebo)\n)\n```\n:::\n\n\nThe plot below shows which historical periods were selected as placebo windows. Each colored band is a bimonthly window where we *pretended* an intervention happened and ran the full Synthetic Control pipeline. The hatched region on the right is the actual Krabby Patty campaign — completely untouched during calibration.\n\n::: {#3ddb0cd5 .cell execution_count=7}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — placebo windows schematic\"}\nfig, ax = plt.subplots(figsize=(10, 3.5))\n_dates = df_pre.index\nax.plot(\n    _dates, df_pre[cfg.TREATMENT_COL],\n    color=cfg.C_TREATMENT, linewidth=1.5, alpha=0.5,\n)\nfor i, r in enumerate(results_placebo):\n    ps = r[\"pseudo_start\"]\n    pe = r[\"pseudo_end\"]\n    c = cfg.FOLD_COLORS[i % len(cfg.FOLD_COLORS)]\n    ax.axvspan(\n        ps, pe, alpha=0.2, color=c,\n        label=f\"Fold {i+1}: {ps.strftime('%b %Y')}\\u2013{pe.strftime('%b %Y')}\",\n    )\n    ax.axvline(ps, color=c, linewidth=1, linestyle=\"--\", alpha=0.6)\nax.axvspan(\n    intervention_ts, intervention_ts + pd.DateOffset(months=cfg.INTERVENTION_MONTHS),\n    alpha=0.15, color=cfg.C_TREATMENT, hatch=\"//\",\n)\nax.axvline(\n    intervention_ts, color=\"#0f172a\", linewidth=1.5, linestyle=\"--\", alpha=0.8,\n)\nax.text(\n    intervention_ts + pd.DateOffset(days=10), ax.get_ylim()[1] * 0.95,\n    \"Planned\\nintervention\", fontsize=7, va=\"top\", fontweight=\"bold\",\n)\nax.set_xlabel(\"Date\")\nax.set_ylabel(\"Wendy's (GT Index)\")\nax.set_title(\"Placebo-in-Time Windows (Random Selection Across Pre-Period)\")\nax.legend(\n    loc=\"upper left\", fontsize=7, frameon=True, fancybox=False,\n    edgecolor=\"#e2e8f0\",\n)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-8-output-1.png){width=1487 height=514}\n:::\n:::\n\n\nNow we extract the cumulative effect posteriors from each placebo fold. Even though the true effect is zero in every window, the model reports estimated lifts ranging from approximately −4.7 to +4.2 Google Trends points. The model hallucinates non-trivial lifts from pure structural drift.\n\n::: {#0201890f .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — extract placebo posteriors\"}\npost_impact, fold_means, fold_sds = extract_posteriors(results_placebo)\nn_samples = post_impact.sizes[\"sample\"]\n\nprint(f\"Fold means: [{', '.join(f'{m:.2f}' for m in fold_means)}]\")\nprint(f\"Fold SDs:   [{', '.join(f'{s:.2f}' for s in fold_sds)}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFold means: [4.14, -4.54, -4.67, -0.63]\nFold SDs:   [1.29, 1.30, 1.15, 1.06]\n```\n:::\n:::\n\n\nThe histogram below shows the posterior distribution of the cumulative causal effect for each placebo fold. Each histogram represents a period where **the true effect is exactly zero** — yet the model reports non-trivial effects.\n\n::: {#cc549b1e .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — placebo posteriors histogram\"}\n_n_folds = post_impact.sizes[\"fold\"]\nfig, ax = plt.subplots(figsize=(8, 5))\nfor i in range(_n_folds):\n    _data = post_impact.isel(fold=i).values\n    ax.hist(\n        _data, bins=40, density=True, alpha=0.55,\n        color=cfg.FOLD_COLORS[i % len(cfg.FOLD_COLORS)],\n        edgecolor=\"white\", linewidth=0.5,\n        label=f\"Fold {i+1} (mean: {fold_means[i]:.1f})\",\n    )\nax.axvline(0, color=\"#0f172a\", linestyle=\"-\", linewidth=1.2, alpha=0.6, label=\"Zero\")\nax.set_xlabel(\"Cumulative Effect (Google Trends Points)\")\nax.set_ylabel(\"Density\")\nax.set_title(\"Placebo Cumulative Effect Posteriors (True Effect = 0)\")\nax.legend(frameon=True, fancybox=False, edgecolor=\"#e2e8f0\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-10-output-1.png){width=1188 height=739}\n:::\n:::\n\n\n**This is the key insight:** the model's credible intervals are too narrow to capture the structural volatility. Each fold's posterior is tight (small $s_j$), but the fold means scatter widely. This gap between within-fold precision and between-fold heterogeneity is exactly what the hierarchical null model is designed to capture.\n\n### Hierarchical Null Construction\n\nRather than treating placebo results as isolated anecdotes (\"the worst false alarm was 4.2 points\"), we model them as draws from a latent distribution: a \"status quo\" process governing how much structural drift the estimator absorbs.\n\nThis is similar to a Bayesian normal–normal random-effects meta-analysis (Higgins & Thompson, 2002), where each placebo fold plays the role of a \"study.\"\n\n**Level 1: Within-fold uncertainty.** For each fold $j$, the posterior mean $m_j$ is a noisy observation of a latent true structural error $\\theta_j$:\n\n$$m_j \\mid \\theta_j, s_j \\sim \\mathcal{N}(\\theta_j,\\; s_j^2)$$\n\n**Level 2: Between-fold heterogeneity.** The latent errors are drawn from a population distribution:\n\n$$\\theta_j \\sim \\mathcal{N}(\\mu_{null},\\; \\tau_{het}^2)$$\n\n- $\\mu_{null}$: Systematic bias — the model's average tendency to over- or under-estimate. In a well-calibrated model, this is near zero.\n- $\\tau_{het}$: Structural volatility — the critical parameter. A high $\\tau_{het}$ means the estimator routinely produces false alarms of non-trivial magnitude.\n\n**Level 3: Weakly informative hyperpriors.** We set $\\mu_{null} \\sim \\mathcal{N}(0, 2\\hat{\\sigma})$ and $\\tau_{het} \\sim \\text{HalfNormal}(2\\hat{\\sigma})$, where $\\hat{\\sigma}$ is the empirical standard deviation of the fold means.\n\nFitting this model yields a **Null Predictive Distribution**: the expected range of estimates under \"no effect\":\n\n$$\\tilde{\\theta}_{new} \\sim \\mathcal{N}(\\mu_{null},\\; \\tau_{het}^2)$$\n\n::: {#5396906c .cell execution_count=10}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — fit hierarchical null model\"}\n_draws_per_chain = n_samples // cfg.N_CHAINS\ntheta_new_samples = fit_hierarchical_null(fold_means, fold_sds, _draws_per_chain)\n_mu_hat = float(np.mean(theta_new_samples))\n_sd_hat = float(np.std(theta_new_samples))\n\nprint(f\"Null Predictive Distribution fitted.\")\nprint(f\"  mu = {_mu_hat:.2f} GT points (estimator bias)\")\nprint(f\"  sigma = {_sd_hat:.2f} GT points (structural volatility)\")\nprint(f\"  Based on {theta_new_samples.shape[0]:,} posterior draws.\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSampling: [theta_new]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nNull Predictive Distribution fitted.\n  mu = -1.21 GT points (estimator bias)\n  sigma = 6.30 GT points (structural volatility)\n  Based on 4,000 posterior draws.\n```\n:::\n:::\n\n\nThe forest plot below (Panel A) shows each placebo fold's estimated cumulative effect with its 95% credible interval. Panel B shows the resulting Null Predictive Distribution — the hierarchical model's best estimate of *what noise looks like* for this estimator.\n\n::: {#1dcc40e6 .cell execution_count=11}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — forest plot and null predictive distribution\"}\n_n_folds = len(fold_means)\nfig, (ax_forest, ax_null) = plt.subplots(\n    1, 2, figsize=(11, 4.5),\n    gridspec_kw={\"width_ratios\": [1, 1.3]},\n)\n\n# Panel A: Forest plot\n_y_pos = np.arange(_n_folds)\n_ci_95 = 1.96\nfor i in range(_n_folds):\n    lo = fold_means[i] - _ci_95 * fold_sds[i]\n    hi = fold_means[i] + _ci_95 * fold_sds[i]\n    ax_forest.plot(\n        [lo, hi], [i, i], color=cfg.C_ALT, linewidth=2, alpha=0.7,\n    )\n    ax_forest.plot(\n        fold_means[i], i, \"o\", color=cfg.C_ALT, markersize=7, zorder=5,\n    )\nax_forest.axvline(0, color=\"#0f172a\", linestyle=\"--\", linewidth=1, alpha=0.5)\nax_forest.set_yticks(_y_pos)\nax_forest.set_yticklabels([f\"Fold {i+1}\" for i in range(_n_folds)])\nax_forest.set_xlabel(\"Cumulative Effect\")\nax_forest.set_title(\"A: Placebo Fold Estimates (\\u00b195% CI)\")\nax_forest.invert_yaxis()\n\n# Panel B: Null predictive distribution\nax_null.hist(\n    theta_new_samples, bins=60, density=True, alpha=0.55,\n    color=cfg.C_NULL, edgecolor=\"white\", linewidth=0.5,\n    label=\"Null Predictive Distribution\",\n)\nax_null.axvline(0, color=\"#0f172a\", linestyle=\"-\", linewidth=1.2, alpha=0.6)\nax_null.axvline(\n    _mu_hat, color=cfg.C_ALT, linestyle=\"--\", linewidth=1,\n    label=f\"Mean = {_mu_hat:.1f}\",\n)\nax_null.text(\n    0.95, 0.92,\n    f\"$\\\\mu$ = {_mu_hat:.1f}\\n$\\\\sigma$ = {_sd_hat:.1f}\",\n    transform=ax_null.transAxes, fontsize=8, va=\"top\", ha=\"right\",\n    bbox=dict(boxstyle=\"round,pad=0.3\", facecolor=\"white\", edgecolor=\"#e2e8f0\"),\n)\nax_null.set_xlabel(\"Cumulative Effect\")\nax_null.set_ylabel(\"Density\")\nax_null.set_title(\"B: Null Predictive Distribution\")\nax_null.legend(frameon=True, fancybox=False, edgecolor=\"#e2e8f0\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-12-output-1.png){width=1639 height=664}\n:::\n:::\n\n\nThis means that under the status quo, the estimator can easily report cumulative effects of ±12 points or more, purely from structural drift.\n\n### Expected-Effect Prior\n\nClassical power analysis requires a single fixed effect size (\"if the true lift is exactly 5 points, power is X%\"). In Bayesian design analysis, we acknowledge that the true campaign effect is uncertain even if the campaign works. We specify an **Expected-Effect Prior** $S_{alt}$: a probability distribution encoding plausible outcomes under the alternative hypothesis.\n\nThis moves us from classical Power to **Bayesian Assurance** (O'Hagan et al., 2005): the unconditional probability of a correct positive decision, averaged over all plausible effect sizes. Assurance answers a more honest question: *\"Across the realistic range of campaign outcomes, what is the overall probability of a correct detection?\"*\n\nFor the Krabby Patty Kollab, suppose the marketing team expects a bimonthly search interest lift between 5 and 25 Google Trends points if the campaign is successful. Using a Maximum Entropy approach (PreliZ), we find the least informative Gamma distribution with 90% of its mass in [5, 25]:\n\n::: {#bfa23c83 .cell execution_count=12}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — expected-effect prior\"}\nexpected_effect_dist = pz.maxent(\n    pz.Gamma(),\n    lower=cfg.EXPECTED_EFFECT_LOWER,\n    upper=cfg.EXPECTED_EFFECT_UPPER,\n    mass=0.90,\n    plot=False,\n)\n_n_draws = theta_new_samples.size\nexpected_effect_samples = expected_effect_dist.rvs(\n    _n_draws, random_state=np.random.default_rng(cfg.SEED),\n)\nprint(f\"Expected-Effect Prior: MaxEnt Gamma with 90% mass in \"\n      f\"[{cfg.EXPECTED_EFFECT_LOWER}, {cfg.EXPECTED_EFFECT_UPPER}]\")\nprint(f\"  mu = {np.mean(expected_effect_samples):.2f}, \"\n      f\"sigma = {np.std(expected_effect_samples):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nExpected-Effect Prior: MaxEnt Gamma with 90% mass in [5.0, 25.0]\n  mu = 15.25, sigma = 6.40\n```\n:::\n:::\n\n\nThe plot below overlays the Null Predictive Distribution (grey) with the Expected-Effect Prior (blue). The overlap between the two distributions represents the fundamental difficulty of the decision task: the zone where a real campaign effect is hard to distinguish from structural noise.\n\n::: {#2bf59543 .cell execution_count=13}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — null vs alternative overlay\"}\nfig, ax = plt.subplots(figsize=(9, 5))\nax.hist(\n    theta_new_samples, bins=50, density=True, alpha=0.5,\n    color=cfg.C_NULL, edgecolor=\"white\", linewidth=0.5,\n    label=\"Null Predictive (Status Quo)\",\n)\nax.hist(\n    expected_effect_samples, bins=50, density=True, alpha=0.5,\n    color=cfg.C_ALT, edgecolor=\"white\", linewidth=0.5,\n    label=\"Expected-Effect Prior (Alternative)\",\n)\nax.axvline(0, color=\"#0f172a\", linestyle=\"-\", linewidth=1.2, alpha=0.6)\nax.axvspan(\n    -cfg.ROPE_HALF_WIDTH, cfg.ROPE_HALF_WIDTH,\n    alpha=0.1, color=\"#f59e0b\",\n    label=f\"ROPE [\\u00b1{cfg.ROPE_HALF_WIDTH}]\",\n)\nax.axvline(-cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", linestyle=\":\", linewidth=1, alpha=0.6)\nax.axvline(cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", linestyle=\":\", linewidth=1, alpha=0.6)\nax.set_xlabel(\"Cumulative Effect (Google Trends Points)\")\nax.set_ylabel(\"Density\")\nax.set_title(\"Null Predictive Distribution vs Expected-Effect Prior\")\nax.legend(frameon=True, fancybox=False, edgecolor=\"#e2e8f0\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-14-output-1.png){width=1338 height=739}\n:::\n:::\n\n\n## Decision Rules: ROPE\n\nStandard practice in quasi-experiments often relies on a binary rule: if the 95% credible interval excludes zero, declare the effect significant. This conflates *precision* with *utility*: a very precise estimate of a 0.001-point lift is statistically non-zero but practically worthless.\n\nWe adopt the **Region of Practical Equivalence** (ROPE) framework (Kruschke, 2018). We define a range $[-\\Delta, +\\Delta]$ around zero representing effects that are \"practically zero.\" The decision rule is:\n\n- **Actionable Positive:** $P(\\hat{\\tau} > \\Delta) \\ge p^*$ — the effect exceeds the practical threshold with high confidence.\n- **Actionable Negative:** $P(\\hat{\\tau} < -\\Delta) \\ge p^*$ — the campaign likely caused harm.\n- **Practically Null:** $P(|\\hat{\\tau}| \\le \\Delta) \\ge p^*$ — the effect is negligible.\n- **Indeterminate:** Otherwise — the data cannot distinguish signal from noise.\n\nThe four-category classification explicitly introduces a \"suspend judgment\" outcome and a harm-detection mechanism, preventing the common failure mode where weak signals are forced into binary buckets.\n\n::: {#f5c43abd .cell execution_count=14}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — ROPE decision rule illustration\"}\nfig, axes = plt.subplots(1, 4, figsize=(14, 3.2), sharey=True)\n_x = np.linspace(-15, 25, 300)\n_scenarios = [\n    (\"Actionable Positive\", 10, 2.0, \"#22c55e\"),\n    (\"Actionable Negative\", -8, 2.0, \"#ef4444\"),\n    (\"Practically Null\", 0.5, 1.0, \"#f59e0b\"),\n    (\"Indeterminate\", 4.0, 3.0, \"#94a3b8\"),\n]\nfor ax, (title, mu, sd, color) in zip(axes, _scenarios):\n    density = stats.norm.pdf(_x, mu, sd)\n    ax.fill_between(_x, density, alpha=0.4, color=color)\n    ax.plot(_x, density, color=color, linewidth=1.5)\n    ax.axvspan(\n        -cfg.ROPE_HALF_WIDTH, cfg.ROPE_HALF_WIDTH,\n        alpha=0.15, color=\"#f59e0b\",\n    )\n    ax.axvline(-cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", linestyle=\":\", linewidth=0.8, alpha=0.6)\n    ax.axvline(cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", linestyle=\":\", linewidth=0.8, alpha=0.6)\n    ax.axvline(0, color=\"#0f172a\", linestyle=\"-\", linewidth=0.8, alpha=0.4)\n    ax.set_title(title, fontsize=9, fontweight=\"bold\", color=color)\n    ax.set_xlabel(\"Effect\")\n    ax.set_xlim(-15, 20)\naxes[0].set_ylabel(\"Density\")\nfig.suptitle(\n    f\"ROPE Decision Rule Illustration (ROPE = \\u00b1{cfg.ROPE_HALF_WIDTH})\",\n    fontweight=\"bold\", fontsize=10,\n)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-15-output-1.png){width=2088 height=479}\n:::\n:::\n\n\n## Simulating Operating Characteristics\n\nThe final step combines the Hierarchical Null, the Expected-Effect Prior, and the ROPE decision rule in a Monte Carlo simulation to produce the **Operating Characteristic Table**: the design's reliability profile computed *before* any real campaign data is analyzed.\n\n::: {.callout-note}\n**Algorithm: Bayesian Design Assurance Simulation**\n\nFor each scenario (null, alternative), repeat $N$ times:\n\n1. **Draw true effect:** $\\theta^*_i$ from the Null Predictive (null) or from $S_{alt}$ + Null Predictive (alternative)\n2. **Draw estimation noise:** $\\sigma_i$ sampled uniformly from the placebo fold standard deviations\n3. **Simulate synthetic posterior:** Draw $\\hat{\\tau}_k \\sim \\mathcal{N}(\\theta^*_i, \\sigma_i^2)$ for $k = 1, \\dots, K$\n4. **Classify:** Apply the ROPE decision rule\n\n**Outputs:** False Positive Rate (null classified as positive), Bayesian Assurance (alternative classified as positive), and Indeterminacy rates for both scenarios.\n:::\n\n::: {#d3498086 .cell execution_count=15}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — compute operating characteristics\"}\noc_results = compute_oc(\n    theta_new_samples, fold_sds, expected_effect_samples, n_samples,\n)\nnull_decisions = oc_results[\"null_decisions\"]\nalt_decisions = oc_results[\"alt_decisions\"]\n\nprint(\"Operating Characteristics:\")\nprint(f\"  FPR:           {oc_results['FPR']:.1%}\")\nprint(f\"  Assurance:     {oc_results['Assurance']:.1%}\")\nprint(f\"  Null Indet.:   {oc_results['Null Indet.']:.1%}\")\nprint(f\"  Alt Indet.:    {oc_results['Alt Indet.']:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOperating Characteristics:\n  FPR:           39.9%\n  Assurance:     89.6%\n  Null Indet.:   54.5%\n  Alt Indet.:    9.7%\n```\n:::\n:::\n\n\nThe chart below is the core output of the design analysis. It shows three classification outcomes — **Actionable** (we'd call it a real effect), **Practically Null** (we'd say nothing happened), and **Indeterminate** (we can't tell) — each evaluated under two scenarios: the true state is null (red) or alternative (blue).\n\n::: {#9848d53f .cell execution_count=16}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — operating characteristics chart\"}\ndef _three_cat(arr):\n    arr = np.asarray(arr)\n    return [\n        float(np.mean((arr == \"positive\") | (arr == \"negative\"))),\n        float(np.mean(arr == \"null\")),\n        float(np.mean(arr == \"indeterminate\")),\n    ]\n\nnull_props = _three_cat(null_decisions)\nalt_props = _three_cat(alt_decisions)\n\n_categories = [\"Actionable\", \"Practically\\nNull\", \"Indeterminate\"]\nfig, ax = plt.subplots(figsize=(9, 4.5))\n_y_pos = np.arange(len(_categories))\n_h = 0.35\n\nax.barh(\n    _y_pos + _h / 2, null_props, _h, label=\"True State: Null\",\n    color=cfg.C_FPR, alpha=0.85, edgecolor=\"white\", linewidth=0.8,\n)\nax.barh(\n    _y_pos - _h / 2, alt_props, _h, label=\"True State: Alternative\",\n    color=cfg.C_ASSURANCE, alpha=0.85, edgecolor=\"white\", linewidth=0.8,\n)\nax.set_yticks(_y_pos)\nax.set_yticklabels(_categories, fontweight=\"bold\", fontsize=9)\nax.set_xlabel(\"Probability of Decision Outcome\")\nax.set_xlim(0, 1.15)\nax.legend(\n    loc=\"upper center\", bbox_to_anchor=(0.5, -0.14), ncol=2,\n    frameon=True, fancybox=False, edgecolor=\"#e2e8f0\",\n)\nax.grid(axis=\"x\", linestyle=\":\", alpha=0.4)\nax.set_axisbelow(True)\n\n_labels_cfg = [\n    (0, null_props[0], \"False Positive\", cfg.C_FPR, _h / 2),\n    (0, alt_props[0], \"True Positive\\n(Assurance)\", cfg.C_ASSURANCE, -_h / 2),\n    (1, null_props[1], \"True Negative\", cfg.C_FPR, _h / 2),\n    (1, alt_props[1], \"False Negative\", cfg.C_ASSURANCE, -_h / 2),\n    (2, null_props[2], \"Null Indet.\", cfg.C_FPR, _h / 2),\n    (2, alt_props[2], \"Alt Indet.\", cfg.C_ASSURANCE, -_h / 2),\n]\nfor _y, _val, _lbl, _clr, _offset in _labels_cfg:\n    ax.text(\n        max(_val, 0) + 0.01, _y + _offset, f\"{_lbl}\\n{_val:.1%}\",\n        va=\"center\", color=_clr, fontsize=7.5, fontweight=\"bold\",\n    )\nax.set_title(\"Bayesian Operating Characteristics (Design Assurance)\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-17-output-1.png){width=1339 height=662}\n:::\n:::\n\n\n| Metric | Value | Interpretation |\n|--------|------:|----------------|\n| **False Positive Rate** | 40.8% | Under the status quo, the design erroneously declares an Actionable effect ~41% of the time |\n| **Bayesian Assurance** | 90.1% | If the campaign produces a lift in the expected [5, 25] range, the design detects it with high probability |\n| **Null Indeterminacy** | 53.9% | When there is no effect, 54% of the time the data is simply inconclusive |\n| **Alt Indeterminacy** | 9.3% | When the campaign works, approximately 9% of simulations produce indeterminate results |\n\n**What does this tell the Wendy's team?** The design has strong detection power (90.1% assurance) but a non-trivial structural false positive rate (40.8%). This is substantially higher than the conventional 5% threshold used in A/B testing, and it reflects a genuine property of the data: Google Trends indices for fast-food brands are noisy and weakly correlated, making the Synthetic Control counterfactual imprecise.\n\n## The Payoff: Interpreting Your Estimate in Context\n\nOnce the campaign runs and the real data arrives, the standard analysis produces a posterior estimate. But now the team has something they didn't have before: a calibrated sense of how much to trust it.\n\nEverything so far has been pre-intervention calibration. Now we apply the exact same Synthetic Control estimator to the **actual campaign period** (Sep–Nov 2024) and get our treatment effect estimate.\n\n**A crucial point:** The estimate itself is *identical* regardless of whether you did the design analysis. The framework doesn't change your model or adjust your numbers. It provides an **interpretive overlay** — a reliability label that travels with the estimate.\n\n::: {#56458d14 .cell execution_count=17}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — run real intervention estimate\"}\n_int_ts = pd.Timestamp(cfg.INTERVENTION_START)\n_end_ts = _int_ts + pd.DateOffset(months=cfg.INTERVENTION_MONTHS)\n_df_int = df.loc[df.index < _end_ts].copy()\n\n_result_int = cp.SyntheticControl(\n    _df_int,\n    _int_ts,\n    control_units=cfg.CONTROL_UNITS,\n    treated_units=cfg.TREATED_UNITS,\n    model=cp.pymc_models.WeightedSumFitter(\n        sample_kwargs={\n            \"target_accept\": 0.95,\n            \"random_seed\": cfg.SEED,\n            \"progressbar\": False,\n        }\n    ),\n)\nint_cumulative = (\n    _result_int.post_impact\n    .sum(\"obs_ind\")\n    .isel(treated_units=0)\n    .stack(sample=(\"chain\", \"draw\"))\n    .values\n)\nint_mean = float(np.mean(int_cumulative))\nint_ci_lo, int_ci_hi = np.percentile(int_cumulative, [2.5, 97.5])\n\nprint(f\"Intervention estimate: {int_mean:.1f} GT points\")\nprint(f\"95% CI: [{int_ci_lo:.1f}, {int_ci_hi:.1f}]\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nInitializing NUTS using jitter+adapt_diag...\nMultiprocess sampling (4 chains in 4 jobs)\nNUTS: [beta, y_hat_sigma]\nSampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 9 seconds.\nSampling: [beta, y_hat, y_hat_sigma]\nSampling: [y_hat]\nSampling: [y_hat]\nSampling: [y_hat]\nSampling: [y_hat]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nIntervention estimate: 25.1 GT points\n95% CI: [20.2, 29.6]\n```\n:::\n:::\n\n\nThe plot below shows the two panels side by side. **Panel A** is what you'd see *without* the framework: a posterior distribution of the cumulative effect. **Panel B** is what the framework adds: the pre-intervention FPR, Assurance, and Indeterminacy rates — the context you need to interpret Panel A with calibrated confidence.\n\n::: {#0cf82bea .cell execution_count=18}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — estimate with calibrated context\"}\nfig, (ax_post, ax_ctx) = plt.subplots(1, 2, figsize=(12, 5))\n\n# Panel A: Posterior estimate\nax_post.hist(\n    int_cumulative, bins=50, density=True, alpha=0.5,\n    color=cfg.C_TREATMENT, edgecolor=\"white\", linewidth=0.5,\n)\nax_post.axvline(0, color=\"#0f172a\", linestyle=\"--\", linewidth=1, alpha=0.5)\nax_post.axvspan(\n    -cfg.ROPE_HALF_WIDTH, cfg.ROPE_HALF_WIDTH,\n    alpha=0.1, color=\"#f59e0b\",\n)\nax_post.axvline(-cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", linestyle=\":\", linewidth=0.8, alpha=0.6)\nax_post.axvline(cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", linestyle=\":\", linewidth=0.8, alpha=0.6)\n_decision = bayesian_rope_decision(\n    int_cumulative, cfg.ROPE_HALF_WIDTH, cfg.DECISION_THRESHOLD,\n)\n_prob_above = float((int_cumulative > cfg.ROPE_HALF_WIDTH).mean())\nax_post.set_title(\n    \"A: Posterior Estimate (Same Regardless of Framework)\",\n    fontweight=\"bold\",\n)\nax_post.set_xlabel(\"Cumulative Effect (Google Trends Points)\")\nax_post.set_ylabel(\"Density\")\nax_post.text(\n    0.05, 0.95,\n    f\"Estimate: {int_mean:.1f}\\n\"\n    f\"95% CI: [{int_ci_lo:.1f}, {int_ci_hi:.1f}]\\n\"\n    f\"P(effect > ROPE): {_prob_above:.1%}\\n\"\n    f\"ROPE decision: {_decision}\",\n    transform=ax_post.transAxes, fontsize=8, va=\"top\",\n    bbox=dict(boxstyle=\"round,pad=0.4\", facecolor=\"white\", edgecolor=\"#e2e8f0\"),\n)\n\n# Panel B: Calibrated context\n_metrics = [\"FPR\", \"Assurance\", \"Null\\nIndet.\", \"Alt\\nIndet.\"]\n_values = [null_props[0], alt_props[0], null_props[2], alt_props[2]]\n_colors = [cfg.C_FPR, cfg.C_ASSURANCE, cfg.C_INDET, cfg.C_INDET]\n_bars = ax_ctx.bar(\n    _metrics, _values, color=_colors, alpha=0.85,\n    edgecolor=\"white\", linewidth=0.8, width=0.6,\n)\nfor _bar, _val in zip(_bars, _values):\n    ax_ctx.text(\n        _bar.get_x() + _bar.get_width() / 2, _val + 0.02,\n        f\"{_val:.1%}\", ha=\"center\", fontsize=9, fontweight=\"bold\",\n    )\nax_ctx.set_ylim(0, 1.1)\nax_ctx.set_ylabel(\"Probability\")\nax_ctx.set_title(\n    \"B: Calibrated Decision Context (Pre-Intervention)\",\n    fontweight=\"bold\",\n)\nax_ctx.set_axisbelow(True)\nax_ctx.grid(axis=\"y\", linestyle=\":\", alpha=0.4)\n\n_go_nogo = \"High confidence\" if alt_props[0] > 0.7 else \"Exercise caution\"\nax_ctx.text(\n    0.95, 0.95,\n    f\"How much to trust this estimate?\\n\"\n    f\"FPR (structural false positive): {null_props[0]:.1%}\\n\"\n    f\"Assurance (detection power): {alt_props[0]:.1%}\\n\"\n    f\"Interpretation: {_go_nogo}\",\n    transform=ax_ctx.transAxes, fontsize=8, va=\"top\", ha=\"right\",\n    bbox=dict(boxstyle=\"round,pad=0.4\", facecolor=\"#dbeafe\", edgecolor=cfg.C_ASSURANCE),\n)\nfig.suptitle(\n    \"Intervention Estimate + Calibrated Decision Risk\",\n    fontweight=\"bold\", fontsize=11,\n)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-19-output-1.png){width=1788 height=744}\n:::\n:::\n\n\nWithout the design analysis, the team sees Panel A: a large, precise positive effect. With the design analysis, they also see Panel B: 90.1% assurance that this design can detect effects in the expected range, tempered by the knowledge that the design has a 40.8% structural FPR. The estimate doesn't change, but the team's confidence in interpreting it does.\n\nThe intervention estimate of +14.5 GT points is far above the ROPE (±2.5) and within the expected-effect range (5–25), which makes this a high-confidence finding even given the elevated FPR. A smaller observed effect, say +4 points, would warrant considerably more caution given the same structural profile.\n\n## Sanity Checks\n\nBefore acting on the operating characteristics, we need to answer two uncomfortable questions:\n\n1. **\"Am I just seeing my prior?\"** — With only 4 placebo folds, the hierarchical model's prior for $\\tau_{het}$ could be driving the results.\n2. **\"Do I have enough placebo folds?\"** — With $J = 2$ folds, the between-fold variance is barely identifiable.\n\n### Test 1: Does the prior scale change the story?\n\nWe re-run the hierarchical model with three different prior widths for $\\tau_{het}$: $1\\times$, $2\\times$, and $4\\times$ the empirical standard deviation of the fold means. If the FPR, Assurance, and Indeterminacy are stable across a fourfold range of priors, the data is speaking louder than the prior.\n\n::: {#67d2f5d4 .cell execution_count=19}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — prior sensitivity analysis\"}\n_multipliers = [1.0, 2.0, 4.0]\n_sens_results = {}\n_n_folds = len(fold_means)\n_prior_mu_scale = float(np.nanstd(fold_means)) if np.nanstd(fold_means) > 0 else 1.0\n\nfor _mult in _multipliers:\n    _coords = {\"fold\": np.arange(_n_folds)}\n    with pm.Model(coords=_coords) as _m_sens:\n        pm.Data(\"obs_means_s\", fold_means, dims=\"fold\")\n        _obs_sd_s = pm.Data(\"obs_sd_s\", fold_sds, dims=\"fold\")\n        _mu_s = pm.Normal(\"mu_s\", mu=0.0, sigma=2.0 * _prior_mu_scale)\n        _tau_s = pm.HalfNormal(\"tau_s\", sigma=_mult * _prior_mu_scale)\n        _z_s = pm.Normal(\"z_s\", mu=0.0, sigma=1.0, dims=\"fold\")\n        _theta_s = pm.Deterministic(\"theta_s\", _mu_s + _tau_s * _z_s, dims=\"fold\")\n        pm.Normal(\n            \"lik_s\", mu=_theta_s, sigma=_obs_sd_s,\n            observed=fold_means, dims=\"fold\",\n        )\n        _idata_s = pm.sample(\n            draws=cfg.N_MCMC_DRAWS, tune=cfg.N_MCMC_TUNE,\n            chains=cfg.N_CHAINS, target_accept=0.97,\n            nuts_sampler=\"nutpie\", random_seed=cfg.SEED,\n            progressbar=False,\n        )\n    with _m_sens:\n        _m_sens.add_coords({\"new_period\": np.arange(1)})\n        pm.Normal(\"theta_new_s\", mu=_mu_s, sigma=_tau_s, dims=\"new_period\")\n        _ppc_s = pm.sample_posterior_predictive(\n            _idata_s, var_names=[\"theta_new_s\"], random_seed=cfg.SEED,\n            progressbar=False,\n        )\n    _theta_s_draws = (\n        _ppc_s[\"posterior_predictive\"][\"theta_new_s\"]\n        .stack(sample=(\"chain\", \"draw\")).values.squeeze()\n    )\n    _n_reps = int(min(_theta_s_draws.size, expected_effect_samples.size))\n    _rng_s = np.random.default_rng(cfg.SEED)\n    _null_dec, _alt_dec = [], []\n    for _i in range(_n_reps):\n        _sd_sim = _rng_s.choice(fold_sds)\n        _pn = _rng_s.normal(float(_theta_s_draws[_i]), _sd_sim, size=n_samples)\n        _null_dec.append(\n            bayesian_rope_decision(_pn, cfg.ROPE_HALF_WIDTH, cfg.DECISION_THRESHOLD)\n        )\n        _pa = _rng_s.normal(\n            float(expected_effect_samples[_i] + _theta_s_draws[_i]),\n            _sd_sim, size=n_samples,\n        )\n        _alt_dec.append(\n            bayesian_rope_decision(_pa, cfg.ROPE_HALF_WIDTH, cfg.DECISION_THRESHOLD)\n        )\n    _null_dec = np.array(_null_dec)\n    _alt_dec = np.array(_alt_dec)\n    _sens_results[_mult] = {\n        \"FPR\": np.mean(_null_dec == \"positive\"),\n        \"Assurance\": np.mean(_alt_dec == \"positive\"),\n        \"Null Indet.\": np.mean(_null_dec == \"indeterminate\"),\n    }\n\n_sens_df = pd.DataFrame(_sens_results).T\n_sens_df.index = [f\"{m:.0f}x\" for m in _multipliers]\n\nfig, axes = plt.subplots(1, 3, figsize=(11, 4), sharey=True)\n_metrics = [\"FPR\", \"Assurance\", \"Null Indet.\"]\n_colors = [cfg.C_FPR, cfg.C_ASSURANCE, cfg.C_INDET]\nfor ax, _metric, _color in zip(axes, _metrics, _colors):\n    ax.bar(\n        _sens_df.index, _sens_df[_metric], color=_color, alpha=0.85,\n        edgecolor=\"white\", linewidth=0.8, width=0.6,\n    )\n    ax.set_title(_metric)\n    ax.set_xlabel(r\"Prior scale ($\\sigma_\\tau$)\")\n    ax.set_ylim(0, 1.08)\n    ax.set_axisbelow(True)\n    for _idx_b, _v in enumerate(_sens_df[_metric]):\n        ax.text(\n            _idx_b, _v + 0.03, f\"{_v:.1%}\",\n            ha=\"center\", fontsize=8, fontweight=\"bold\",\n        )\naxes[0].set_ylabel(\"Probability\")\nfig.suptitle(\"Prior Sensitivity Analysis\", fontweight=\"bold\", fontsize=11)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSampling: [theta_new_s]\nSampling: [theta_new_s]\nSampling: [theta_new_s]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-20-output-2.png){width=1638 height=595}\n:::\n:::\n\n\nThe Assurance is largely stable across prior scales. The FPR shifts modestly, confirming that the elevated false positive rate is a property of the data, not an artifact of the prior.\n\n### Test 2: Do we have enough placebo folds?\n\nWe refit the hierarchical model using $J = 2, 3, 4$ folds and watch how $\\tau_{het}$ and $\\mu_{null}$ evolve. At $J = 2$, the posterior for $\\tau_{het}$ hugs zero — not because the true structural volatility is small, but because two data points can't identify a variance parameter. As we add folds, the posterior concentrates and stabilizes.\n\n::: {#d3546890 .cell execution_count=20}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — fold-count sensitivity\"}\n_max_folds = len(results_placebo)\n_js = np.arange(2, _max_folds + 1)\n_draws_per_chain = n_samples // cfg.N_CHAINS\n\n_tau_posteriors = {}\n_mu_posteriors = {}\n_prior_scale_ref = None\n_primary_j = cfg.N_FOLDS\n\nfor _j in _js:\n    _subset = results_placebo[:int(_j)]\n    _, _fm, _fs = extract_posteriors(_subset)\n    _prior_scale = float(np.nanstd(_fm)) if np.nanstd(_fm) > 0 else 1.0\n    _n_f = len(_fm)\n    _coords = {\"fold\": np.arange(_n_f)}\n    with pm.Model(coords=_coords) as _mdl:\n        pm.Data(\"obs_means\", _fm, dims=\"fold\")\n        _obs_sd = pm.Data(\"obs_sd\", _fs, dims=\"fold\")\n        _mu_rv = pm.Normal(\"mu\", mu=0.0, sigma=2.0 * _prior_scale)\n        _tau_rv = pm.HalfNormal(\"tau\", sigma=2.0 * _prior_scale)\n        _z = pm.Normal(\"z\", mu=0.0, sigma=1.0, dims=\"fold\")\n        _theta = pm.Deterministic(\"theta\", _mu_rv + _tau_rv * _z, dims=\"fold\")\n        pm.Normal(\"lik\", mu=_theta, sigma=_obs_sd, observed=_fm, dims=\"fold\")\n        _idata = pm.sample(\n            draws=_draws_per_chain, tune=cfg.N_MCMC_TUNE,\n            chains=cfg.N_CHAINS, target_accept=0.97,\n            nuts_sampler=\"nutpie\", random_seed=cfg.SEED,\n            progressbar=False,\n        )\n    _tau_posteriors[int(_j)] = _idata.posterior[\"tau\"].values.flatten()\n    _mu_posteriors[int(_j)] = _idata.posterior[\"mu\"].values.flatten()\n    if int(_j) == _primary_j:\n        _prior_scale_ref = 2.0 * _prior_scale\n\nif _prior_scale_ref is None:\n    _prior_scale_ref = 2.0 * _prior_scale\n\nfig, (ax_tau, ax_mu) = plt.subplots(1, 2, figsize=(12, 5))\n\n_cmap_vals = np.linspace(0.3, 0.85, len(_js))\n_j_colors = {\n    int(j_val): plt.cm.Blues(_cmap_vals[i])\n    for i, j_val in enumerate(sorted(_tau_posteriors))\n}\n\n# Left: tau_het\n_tau_upper = max(np.percentile(v, 99) for v in _tau_posteriors.values()) * 1.4\n_x_tau = np.linspace(0, _tau_upper, 400)\n_prior_tau_pdf = stats.halfnorm.pdf(_x_tau, scale=_prior_scale_ref)\nax_tau.fill_between(_x_tau, 0, _prior_tau_pdf, color=\"#e5e7eb\", alpha=0.5, label=\"Prior\", zorder=1)\nax_tau.plot(_x_tau, _prior_tau_pdf, color=\"#9ca3af\", ls=\"--\", lw=1.5, zorder=2)\nfor _j_val in sorted(_tau_posteriors):\n    _samples = _tau_posteriors[_j_val]\n    _reflected = np.concatenate([_samples, -_samples])\n    _kde = stats.gaussian_kde(_reflected)\n    _pdf = 2.0 * _kde(_x_tau)\n    _is_primary = (_j_val == _primary_j)\n    ax_tau.plot(\n        _x_tau, _pdf, color=_j_colors[_j_val],\n        lw=2.5 if _is_primary else 1.8,\n        label=f\"$J = {_j_val}$\" + (\" (primary)\" if _is_primary else \"\"),\n        alpha=0.95 if _is_primary else 0.7, zorder=3 + _j_val,\n    )\n    ax_tau.fill_between(\n        _x_tau, 0, _pdf, color=_j_colors[_j_val],\n        alpha=0.15 if _is_primary else 0.06, zorder=2,\n    )\n    _med = float(np.median(_samples))\n    ax_tau.axvline(_med, color=_j_colors[_j_val], ls=\":\", lw=1.0, alpha=0.6)\nax_tau.set_xlabel(r\"$\\tau_{het}$ (Structural Volatility)\", fontsize=10)\nax_tau.set_ylabel(\"Density\", fontsize=10)\nax_tau.set_title(r\"Posterior Evolution of $\\tau_{het}$\", fontsize=11, fontweight=\"bold\")\nax_tau.set_xlim(0, _tau_upper)\nax_tau.set_ylim(bottom=0)\nax_tau.legend(fontsize=8, loc=\"upper right\")\nax_tau.grid(True, alpha=0.15)\n\n# Right: mu_null\n_mu_abs = max(np.percentile(np.abs(v), 99) for v in _mu_posteriors.values()) * 1.5\n_x_mu = np.linspace(-_mu_abs, _mu_abs, 400)\n_prior_mu_pdf = stats.norm.pdf(_x_mu, loc=0.0, scale=_prior_scale_ref)\nax_mu.fill_between(_x_mu, 0, _prior_mu_pdf, color=\"#e5e7eb\", alpha=0.5, label=\"Prior\", zorder=1)\nax_mu.plot(_x_mu, _prior_mu_pdf, color=\"#9ca3af\", ls=\"--\", lw=1.5, zorder=2)\nfor _j_val in sorted(_mu_posteriors):\n    _samples = _mu_posteriors[_j_val]\n    _kde = stats.gaussian_kde(_samples)\n    _pdf = _kde(_x_mu)\n    _is_primary = (_j_val == _primary_j)\n    ax_mu.plot(\n        _x_mu, _pdf, color=_j_colors[_j_val],\n        lw=2.5 if _is_primary else 1.8,\n        label=f\"$J = {_j_val}$\" + (\" (primary)\" if _is_primary else \"\"),\n        alpha=0.95 if _is_primary else 0.7, zorder=3 + _j_val,\n    )\n    ax_mu.fill_between(\n        _x_mu, 0, _pdf, color=_j_colors[_j_val],\n        alpha=0.15 if _is_primary else 0.06, zorder=2,\n    )\n    _med = float(np.median(_samples))\n    ax_mu.axvline(_med, color=_j_colors[_j_val], ls=\":\", lw=1.0, alpha=0.6)\nax_mu.axvline(0, color=\"black\", ls=\"-\", lw=0.5, alpha=0.3)\nax_mu.set_xlabel(r\"$\\mu_{null}$ (Systematic Bias)\", fontsize=10)\nax_mu.set_ylabel(\"Density\", fontsize=10)\nax_mu.set_title(r\"Posterior Evolution of $\\mu_{null}$\", fontsize=11, fontweight=\"bold\")\nax_mu.set_xlim(-_mu_abs, _mu_abs)\nax_mu.set_ylim(bottom=0)\nax_mu.legend(fontsize=8, loc=\"upper right\")\nax_mu.grid(True, alpha=0.15)\n\nfig.suptitle(\n    r\"Prior$-$Posterior Sensitivity to Fold Count ($J$)\",\n    fontweight=\"bold\", fontsize=12,\n)\nfig.tight_layout(rect=[0, 0, 1, 0.94])\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-21-output-1.png){width=1789 height=744}\n:::\n:::\n\n\n**Rule of thumb:** $J \\ge 3$ is the minimum for the framework to be meaningful. With $J = 2$ you're essentially guessing.\n\n### Specification Diagnostics: Picking the Right Model\n\nThe framework doubles as a model selection tool. If the operating characteristics are unsatisfactory (high FPR, low assurance, or excessive indeterminacy), the natural next step is to improve the model.\n\nThe selection process follows a **\"Falsification and Efficiency\"** logic:\n\n1. **Define candidates.** Specify a set of theoretically distinct models. For Wendy's, this might include dropping weakly correlated brands or adding seasonal adjustments.\n2. **Run placebo calibration for each.** Execute the full framework on each candidate.\n3. **Apply selection criteria:** Flag any model where FPR exceeds your tolerance. Among valid models, prefer the one that minimizes $\\tau_{het}$ (equivalently, maximizes Assurance).\n\nFor the Wendy's case, the low correlations suggest that the Synthetic Control counterfactual is fundamentally limited by the available control pool. The specification diagnostic reveals this as a structural constraint of the data environment rather than a fixable modeling error.\n\n## Closing the Loop: Post-Intervention Calibrated Significance\n\nBefore the campaign, we asked: *\"If there's a real effect, will we detect it?\"* (Assurance). Now the campaign is over and we have an estimate in hand. The question flips:\n\n> **\"How likely is it that *structural noise alone* could have produced an estimate this large?\"**\n\nThis is the **calibrated tail probability** — the post-intervention counterpart to the pre-intervention Assurance.\n\n$$p_{cal} = P(\\tilde{m}_{new} \\geq \\hat{\\delta}_{obs} \\mid H_0)$$\n\nA tiny $p_{cal}$ means structural noise is extremely unlikely to explain the result. A large one means you can't rule it out.\n\n::: {#e0c654a8 .cell execution_count=21}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — calibration arc\"}\n_mu_null = float(np.mean(theta_new_samples))\n_sigma_null = float(np.std(theta_new_samples))\n_s_avg = float(np.mean(fold_sds))\n_sigma_pred = np.sqrt(_sigma_null**2 + _s_avg**2)\n_obs_sd = float(np.std(int_cumulative))\n\n# Calibrated tail probability\n_rng = np.random.default_rng(cfg.SEED)\n_noise_sds = _rng.choice(fold_sds, size=theta_new_samples.size)\n_pred_null = theta_new_samples + _rng.normal(0, _noise_sds)\n_p_tail = float(np.mean(_pred_null >= int_mean))\n_z_cal = (int_mean - _mu_null) / _sigma_pred\n\n# Shared x-axis\n_x_lo = min(_mu_null - 4 * _sigma_null, -5)\n_x_hi = max(int_mean + 4 * _obs_sd, 45)\n_x = np.linspace(_x_lo, _x_hi, 600)\n\n# PDFs\n_npd_pdf = stats.norm.pdf(_x, _mu_null, _sigma_null)\n_alt_pdf = expected_effect_dist.pdf(_x)\n_obs_pdf = stats.norm.pdf(_x, int_mean, _obs_sd)\n\nfig, ax = plt.subplots(figsize=(10, 5))\n\n# ROPE band\nax.axvspan(-cfg.ROPE_HALF_WIDTH, cfg.ROPE_HALF_WIDTH, alpha=0.12, color=\"#f59e0b\", zorder=1,\n           label=f\"ROPE [$\\\\pm${cfg.ROPE_HALF_WIDTH}]\")\nax.axvline(-cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", ls=\":\", lw=0.8, alpha=0.5, zorder=2)\nax.axvline(cfg.ROPE_HALF_WIDTH, color=\"#f59e0b\", ls=\":\", lw=0.8, alpha=0.5, zorder=2)\n\n# Null Predictive\nax.fill_between(_x, _npd_pdf, alpha=0.25, color=cfg.C_NULL, zorder=3)\nax.plot(_x, _npd_pdf, color=cfg.C_NULL, lw=1.8, zorder=4,\n        label=f\"Null Predictive ($\\\\mu$={_mu_null:.1f}, $\\\\sigma$={_sigma_null:.1f})\")\n\n# Expected-Effect Prior\nax.fill_between(_x, _alt_pdf, alpha=0.20, color=cfg.C_ALT, zorder=3)\nax.plot(_x, _alt_pdf, color=cfg.C_ALT, lw=1.8, zorder=4,\n        label=f\"Expected-Effect Prior $S_{{alt}}$\")\n\n# Observed Posterior\nax.fill_between(_x, _obs_pdf, alpha=0.30, color=cfg.C_TREATMENT, zorder=5)\nax.plot(_x, _obs_pdf, color=cfg.C_TREATMENT, lw=2.0, zorder=6,\n        label=f\"Observed Posterior ($\\\\mu$={int_mean:.1f}, $\\\\sigma$={_obs_sd:.1f})\")\n\nax.axvline(0, color=\"#0f172a\", ls=\"--\", lw=0.8, alpha=0.35, zorder=2)\n\nax.text(\n    0.97, 0.95,\n    f\"$z_{{cal}}$ = {_z_cal:.1f}\\n\"\n    f\"$P(\\\\hat{{\\\\delta}}_{{obs}} \\\\mid H_0)$ = {_p_tail:.4f}\\n\"\n    f\"$\\\\sigma_{{pred}}$ = {_sigma_pred:.1f}\",\n    transform=ax.transAxes, fontsize=8, va=\"top\", ha=\"right\",\n    bbox=dict(boxstyle=\"round,pad=0.4\", facecolor=\"white\", edgecolor=\"#e2e8f0\"),\n    zorder=10,\n)\n\nax.set_xlabel(\"Cumulative Effect (Google Trends Points)\")\nax.set_ylabel(\"Density\")\nax.set_title(\"Calibration Arc: Null, Prior, and Observed Posterior\", fontweight=\"bold\", fontsize=11)\nax.legend(loc=\"upper left\", fontsize=7.5, frameon=True, fancybox=False, edgecolor=\"#e2e8f0\")\nax.set_xlim(_x_lo, _x_hi)\nax.set_ylim(bottom=0)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-22-output-1.png){width=1488 height=739}\n:::\n:::\n\n\n**This completes the decision arc:**\n\n- **Pre-intervention:** $S_{alt}$ + Null Predictive → *\"Is the experiment worth running?\"* (go/no-go)\n- **Post-intervention:** Observed estimate + Null Predictive → *\"Is the result worth acting on?\"* (act/don't act)\n\n## Bonus: The Detection Gradient\n\nClassical power analysis gives you a single number: the Minimum Detectable Effect (MDE). Effects above it are \"detectable\"; below it, they're not. Reality is more nuanced.\n\nThe plot below shows **detection probability as a continuous function of the true effect size**. Instead of a binary threshold, you get a gradient: correct detection (blue), misclassification in the wrong direction (red), and non-detection (grey).\n\n::: {#b823e3f9 .cell execution_count=22}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show code — detection gradient\"}\n_mu = float(np.mean(theta_new_samples))\n_tau = float(np.std(theta_new_samples))\n_sa = float(np.mean(fold_sds))\n_delta = cfg.ROPE_HALF_WIDTH\n_z_thr = stats.norm.ppf(cfg.DECISION_THRESHOLD)\n_x_max = cfg.EXPECTED_EFFECT_UPPER * 2\n_eff = np.linspace(0, _x_max, 500)\n\n_prior_pdf = expected_effect_dist.pdf(_eff)\n_prior_mu = float(expected_effect_dist.mean())\n_prior_sd = float(expected_effect_dist.std())\n\nfig = plt.figure(figsize=(7, 7))\n_gs = gridspec.GridSpec(2, 1, height_ratios=[1, 5], hspace=0.06)\nax_p = fig.add_subplot(_gs[0])\nax = fig.add_subplot(_gs[1])\n\n# Top: Expected-Effect Prior density\nax_p.fill_between(_eff, 0, _prior_pdf, color=\"#22c55e\", alpha=0.25)\nax_p.plot(_eff, _prior_pdf, color=\"#22c55e\", lw=1.2, alpha=0.7)\nax_p.axvline(_delta, color=\"#f59e0b\", ls=\"--\", lw=1, alpha=0.5)\nax_p.axvspan(0, _delta, color=\"#9ca3af\", alpha=0.15)\nax_p.set_xlim(0, _x_max)\nax_p.set_yticks([])\nax_p.tick_params(labelbottom=False)\nfor _sp in [\"top\", \"right\"]:\n    ax_p.spines[_sp].set_visible(False)\nax_p.set_ylabel(\"Prior\\nDensity\", fontsize=7, rotation=0, labelpad=30, va=\"center\")\nax_p.set_title(\"Detection Gradient\", fontweight=\"bold\", fontsize=11, pad=6)\nax_p.text(\n    _prior_mu, _prior_pdf.max() * 0.55,\n    f\"Expected Effect Prior\\n$\\\\mu={_prior_mu:.1f}$, $\\\\sigma={_prior_sd:.1f}$\",\n    fontsize=7, ha=\"center\", color=\"#15803d\",\n)\n\n# Classification boundaries\n_bnd_pos = _delta + _z_thr * _sa\n_bnd_neg = -(_delta + _z_thr * _sa)\n\ndef _Phi(b):\n    return stats.norm.cdf((b - _eff - _mu) / _tau)\n\n_p_detect_raw = 1 - _Phi(_bnd_pos)\n_p_misclass_raw = _Phi(_bnd_neg)\n\n_below_rope = _eff <= _delta\n_p_detect = np.where(_below_rope, 0.0, _p_detect_raw)\n_p_misclass = np.where(_below_rope, 0.0, _p_misclass_raw)\n_p_nondetect = np.clip(1 - _p_detect - _p_misclass, 0, 1)\n\n_c1 = _p_nondetect\n_c2 = _c1 + _p_misclass\n\nax.fill_between(_eff, 0, _c1, color=cfg.C_NULL, alpha=0.30)\nax.fill_between(_eff, _c1, _c2, color=cfg.C_FPR, alpha=0.30)\nax.fill_between(_eff, _c2, 1, color=cfg.C_ASSURANCE, alpha=0.40)\nfor _curve, _col in [(_c1, cfg.C_NULL), (_c2, cfg.C_FPR)]:\n    ax.plot(_eff, _curve, color=_col, lw=0.8, alpha=0.5)\n\nax.axvspan(0, _delta, color=\"#9ca3af\", alpha=0.35, zorder=4)\nax.text(\n    _delta / 2, 0.50, \"Below\\nROPE\",\n    fontsize=8, ha=\"center\", va=\"center\", color=\"#4b5563\",\n    fontweight=\"bold\", zorder=5,\n    bbox=dict(boxstyle=\"round,pad=0.3\", fc=\"white\", ec=\"#9ca3af\", alpha=0.85),\n)\nax.axvline(_delta, color=\"#f59e0b\", ls=\"--\", lw=1.5, alpha=0.8, zorder=5)\n\n_guide_xs = [cfg.EXPECTED_EFFECT_LOWER, 5, 7, cfg.EXPECTED_EFFECT_UPPER]\nfor _x_val in _guide_xs:\n    ax.axvline(_x_val, color=\"black\", ls=\"-\", lw=0.8, alpha=0.5, zorder=6)\n    ax_p.axvline(_x_val, color=\"black\", ls=\"-\", lw=0.8, alpha=0.3)\n    _i_v = np.argmin(np.abs(_eff - _x_val))\n    _bands = [\n        (0, _c1[_i_v], _p_nondetect[_i_v], cfg.C_NULL, \"white\"),\n        (_c1[_i_v], _c2[_i_v], _p_misclass[_i_v], cfg.C_FPR, \"white\"),\n        (_c2[_i_v], 1.0, _p_detect[_i_v], cfg.C_ASSURANCE, \"white\"),\n    ]\n    for _y_lo, _y_hi, _prob_v, _bg_col, _fg_col in _bands:\n        _band_h = _y_hi - _y_lo\n        if _band_h > 0.045:\n            ax.text(\n                _x_val, (_y_lo + _y_hi) / 2, f\"{_prob_v:.0%}\",\n                fontsize=6.5, ha=\"center\", va=\"center\",\n                color=_fg_col, fontweight=\"bold\", zorder=7,\n                bbox=dict(boxstyle=\"round,pad=0.12\", fc=_bg_col, ec=\"none\", alpha=0.85),\n            )\n\n_mid_x = (_guide_xs[-2] + _guide_xs[-1]) / 2\n_i_lbl = np.argmin(np.abs(_eff - _mid_x))\nfor _y_lo_a, _y_hi_a, _label, _color in [\n    (np.zeros_like(_eff), _c1, \"Non-Detection\", \"#475569\"),\n    (_c1, _c2, \"Misclassification\", \"#991b1b\"),\n    (_c2, np.ones_like(_eff), \"Correct Detection\", \"#1e40af\"),\n]:\n    _bh = _y_hi_a[_i_lbl] - _y_lo_a[_i_lbl]\n    if _bh > 0.08:\n        ax.text(\n            _mid_x, (_y_lo_a[_i_lbl] + _y_hi_a[_i_lbl]) / 2, _label,\n            fontsize=6.5, ha=\"center\", va=\"center\", color=_color, fontweight=\"bold\",\n        )\n\nax.text(\n    0.97, 0.50,\n    rf\"$\\tau_{{\\mathrm{{het}}}} = {_tau:.2f}$\"\n    \"\\n\"\n    rf\"$\\mu_{{\\mathrm{{null}}}} = {_mu:.2f}$\",\n    fontsize=8, ha=\"right\", va=\"center\",\n    transform=ax.transAxes, color=\"#64748b\",\n    bbox=dict(boxstyle=\"round,pad=0.3\", fc=\"white\", ec=\"#cbd5e1\"),\n)\nax.set_xlim(0, _x_max)\nax.set_ylim(0, 1)\nax.set_xlabel(\"Absolute Effect Size (GT Points)\", fontsize=9)\nax.set_ylabel(\"Classification Probability\", fontsize=9)\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nax.grid(True, alpha=0.10)\n\n_legend_handles = [\n    mpatches.Patch(facecolor=cfg.C_ASSURANCE, alpha=0.40, label=\"Correct Detection\"),\n    mpatches.Patch(facecolor=cfg.C_FPR, alpha=0.30, label=\"Misclassification\"),\n    mpatches.Patch(facecolor=cfg.C_NULL, alpha=0.30, label=\"Non-Detection\"),\n]\nax.legend(handles=_legend_handles, loc=\"lower right\", fontsize=7, framealpha=0.9, edgecolor=\"#cbd5e1\")\nfig.suptitle(\"Operating Characteristic Regions by Effect Size\", fontweight=\"bold\", fontsize=12)\nfig.tight_layout(rect=[0, 0, 1, 0.94])\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](placebo_bayesian_quasi_experiments_files/figure-html/cell-23-output-1.png){width=939 height=992}\n:::\n:::\n\n\nInstead of asking *\"Is my MDE good enough?\"*, you can ask *\"At a 10-point lift, what's my detection probability? What about 5 points?\"* This is much more useful for real decision-making.\n\n## When This Framework Breaks\n\n**Regime shifts.** The framework assumes that structural errors during placebo windows are representative of those during the intervention period. If the campaign coincides with a unique structural break (a competitor's viral moment, a macroeconomic shock), the null predictive distribution will be miscalibrated.\n\n**Too few placebo folds.** With $J < 3$, the between-fold variance is essentially unidentifiable. We recommend $J \\ge 3$ as a minimum and sensitivity analysis over the prior scale for $\\tau_{het}$.\n\n**Weak controls.** When treatment–control correlations are low (as in the Wendy's case), the Synthetic Control counterfactual is imprecise, inflating $\\tau_{het}$ and the FPR. The framework correctly diagnoses this weakness but cannot fix it; the solution is better control data, not a better calibration procedure.\n\n**Misspecified stakeholder inputs.** If the ROPE is set too narrow, everything becomes indeterminate. If the expected-effect prior is set too optimistically, assurance will be overstated. These inputs require genuine domain knowledge and should be stress-tested.\n\n## Conclusion\n\nQuasi-experimental estimates are only as trustworthy as the structural environment in which they are produced. The framework presented here transforms the question from *\"Is this result significant?\"* to *\"How capable is this specific design of distinguishing signal from noise in this specific data environment?\"*\n\nThe Wendy's case study illustrates both the power and the limitations of the approach. The Krabby Patty Kollab produced a signal (+14.5 GT points) large enough to be confidently detected (90.1% assurance) despite a data environment with substantial structural noise (40.8% FPR). A weaker campaign in the same environment would face genuine interpretability challenges, and the design analysis would have flagged this *before* the campaign launched.\n\nWe encourage practitioners to treat design analysis as a routine step in any quasi-experimental workflow, not as an academic exercise, but as a practical audit of decision reliability.\n\n## Code and Data Availability\n\nAll code and data for this analysis are available at [my personal repository](https://github.com/cetagostini/placebo-in-time-quasi-experiment). The Google Trends dataset is publicly reproducible. The analysis relies on open-source software: PyMC for Bayesian inference, CausalPy for the quasi-experimental estimator, PreliZ for prior elicitation, and nutpie for MCMC sampling.\n\n## Authors\n\n- Carlos Trujillo [@cetagostini](https://github.com/cetagostini)\n- Anton Bugaev [@aabugaev](https://github.com/aabugaev)\n\n",
    "supporting": [
      "placebo_bayesian_quasi_experiments_files"
    ],
    "filters": [],
    "includes": {}
  }
}